package-lock.json
package.json
src/App.tsx
src/collection/routes.ts
src/collection/views/Collection.tsx
src/detail/routes.ts
src/item/routes.ts
src/item/views/Item.tsx
src/routes.ts
src/search/views/Search.tsx
src/shared/helpers/generateLink.tsx
src/shared/store/collection/collectionActions.ts
src/shared/store/item/itemActions.ts
src/shared/types/DeclaredModules.d.ts

This PR goes together with PRs:
* https://github.com/viaacode/avo2-typings/pull/6
* https://github.com/viaacode/avo2-proxy/pull/11
And should be merged after:
* https://github.com/viaacode/avo2-components/pull/56

feat: add collection detail page + rename detail to item

---

src/item/views/Item.tsx

https://district01.atlassian.net/browse/AVO2-183

feat: format video description on item detail page

---

src/item/views/Item.tsx
src/search/views/Search.tsx

https://district01.atlassian.net/browse/AVO2-99
Can be merged after release of 1.3.0 components
requires additional fixes after merge:
https://district01.atlassian.net/browse/AVO2-365

Feature: Allow keywords on item detail page to be clickable

---

src/search/views/Search.tsx

closes: https://district01.atlassian.net/browse/AVO2-365

fix: execute initial search after query param analysis

---

package-lock.json
package.json
src/item/views/Item.scss
src/item/views/Item.tsx

- Divide details table in 2 columns on appropriate screen sizes. (above 300)
- Fix width of Video Player to 100% without margin.
- Wrap buttons under Video Player and add margin.

Style-fixes for mobile Item page.

---

src/search/views/Search.tsx
src/shared/helpers/formatters/resolve-html.test.ts
src/shared/helpers/formatters/strip-html.ts

feat: cleanup collection description html in search page

---

src/item/views/Item.tsx
src/shared/helpers/generateLink.tsx

fix: encode search filters in url and fix educationLevel

---

package.json
src/setupTests.ts
src/shared/components/CheckboxDropdownModal/CheckboxDropdownModal.test.tsx
src/shared/components/DateRangeDropdown/DateRangeDropdown.test.tsx

run with:
```
npm run unit-tests
```

fix: fix unit tests

---

package-lock.json
src/collection/views/Collection.tsx

fix: fix issue where collection owner and role didn't show up

---

src/my-workspace/types.ts
src/my-workspace/views/MyWorkspace.tsx

https://district01.atlassian.net/browse/AVO2-604

AVO2-604: Remove add button on collection overview page.

---

src/index.tsx
src/shared/types/moment-locales.d.ts

fix: set moment locale to nl-be

---

src/collection/types.ts
src/collection/views/Collection.tsx
src/home/views/Home.tsx
src/item/views/Item.tsx
src/search/components/SearchResults/SearchResultItem.tsx
src/shared/helpers/generateLink.tsx

fix: fix issues with content type now being in dutch

---

src/collection/components/CollectionFragment.tsx
src/collection/components/ShareCollectionModal.tsx

> Publicatie collectie:Tekstblokken in een collectie moeten een titel OF een omschrijving hebbenDus de media-items regel blijft behouden (titel en omschrijving)En voor tekstblokken is er een andere regel

AVO2-633: Reduce validation on fragment title/description.

---

src/assignment/routes.tsx
src/assignment/types.ts
src/assignment/views/Assignment.tsx
src/assignment/views/Assignments.tsx
src/assignment/views/EditAssignment.tsx
src/constants.ts
src/item/views/Item.tsx
src/my-workspace/constants.ts
src/my-workspace/routes.tsx
src/my-workspace/views/MyWorkspace.tsx
src/routes.tsx
src/shared/components/DataComponent/DataQueryComponent.tsx

feat: build assignments edit page while waiting for db tables

---

src/collection/views/Collections.scss
src/collection/views/Collections.tsx

fix(collection-overview): show bigger thumbnail in overview

---

src/collection/components/modals/ShareCollectionModal.tsx
src/collection/graphql.ts
src/collection/views/EditCollection.tsx
src/collection/views/EditCollectionMetadata.tsx

closes: https://district01.atlassian.net/browse/AVO2-684

fix(collection-share): reset public modal errors + save before public

---

src/collection/components/modals/ShareCollectionModal.tsx

closes: https://district01.atlassian.net/browse/AVO2-683

fix(collection-publish-modal): fix external id === -1 is not a video

---

src/collection/components/modals/ShareCollectionModal.tsx

fix(edit-collection-view): do not verify fields during de-publish coll

---

src/collection/views/Collections.tsx
src/collection/views/EditCollectionMetadata.tsx
src/shared/components/DataComponent/DataQueryComponent.tsx

closes: https://district01.atlassian.net/browse/AVO2-690

feat(collections): refetch collections after collection delete

---

src/authentication/helpers/permission-service.ts
src/collection/views/Collection.tsx

https://district01.atlassian.net/browse/AVO2-634

fix(collection-detail): add permission guard around edit and delete coll

---

src/collection/graphql.ts

otherwise you get this long error: 
index.js:1375 Error: Network error: Error writing result to store for query

fix(collection): query collection with fragments with items with id

---

src/assignment/graphql.ts
src/assignment/types.ts
src/assignment/views/AssignmentDetail.tsx
src/search/views/Search.tsx
src/shared/components/DataComponent/LoadingErrorLoadedComponent.tsx

feat(assignment-response): create assignment responses + de/archive

---

package.json
src/assignment/graphql.ts
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentOverview.tsx
src/collection/components/modals/CollectionStillsModal.tsx
src/collection/graphql.ts
src/collection/helpers.ts
src/collection/helpers.tsx
src/collection/views/CollectionDetail.tsx
src/collection/views/CollectionEdit.tsx
src/collection/views/CollectionOverview.scss
src/collection/views/CollectionOverview.tsx
src/shared/components/DataComponent/LoadingErrorLoadedComponent.tsx
src/shared/services/stills-service.ts
src/shared/services/toast-service.tsx

Fix issues with db column rename + set thumbnail for collection when saving

---

src/assignment/views/AssignmentEdit.tsx

issue was caused by multiple useEffects which all set the the currentAssignment state without waiting on eachother.
You could reproduce the issue as follows:
* search for a video
* make assignment
expected result: assignment edit screen
broken result: spinner kept spinning

fix(assignment-edit): Fix issue with assignment-edit eternal spinner

---

src/collection/views/CollectionEdit.tsx

old header (left), prototype (right)
new header (left), prototype (right)

fix(collection-edit): fix styling issues with the collection edit header

---

src/404/routes.tsx
src/assignment/routes.tsx
src/authentication/routes.tsx
src/collection/routes.tsx
src/discover/routes.tsx
src/home/routes.tsx
src/item/routes.tsx
src/my-workspace/routes.tsx
src/routes.tsx
src/search/routes.tsx

fix(routing): avoid multiple login checks + render arrays

---

src/authentication/components/PermissionGuard.tsx
src/authentication/helpers/permission-service.ts
src/collection/graphql.ts
src/collection/views/CollectionDetail.tsx

Users would not have the permission to edit a collection from the detail page
This is now fixed
Also fixed bug in permission service
Added profile parameter info when checking permissions in permission service

fix(collection-detail): show edit button in more options

---

src/assignment/types.ts
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentEdit.tsx
src/item/components/ItemVideoDescription.tsx

https://district01.atlassian.net/browse/AVO2-658

feat(assignment-detail): add option to show detail without video descr.

---

src/collection/views/CollectionOverview.scss

fix(collection-overview): fixed collection overview thumbnails again

---

src/collection/views/CollectionEditContent.tsx

Otherwise this will create bugs when the elements position change over time

fix(collection-edit): don't use index in key

---

src/shared/services/stills-service.ts

closes: https://district01.atlassian.net/browse/AVO2-617
example: http://localhost:8080/collectie/7/bewerk

fix(stills-service): show default thumbnail (MAM) for uncut videos

---

src/collection/views/CollectionDetail.tsx
src/item/views/Item.tsx
src/shared/services/related-items-service.ts

requires this PR from proxy: https://github.com/viaacode/avo2-proxy/pull/48
https://district01.atlassian.net/browse/AVO2-298

feat(item-detail-collection-detail): fetch and show related items/coll.

---

src/assignment/views/AssignmentEdit.tsx
src/authentication/store/selectors.test.ts
src/collection/components/modals/CutFragmentModal.tsx
src/collection/graphql.ts
src/collection/helpers/validation.ts
src/collection/service.tsx
src/collection/views/CollectionEdit.tsx
src/item/components/modals/FragmentAddToCollection.tsx
src/search/store/selectors.test.ts

https://district01.atlassian.net/browse/AVO2-725
Also moved a lot of the collection graphql code to a separate collection service

Feature: copy collection when creating assignment from public collection

---

src/assignment/services.ts
src/collection/components/modals/CutFragmentModal.tsx
src/collection/components/modals/ShareCollectionModal.tsx
src/collection/service.tsx
src/shared/services/toast-service.tsx

bugfix(toastservice): allow multiline toast messages as string[ ]

---

src/assignment/views/AssignmentDetail.scss
src/assignment/views/AssignmentDetail.tsx

fix(assignment-detail): remove collapse and fixed code for description

---

src/item/components/modals/FragmentAddToCollection.tsx

https://district01.atlassian.net/browse/AVO2-785

fix(add-fragment-collection-modal): set thumbnail on collection create

---

src/collection/service.tsx
src/collection/views/CollectionEdit.tsx

Removed unnecessary cache clear as state takes care of this already. Fixes the issue.

AVO2-809: Fix infinite load after rename

---

src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentOverview.tsx
src/collection/components/FragmentEdit.tsx
src/collection/helpers.tsx
src/collection/types.ts
src/collection/views/CollectionDetail.tsx
src/collection/views/CollectionEdit.tsx
src/collection/views/CollectionEditMetaData.tsx
src/home/views/Home.tsx
src/item/views/Item.tsx
src/search/components/SearchResults/SearchResultItem.tsx
src/shared/components/modals/InputModal.tsx
src/shared/helpers/dropdown.ts

- Implemented Header component.
- Refactored CollectionEdit, CollectionDetail.
- More "functional" structure.
- Refactored dropdown item logic to avoid too much logic in component template.
- Commented out more "DISABLED FEATURES" because they are a future feature that is not finished yet, so shouldn't be visible on QAS.

AVO2-819: Implement Header component in CollectionEdit & CollectionDetail

---

src/assignment/assignment.services.ts
src/assignment/views/AssignmentEdit.tsx

closes: https://district01.atlassian.net/browse/AVO2-787

fix(assignment-edit): show warning not error for deadline in the past

---

src/assignment/views/AssignmentDetail.tsx
src/collection/collection.gql.ts
src/collection/components/fragment/FragmentDetail.tsx
src/collection/components/fragment/FragmentListDetail.tsx
src/collection/components/index.ts
src/collection/views/CollectionDetail.tsx

closes: https://district01.atlassian.net/browse/AVO2-657
implements option to hide video description in assignment detail

feat(assignment-detail): hide video description option

---

src/item/item.gql.ts
src/item/views/Item.tsx

This PR requires a change in the typings: https://github.com/viaacode/avo2-typings/pull/23

fix(item-detail): correctly show published at date and added at date

---

src/authentication/authentication.const.ts
src/authentication/helpers/get-profile-info.ts
src/authentication/helpers/redirect-to-idp.ts

This simplifies logout for the frontend
This requires this proxy pr: https://github.com/viaacode/avo2-proxy/pull/58

fix(auth): use single logout route from the proxy

---

src/item/components/modals/AddToCollectionModal.tsx

1. Open video.
2. Add to new Collection "TEST123".
3. Open another video. 
4. Add to same collection. (Previously, the newly made "TEST123" collection would not be in the list yet until refresh.)

AVO2-858: Refetch collections after adding item to new collection.

---

src/authentication/views/registration-flow/r3-stamboek.tsx
src/collection/collection.const.ts
src/constants.ts
src/shared/components/DateRangeDropdown/DateRangeDropdown.test.tsx
src/shared/constants/index.ts
src/shared/constants/routes.ts
src/shared/helpers/link.test.ts
src/shared/helpers/link.tsx

This is needed to bring the route in line with avo1

fix(routing): switch collection to collections route + cleanup

---

src/authentication/components/SecuredRoute.tsx
src/authentication/helpers/get-profile-info.ts
src/constants.ts
src/search/views/Search.tsx
src/settings/components/Profile.tsx
src/settings/settings.const.ts
src/settings/settings.routes.tsx
src/shared/components/Navigation/Navigation.tsx
src/shared/constants/routes.ts

required fields:
* onderwijsniveau
* scholen
* vakken

feat(profile): enforce profile be complete before allowing people in

---

src/authentication/helpers/get-profile-info.ts
src/constants.ts
src/shared/components/Navigation/Navigation.tsx

according to the prototype this should be the first name instead of the full name:

fix(navigation): show firstname instead of full name

---

public/index.html

feat(zendesk): add zendesk widget to bottom right of site

---

src/authentication/helpers/get-profile-info.ts
src/authentication/helpers/redirects.ts
src/authentication/store/types.ts
src/settings/components/Account.tsx
src/settings/settings.routes.tsx
src/shared/components/Navigation/Navigation.tsx

This PR requires proxy changes: https://github.com/viaacode/avo2-proxy/pull/67

feat(account): link + unlink smartschool account

---

src/authentication/components/LoginOptions.scss
src/authentication/components/LoginOptions.tsx
src/authentication/components/LoginOptionsDropdown.scss
src/authentication/components/LoginOptionsDropdown.tsx
src/authentication/components/PupilOrTeacherDropdown.tsx
src/authentication/views/RegisterOrLogin.tsx
src/authentication/views/registration-flow/r3-stamboek.tsx
src/shared/components/Navigation/Navigation.tsx

fix(login-flow): rework login flow

---

src/authentication/authentication.service.ts
src/authentication/components/StamboekInput.scss
src/authentication/components/StamboekInput.tsx
src/authentication/views/registration-flow/r3-stamboek.tsx
src/collection/components/modals/ShareCollectionModal.tsx
src/settings/components/Account.tsx
src/settings/components/Profile.tsx
src/settings/settings.service.ts
src/shared/components/Navigation/Navigation.tsx

er is nog steeds een issue met de dropdown onchange event voor de organizations

feat(profile): AVO2-437 save profile info to database

---

src/collection/components/fragment/FragmentEdit.tsx
src/shared/constants/index.ts
src/shared/constants/wysiwyg.ts

For future use once roles are implemented.

Add wysiwyg options as constants.

---

src/admin/content-block/components/ContentBlockForm/ContentBlockForm.tsx
src/admin/content-block/content-block.types.ts
src/admin/content-block/helpers/generators/buttons.ts
src/admin/content-block/helpers/generators/defaults.ts

As an example. Buttons is max 3. CTA will be min 2, max 2.

Add min & max limits for components in content block

---

src/search/views/Search.tsx

otherwise the search term is reset
closes: https://district01.atlassian.net/browse/AVO2-876

fix(search): apply search term when applying search filter

---

src/collection/collection.gql.ts
src/item/components/ItemVideoDescription.tsx

AVO2-912: Display issued date and organisation name in fullscreen FlowPlayer.

---

package-lock.json
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentEdit.tsx
src/collection/views/CollectionDetail.tsx
src/content-page/views/ContentPage.tsx
src/item/views/Item.tsx

closes: https://district01.atlassian.net/browse/AVO2-952

fix(content-page): load new content page if route changes

---

src/search/search.types.ts
src/search/store/actions.ts
src/search/views/Search.tsx

fix(search): improve error handling when request to ES fails

---

src/bundle/views/BundleDetail.tsx
src/collection/collection.gql.ts
src/collection/collection.service.ts
src/collection/views/CollectionDetail.tsx

feat(bundle-detail): show published bundles that contain collection

---

src/collection/collection.service.ts
src/collection/collection.types.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleEditContent.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/collection/components/modals/CutFragmentModal.tsx

steps to reproduce issue before this PR:
edit collection
enable custom fields switch
add some text
save collection
reload page
expected: custom fields switch is still enabled
current: custom fields switch is back in the off position

Fix issue with use_custom_fields in collection edit page

---

src/collection/collection.gql.ts

- Men kan weer items toevoegen aan collecties.
- Men kan weer collecties toevoegen aan bundels.

fix(bundle): remove return props

---

src/assignment/assignment.gql.ts
src/assignment/views/AssignmentDetail.tsx

closes issue: https://district01.atlassian.net/browse/AVO2-989

Fix: Assignment edit page doesn't load

---

src/collection/components/CollectionOrBundleEditMetaData.tsx

closes: https://district01.atlassian.net/browse/AVO2-993

fix(collection-edit-meta): fix infinite spinner on save meta data

---

src/assignment/views/AssignmentDetail.tsx
src/bundle/views/BundleDetail.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/collection/views/CollectionDetail.tsx
src/shared/helpers/formatters/avatar.tsx

closes: https://viaadocumentation.atlassian.net/browse/AVO-75

fix(bundle-collection): hide bundle description and make avatars dark

---

src/item/views/Item.tsx

Steps:
* go to an item detail page
* add it to an existing collection
expected result:
the add to collection modal closes and the item detail is visible again
current result:
The add to collection modal closes and you see an infinite spinner

fix(item-detail): fix infinite spinner after adding item to collection

---

src/admin/content/views/ContentEdit.tsx
src/admin/menu/views/MenuDetail.tsx
src/admin/menu/views/MenuEdit.tsx

closes: https://viaadocumentation.atlassian.net/browse/AVO-16

fix(admin): reverse order save buttons in admin dashboard

---

src/admin/shared/helpers/content-picker/internal-link.ts

* add setting routes
* add workspace routes
* remove assignment create route since it needs specific query params
* sort the paths alphabetically

fix(content-picker): add more static routes

---

src/admin/content/views/ContentEdit.tsx

fix(content-page-edit): require path and check uniqueness

---

src/assignment/assignment.routes.tsx
src/assignment/views/AssignmentCreate.tsx

Split assignment edit from create page
before this PR you would get an infinite spinner for the edit page of an assignment

fix(assignment-edit): fix inifinite spinner on create and edit page

---

src/search/components/SearchFilterControls.tsx

fix(search): remove duplicate subject filter

---

src/search/components/SearchFilterControls.tsx

relates to: https://meemoo.atlassian.net/browse/DEV-632

fix(search): remove capitalize function from provider name

---

src/admin/content/content.gql.ts
src/content-page/content-page.gql.ts

This will fix the page width in the admin content edit/detail views
For the actual content pages you will need this proxy PR: https://github.com/viaacode/avo2-proxy/pull/97

fix(content): add missing content_width property in queries

---

src/dynamic-route-resolver/views/DynamicRouteResolver.tsx
src/item/item.gql.ts

closes: https://district01.atlassian.net/browse/AVO2-574
example media mosa url:
http://localhost:8080/media/pieten-pact/A13eTSfXWZNJWXQVGXMA65VL

fix(dynamic-route-resolver): add support for mediamosa item urls

---

src/admin/content/views/ContentDetail.tsx

feat(content-detail): show all fields on content detail page

---

src/admin/content/views/ContentOverview.tsx

feat(content-overview): allow search pages by label in textfield

---

src/admin/interactive-tour/views/InteractiveTourEdit.tsx
src/shared/translations/nl.json

fix(interactive-tour-edit): render tooltip as html

---

src/admin/admin.const.ts
src/admin/content/content.const.tsx

Add content shortcuts for Pagina's and Screencasts on admin navigation.

feat(admin-content): add shortcuts

---

src/shared/components/ShareThroughEmailModal/ShareThroughEmailModal.tsx

- When item is being shared by email, close modal on success.

feat(share-email): close when done

---

src/shared/components/Navigation/Navigation.scss
src/shared/components/Navigation/Navigation.tsx
src/shared/components/Navigation/NavigationItem.tsx

part of: https://district01.atlassian.net/browse/AVO2-571
before:
after:

fix(navigation): fix styles and behavior for mobile site menu

---

src/item/components/ItemVideoDescription.scss
src/item/components/ItemVideoDescription.tsx
src/item/views/ItemDetail.scss

part of: https://district01.atlassian.net/browse/AVO2-571
|item detail before|item detail after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/77154213-90cc3a80-6a9b-11ea-9785-cbefbddd4159.png)|![image](https://user-images.githubusercontent.com/1710840/77154237-975ab200-6a9b-11ea-95f9-91e599b7b19d.png)|

fix(item-detail): fix video player margins

---

src/admin/shared/components/ContentPicker/ContentPicker.tsx
src/item/item.service.ts

Items in content picker didn't inflate anymore, now they do.

fix(content-picker): inflate items

---

src/App.tsx
src/shared/components/CookieDeclaration/CookieDeclaration.scss
src/shared/components/CookieDeclaration/CookieDeclaration.tsx
src/shared/components/index.ts
src/shared/services/toast-service.tsx

closes: https://district01.atlassian.net/browse/AVO2-590

feat(cookie-declaration): add a cookie declaration

---

src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleEditContent.tsx
src/collection/components/fragment/FragmentAdd.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/collection/components/modals/CutFragmentModal.tsx
src/collection/helpers/fragment.ts
src/collection/helpers/index.ts

closes: https://meemoo.atlassian.net/browse/AVO-110

Fix: slow typing in collection fragment title

---

src/assignment/views/AssignmentOverview.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/workspace/views/BookmarksOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-146

fix(assignment-overview): show blankslate when no assignments exist yet

---

src/admin/content/views/ContentEdit.tsx
src/admin/content/views/ContentOverview.tsx

closes: https://district01.atlassian.net/browse/AVO2-220

fix(content-pages): correctly check permission list for protected pages

---

src/collection/collection.gql.ts
src/collection/collection.service.ts
src/collection/collection.types.ts
src/collection/views/CollectionDetail.tsx
src/item/views/ItemDetail.tsx
src/search/components/SearchFilterControls.tsx
src/search/components/SearchResultItem.tsx
src/search/components/SearchResults.tsx
src/search/search.types.ts
src/search/views/Search.tsx
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.const.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.gql.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.types.ts
src/workspace/views/BookmarksOverview.tsx

closes: https://district01.atlassian.net/browse/AVO2-644
This PR requires changes in all 4 repos:
* https://github.com/viaacode/avo2-typings/pull/56
* https://github.com/viaacode/avo2-components/pull/267
* https://github.com/viaacode/avo2-proxy/pull/112
* https://github.com/viaacode/avo2-client/pull/496

feat(search): add content labels and bookmark btn to search results page

---

src/authentication/helpers/redirects.ts
src/bundle/views/BundleDetail.tsx
src/collection/collection.types.ts
src/collection/components/CollectionOrBundleOverview.tsx
src/collection/components/modals/ShareCollectionModal.tsx
src/collection/views/CollectionDetail.tsx
src/constants.ts
src/search/components/SearchFilterControls.tsx
src/shared/services/related-items-service.ts

closes: 
* https://district01.atlassian.net/browse/AVO2-1046
* https://meemoo.atlassian.net/browse/AVO-93
Twin on the proxy: https://github.com/viaacode/avo2-proxy/pull/111

fix(collection-detail): fix related items, allow search for bundles

---

src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx

closes: https://district01.atlassian.net/browse/AVO2-108

feat(bundle-detail): add bookmark button

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx
src/admin/content-block/helpers/generators/media-grid.ts
src/admin/shared/helpers/content-picker/parse-picker.ts
src/shared/components/LoadingErrorLoadedComponent/LoadingErrorLoadedComponent.tsx
src/shared/helpers/parsers/number.ts
src/shared/services/content-page-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-214
proxy twin PR: https://github.com/viaacode/avo2-proxy/pull/114

fix(media-grid-block): allow selection of bundles,fix media grid preview

---

src/authentication/components/LoginOptions.scss
src/authentication/components/LoginOptions.tsx
src/authentication/helpers/redirects.ts
src/authentication/views/RegisterOrLogin.scss
src/settings/components/Account.tsx
src/styles/components/_index.scss
src/styles/components/_oauth-buttons.scss
src/styles/settings/_colors.scss

closes: 
* https://district01.atlassian.net/browse/AVO2-159
* https://district01.atlassian.net/browse/AVO2-263
* https://meemoo.atlassian.net/browse/AVO-149
* https://meemoo.atlassian.net/browse/AVO-150
Proxy twin: https://github.com/viaacode/avo2-proxy/pull/113

feat(auth): add klascement login, fix login button styles

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/assignment/views/AssignmentCreate.tsx
src/authentication/components/SecuredRoute.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/settings/components/Profile.tsx
src/shared/components/Footer/Footer.tsx
src/shared/components/LoadingErrorLoadedComponent/LoadingErrorLoadedComponent.tsx
src/shared/components/Navigation/Navigation.test.tsx
src/shared/components/Navigation/Navigation.tsx
src/shared/hocs/withUser.tsx

refactor(with-user): use hoc component where possible to get user

---

package.json
src/collection/collection.helpers.tsx
src/collection/components/fragment/FragmentEdit.tsx

fix(bundle-edit): fix title validation for bundle edit page

---

src/admin/permission-groups/permission-group.service.ts
src/admin/user-groups/user-group.gql.ts
src/admin/user-groups/user-group.service.ts
src/admin/user-groups/views/UserGroupDetail.scss
src/admin/user-groups/views/UserGroupDetail.tsx
src/admin/user-groups/views/UserGroupEdit.tsx

also:
* move getUserGroupById to service
* move getAllPermissionGroups to permissionGroup service

feat(user-group): show permissions below each permission group

---

package-lock.json
package.json
src/admin/Admin.scss
src/admin/Admin.tsx
src/admin/content/views/ContentEdit.scss
src/admin/content/views/ContentEditContentBlocks.tsx
src/admin/shared/components/Sidebar/Sidebar.scss
src/react-app-env.d.ts

closes: https://meemoo.atlassian.net/browse/AVO-85

feat(content-edit): make panes independently scrollable and resizable

---

src/admin/menu/menu.service.ts
src/admin/menu/views/MenuDetail.scss
src/admin/menu/views/MenuDetail.tsx
src/admin/menu/views/MenuEdit.tsx
src/admin/menu/views/MenuOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-67

fix(admin-navigation): rework menu screens + refetch after delete

---

src/bundle/views/BundleDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-135

fix(bundle-detail): show custom title of collection if enabled

---

src/search/views/Search.tsx

closes: https://meemoo.atlassian.net/browse/AVO-140

fix(search): avoid unnecessary redirects to keep browser history clean

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.const.ts
src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content-block/helpers/generators/image-grid.ts

closes: https://meemoo.atlassian.net/browse/AVO-189
Requires components PR: https://github.com/viaacode/avo2-components/pull/277

Image grid: add optional link and optional button to image grid items

---

src/collection/components/CollectionOrBundleOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-27

fix(collection-overview): add column to show public status

---

src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-198

fix(bundle-detail): render meta data with same layout as collection

---

src/admin/content/views/ContentEditContentBlocks.tsx
src/shared/helpers/link.tsx

closes: https://meemoo.atlassian.net/browse/AVO-264
test url: http://localhost:8080/beheer/content/212

fix(link): handle www urls als absolute by prefixing with //

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx
src/admin/content/views/ContentEditContentBlocks.tsx
src/admin/shared/components/ContentPicker/ContentPicker.scss
src/admin/shared/components/ContentPicker/ContentPicker.tsx
src/admin/shared/helpers/content-picker/parse-picker.ts
src/admin/shared/types/content-picker.ts
src/authentication/helpers/redirects.ts
src/shared/helpers/link.tsx

closes: https://meemoo.atlassian.net/browse/AVO-265
requires component PR: https://github.com/viaacode/avo2-components/pull/282

feat(content-picker): add link target toggle button

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.const.ts
src/admin/content-block/components/wrappers/ImageGridWrapper/ImageGridWrapper.tsx
src/admin/content-block/components/wrappers/index.ts
src/admin/content-block/content-block.const.ts
src/admin/content-block/helpers/generators/image-grid.ts
src/admin/content/views/ContentEditContentBlocks.tsx
src/admin/shared/types/content-block.ts

closes: https://meemoo.atlassian.net/browse/AVO-187

feat(image-grid-block): limit images sizes to predefined list

---

src/collection/collection.helpers.tsx
src/collection/collection.service.ts
src/collection/collection.types.ts
src/collection/components/CollectionOrBundleEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-590

fix(collection-edit): fix inserting fragment position + update fragments

---

src/collection/components/CollectionOrBundleEdit.tsx
src/collection/helpers/fragment.ts
src/shared/components/DraggableList/DraggableList.scss
src/shared/components/DraggableList/DraggableList.test.tsx
src/shared/components/DraggableList/DraggableList.tsx
src/shared/components/DraggableList/DraggableListModal.tsx
src/styles/components/_draggable_items.scss
src/styles/components/_index.scss

closes: https://meemoo.atlassian.net/browse/AVO-139

feat(draggable-list): re-hydrated draggableList, integrate collections

---

src/collection/collection.const.ts
src/collection/collection.gql.ts
src/collection/collection.helpers.tsx
src/collection/collection.service.ts
src/collection/components/fragment/FragmentEdit.tsx
src/collection/components/modals/AddToBundleModal.tsx
src/collection/helpers/fragment.ts
src/collection/helpers/index.ts
src/item/components/modals/AddToCollectionModal.tsx
src/shared/services/stills-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-336

fix(collection-edit): check fragment type based on type not id = -1

---

src/admin/content/components/ShareContentPageModal.tsx
src/admin/content/content.service.ts
src/admin/content/views/ContentDetail.tsx
src/admin/content/views/ContentEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-333
proxy twin: https://github.com/viaacode/avo2-proxy/pull/122

feat(content-page): allow content page publish + rework save/update

---

src/collection/components/modals/CutFragmentModal.tsx

Replaced mock data on video in cut fragment modal by real data.

fix(fragment-cut-modal): display data on video

---

src/admin/items/items.gql.ts
src/admin/items/items.service.ts
src/collection/components/CollectionOrBundleEdit.tsx

closes:
* https://meemoo.atlassian.net/browse/AVO-243
* https://meemoo.atlassian.net/browse/AVO-244
Translations for the placeholders look messed up because we extract them from the key, because the translation isn't added in the database yet

feat(collection-edit): add item/collection to collection/bundle by id

---

src/admin/items/views/ItemDetail.tsx

part of: https://meemoo.atlassian.net/browse/AVO-284

fix(admin-item): fix toasts, don't show model on publish, only on depub.

---

src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/components/ShareContentPageModal.tsx
src/admin/content/views/ContentDetail.tsx
src/shared/helpers/link.tsx

closes: https://meemoo.atlassian.net/browse/AVO-109

feat(content-page): add preview button, (de)publish_at options

---

src/authentication/helpers/permission-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-157

fix(collection-detail): correctly check permissions for edit button

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content-block/content-block.const.ts
src/admin/content-block/helpers/generators/image.ts
src/admin/shared/types/content-block.ts
src/content-page/views/ContentPage.tsx

closes: 
* https://meemoo.atlassian.net/browse/AVO-572
* https://meemoo.atlassian.net/browse/AVO-601
requires component PR: https://github.com/viaacode/avo2-components/pull/289
Test page: http://localhost:8080/beheer/content/220

feat(image-block): add full-width, page-header and align options

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/translations/views/TranslationsOverview.tsx

part of: https://meemoo.atlassian.net/browse/AVO-299
To show the bookmark counts we probably need some database changes
requires client PR: https://github.com/viaacode/avo2-components/pull/296

feat(admin-collections-overview): add number of views to coll overview

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/shared/components/FilterTable/FilterTable.tsx

closes:
* https://meemoo.atlassian.net/browse/AVO-290
* https://meemoo.atlassian.net/browse/AVO-301

feat(admin-collection-overview): add label filter

---

src/collection/collection.gql.ts
src/collection/collection.service.ts
src/collection/components/modals/ShareCollectionModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-466

feat(collection-edit): check duplicate title/description when publishing

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-270

fix(admin-collections-overview): combine first and lastname into author

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/shared/components/FilterTable/FilterTable.tsx
src/admin/shared/helpers/filters.ts
src/admin/users/user.gql.ts
src/admin/users/user.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-287

feat(admin-collections-overview): add filter by role checkbox dropdown

---

package-lock.json
package.json
src/admin/content-block/components/ContentBlockFieldEditor/ContentBlockFieldEditor.tsx
src/admin/content-block/content-block.const.ts
src/admin/content-block/helpers/generators/media-grid.ts
src/admin/content-block/helpers/generators/page-overview.ts
src/admin/interactive-tour/views/InteractiveTourEdit.tsx
src/search/components/SearchResultItem.tsx
src/workspace/views/Workspace.tsx

part of: https://meemoo.atlassian.net/browse/INFRA-27
requires component PR: https://github.com/viaacode/avo2-components/pull/297

fix(components): update story book + fix changes due to fixes in comp.

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx
src/admin/content-block/helpers/generators/media-grid.ts
src/admin/shared/types/content-block.ts

closes: https://meemoo.atlassian.net/browse/AVO-216
requires component PR: https://github.com/viaacode/avo2-components/pull/298

feat(media-grid): add cta colors to media grid tiles block config

---

src/shared/components/DraggableList/DraggableListModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-632

fix(draggable-list): ensure new item list is used when opening modal

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-652
component PR: https://github.com/viaacode/avo2-components/pull/300

fix(block-preview): sync header bg color with inner block header height

---

src/collection/components/CollectionOrBundleOverview.tsx
src/collection/views/CollectionDetail.tsx

closes:
* https://meemoo.atlassian.net/browse/AVO-471
* https://meemoo.atlassian.net/browse/AVO-585
* change unlock icon
* hide access column
* use icon for share button
requires components PR: https://github.com/viaacode/avo2-components/pull/301

feat(collection): change unlock icon, hide access column

---

src/item/components/ItemVideoDescription.tsx
src/item/components/modals/AddToCollectionModal.tsx
src/item/views/ItemDetail.tsx

closes:
* https://meemoo.atlassian.net/browse/AVO-605
* https://meemoo.atlassian.net/browse/AVO-606
requires component PR: https://github.com/viaacode/avo2-components/pull/304
Video should pause after these steps:
Video should also pause after these steps:

fix(flowplayer): pause video when modal opens/closes

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-299

feat(admin-collection-overview): add column bookmarks

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/items/views/ItemsOverview.tsx
src/admin/translations/views/TranslationsOverview.tsx
src/collection/collection.gql.ts
src/collection/collection.helpers.tsx
src/collection/components/CollectionOrBundleEdit.tsx

closes: 
* https://meemoo.atlassian.net/browse/AVO-291
* https://meemoo.atlassian.net/browse/AVO-302
also made tables a bit wider, so the column values don't wrap as much

Feature: add last edited by column to admin collection overview

---

package-lock.json
package.json
src/admin/Admin.tsx
src/admin/content/views/ContentEditContentBlocks.tsx
src/react-app-env.d.ts
src/shared/components/ResizablePanels/ResizablePanels.tsx
src/shared/components/ResizablePanels/components/Resizer.tsx
src/shared/components/index.ts

fixes issue with build non npm published package
https://meemoo.atlassian.net/browse/AVO-652

fix(resizable-panels): move fork to this repo

---

src/admin/items/views/ItemDetail.tsx
src/item/components/ItemVideoDescription.tsx
src/shared/components/InteractiveTour/InteractiveTour.tsx

closes: https://meemoo.atlassian.net/browse/AVO-607

fix(collection-fragment): change color to blue when clickable

---

src/workspace/workspace.gql.ts

closes: https://meemoo.atlassian.net/browse/AVO-634

fix(workspace): only count unarchived assignments

---

src/shared/components/InteractiveTour/InteractiveTour.tsx

closes: https://meemoo.atlassian.net/browse/AVO-668

fix(interactive-tour): disable jumpy animations for steps

---

src/admin/Admin.scss
src/admin/Admin.tsx

closes: https://meemoo.atlassian.net/browse/AVO-268

fix(admin-sidebar): make admin sidebar scrollable

---

src/bundle/views/BundleDetail.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-677
Change user in admin tab should also show up in real time after saving:

fix(collection-detail): update collection id after duplicating

---

src/home/views/Home.tsx

closes: https://meemoo.atlassian.net/browse/AVO-592

feat(home): go to search page when enter is pressed inside search field

---

src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-678

fix(collection-detail): remove onTitleClick handler to remove pointer

---

src/shared/components/DateRangeDropdown/DateRangeDropdown.tsx

closes: 
* https://meemoo.atlassian.net/browse/AVO-595
* https://meemoo.atlassian.net/browse/AVO-448
* https://meemoo.atlassian.net/browse/AVO-8

fix(date-range): ensure dates are parsed using belgian time

---

src/assignment/assignment.const.ts
src/assignment/assignment.service.ts
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentOverview.scss
src/assignment/views/AssignmentOverview.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/shared/services/data-service.ts
src/workspace/views/BookmarksOverview.tsx
src/workspace/views/Workspace.tsx

closes: https://meemoo.atlassian.net/browse/AVO-638
Also switch to other tab, when archiving/de-archiving the last assignment

feat(assignment-overview): show tabs even if no assignments are listed

---

src/bundle/views/BundleDetail.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-585
bundle edit private:
bundle edit public:
bundle detail private:
bundle detail public:
collection edit private:
collection edit public:

fix(bundle-detail): show correct share icon on bundle/coll edit/detail

---

src/assignment/assignment.const.ts
src/assignment/assignment.gql.ts
src/assignment/assignment.service.ts
src/assignment/assignment.types.ts
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentOverview.scss
src/assignment/views/AssignmentOverview.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/shared/services/data-service.ts
src/workspace/views/BookmarksOverview.tsx
src/workspace/views/Workspace.tsx

closes: https://meemoo.atlassian.net/browse/AVO-345
If too many labels are selected, the layout breaks. Will ask on task how meemoo would like us to solve this:

Show labels in assigment overview + allow filtering

---

src/assignment/assignment.const.ts
src/assignment/assignment.service.ts
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentOverview.scss
src/assignment/views/AssignmentOverview.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/shared/services/data-service.ts
src/workspace/views/BookmarksOverview.tsx
src/workspace/views/Workspace.tsx

closes: 
* https://meemoo.atlassian.net/browse/AVO-638
* https://meemoo.atlassian.net/browse/AVO-635

Show active/archived tabs when there are no assignments in table

---

src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/views/ContentEditContentBlocks.tsx
src/admin/interactive-tour/views/InteractiveTourEdit.tsx
src/admin/items/views/ItemDetail.tsx
src/admin/menu/components/MenuEditForm/MenuEditForm.tsx
src/admin/menu/views/MenuEdit.tsx
src/admin/permission-groups/views/PermissionGroupEdit.tsx
src/admin/user-groups/views/UserGroupEdit.tsx
src/authentication/views/registration-flow/r10-student-teacher.tsx
src/authentication/views/registration-flow/r3-stamboek.tsx
src/authentication/views/registration-flow/r4-manual-registration.tsx
src/collection/components/CollectionOrBundleEditAdmin.tsx
src/collection/components/modals/AddToBundleModal.tsx
src/item/components/modals/AddToCollectionModal.tsx
src/item/components/modals/ReportItemModal.tsx
src/settings/components/Profile.tsx
src/shared/components/InputModal/InputModal.tsx
src/shared/components/ResizablePanels/ResizablePanels.tsx
src/user-item-request-form/views/UserItemRequestForm.tsx

closes: https://meemoo.atlassian.net/browse/AVO-681
manuele account aanvraag zonder stamboeknummer:
fragment toevoegen aan collectie:
profile velden:

fix(forms): show asterisk next to required fields

---

src/item/views/ItemDetail.scss
src/item/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-669

fix(item-detail): use Header component so we get wrapping for free

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx
src/admin/content-block/helpers/generators/media-grid.ts
src/admin/shared/types/content-block.ts
src/shared/helpers/link.tsx

closes: 
* https://meemoo.atlassian.net/browse/AVO-609
* https://meemoo.atlassian.net/browse/AVO-215
Requires client PR: https://github.com/viaacode/avo2-components/pull/308
Requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/133
Het aantal opties is wel een beetje zot:

feat(media-tiles-block): add options + link to search query support

---

src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.gql.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.types.ts
src/workspace/views/BookmarksOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-327

feat(bookmarks): show views for each bookmarked item/collection/bundle

---

src/shared/components/FileUpload/FileUpload.tsx

part of: https://meemoo.atlassian.net/browse/AVO-709
Proxy PR: https://github.com/viaacode/avo2-proxy/pull/135

fix(upload-file): lowercase file extensions before lookup mime type

---

src/search/components/SearchFilterControls.tsx
src/search/components/SearchResultItem.tsx

closes: https://meemoo.atlassian.net/browse/AVO-203
test url:
http://localhost:8080/zoeken?filters=%7B%22type%22%3A%5B%22video%22%5D%2C%22educationLevel%22%3A%5B%22Secundair%20onderwijs%22%5D%2C%22subject%22%3A%5B%22beeldende%20kunsten%20-%20schilderkunst%2C%20beeldhouwkunst%2C%20bouwkunst%22%5D%2C%22keyword%22%3A%5B%22Belgi%C3%AB%22%5D%2C%22serie%22%3A%5B%22Schooltelevisie%3A%20Nederlands%22%5D%2C%22language%22%3A%5B%22nl%22%5D%2C%22broadcastDate%22%3A%7B%22gte%22%3A%221930-01-01%22%2C%22lte%22%3A%222020-12-31%22%7D%2C%22provider%22%3A%5B%22VRT%22%5D%2C%22query%22%3A%22test%22%7D

fix(search): show filters from url when no search results are found

---

src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx

part of: https://meemoo.atlassian.net/browse/AVO-672
steps to reproduce before this fix:
* edit an assignment
* click save
expected: saved successfully
current behavior: failed to save assignment

fix(assignment): remove rich text editor state from assign. before save

---

src/collection/views/CollectionDetail.tsx

eg: when the user presses the back button after duplicating the collection

fix(collection-detail): reload collection when id in the url changes

---

src/admin/content/views/ContentDetail.tsx
src/admin/content/views/ContentOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-105

fix(content-overview): switch detail page icon, show lock on detail page

---

src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-327

fix(bookmarks): use correct path to get count for collections/bundles

---

src/authentication/views/registration-flow/r4-manual-registration.tsx

part of: https://meemoo.atlassian.net/browse/AVO-35

fix(manual-registration): make all fields required

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

part of: https://meemoo.atlassian.net/browse/AVO-288

feat(admin-collection-overview): show column with number of times copied

---

src/collection/collection.gql.ts
src/collection/collection.helpers.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/modals/PublishCollectionModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-724

fix(collection-edit): check duplicates when saving and is_public is true

---

src/admin/content-block/components/BlockKlaar/BlockKlaar.tsx
src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content-block/components/fields/PaddingSelect/PaddingSelect.tsx
src/admin/content-block/content-block.const.ts
src/admin/content-block/helpers/generators/defaults.ts
src/admin/shared/types/content-block.ts

closes: https://meemoo.atlassian.net/browse/AVO-746
component PR: https://github.com/viaacode/avo2-components/pull/316

fix(image-block): add option to add margins to block

---

src/settings/components/Account.tsx

|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/81840753-b892c880-9549-11ea-8ce6-2eb821bbfeaa.png)|![image](https://user-images.githubusercontent.com/1710840/81840766-baf52280-9549-11ea-96e1-0b65f1d1a3cb.png)|

fix(account-settings): add margin between idp buttons

---

src/authentication/components/SecuredRoute.tsx
src/authentication/helpers/get-profile-info.ts
src/authentication/views/registration-flow/l8-accept-conditions.tsx
src/collection/collection.gql.ts
src/settings/components/Profile.tsx
src/shared/mocks/user-mock.ts

closes: https://meemoo.atlassian.net/browse/AVO-782
first you need to accept the conditions:
then you need to complete your profile:

fix(profile): force users to complete their profile after registration

---

src/authentication/authentication.service.ts
src/authentication/store/actions.ts
src/search/search.service.ts
src/settings/settings.service.ts
src/shared/helpers/fetch-with-logout.ts
src/shared/helpers/share-through-email.ts
src/shared/services/content-page-service.ts
src/shared/services/data-service.ts
src/shared/services/education-organizations-service.ts
src/shared/services/event-logging-service.ts
src/shared/services/file-upload-service.ts
src/shared/services/interactive-tour-service.ts
src/shared/services/navigation-items-service.ts
src/shared/services/player-ticket-service.ts
src/shared/services/related-items-service.ts
src/shared/services/stills-service.ts
src/shared/services/zendesk-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-761

fix(login): force login when 401 is received

---

src/bundle/views/BundleDetail.tsx
src/collection/components/CollectionOrBundleEditMetaData.tsx
src/shared/constants/wysiwyg2.ts
src/shared/helpers/sanitize/presets/basic.ts
src/shared/helpers/sanitize/presets/link.ts

closes: https://meemoo.atlassian.net/browse/AVO-792
edit screen:
bundle detail:

feat(bundle-edit): add wysiwyg editor for bundle description_long

---

src/authentication/helpers/redirects.ts
src/authentication/store/actions.tsx

closes: https://meemoo.atlassian.net/browse/AVO-477
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/142
typings PR: https://github.com/viaacode/avo2-typings/pull/72
5 - 10 minutes before session timeout the user gets a warning:
0 - 5 minutes before sesson timeout the user is redirect to the login page:

feat(auth): warn users 10 min before 5am that their session will timeout

---

src/authentication/helpers/get-profile-info.ts
src/settings/components/Profile.tsx
src/shared/components/Navigation/Navigation.tsx

feat(profile): upload profile picture

---

src/admin/content-block/helpers/field-attributes.ts

closes: https://meemoo.atlassian.net/browse/AVO-798

fix(AVO-798): map text area by value prop not values prop

---

src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx
src/admin/content-block/helpers/generators/media-player.ts
src/admin/shared/types/content-block.ts

Closes: AVO-794
Heb een ticketje bijgemaakt voor het probleem dat de eigen geuploade video niet de correct poster toont. Deze toont namelijk de flowplayer poster, ipv onze eigen styling van poster en play button. (AVO-808)

feat: add autoplay checkbox to media-player

---

src/admin/content-block/components/wrappers/MediaPlayerTitleTextButtonWrapper/MediaPlayerTitleTextButtonWrapper.tsx
src/admin/content-block/helpers/generators/media-player-title-text-button.ts
src/admin/shared/types/content-block.ts

Added video upload and autoplay to other media player block.

feat: add autoplay & video upload to media-player-title-text-button

---

src/admin/content-block/components/fields/PaddingSelect/PaddingSelect.scss
src/admin/content-block/components/fields/PaddingSelect/PaddingSelect.tsx

closes: https://meemoo.atlassian.net/browse/AVO-355

fix(padding-select): add more spacing between selects

---

src/collection/collection.gql.ts
src/collection/components/CollectionOrBundleOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-327

fix(collection-or-bundle-overview): show correct view counts

---

scripts/extract-and-replace-translations.ts

changed files were not being written to disk, but the nl.json file was correctly updated

fix(translations): fix extraction bug

---

src/admin/content/content.service.ts
src/admin/content/views/ContentOverview.tsx

I tried deleting Kopie 2: eqwqw

fix(content-page-overview): refetch content pages after deleting one

---

src/admin/content/content.service.ts
src/authentication/authentication.routes.tsx
src/authentication/components/SecuredRoute.tsx
src/authentication/views/registration-flow/l8-accept-conditions.tsx
src/collection/collection.service.ts
src/settings/components/Profile.tsx
src/shared/services/data-service.ts
src/shared/services/notification-service.ts

new accounts would get stuck on accept conditions because the user state would not be refreshed
part of: https://meemoo.atlassian.net/browse/AVO-782

Fix: Accept conditions + complete profile

---

src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx
src/styles/components/_content.scss

part of: https://meemoo.atlassian.net/browse/AVO-386
Also fixed the warning about: 
```
./src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx
Line 35:8:  The 'initFlowPlayer' function makes the dependencies of useEffect Hook (at line 71) change on every render. To fix this, wrap the 'initFlowPlayer' definition into its own useCallback() Hook  react-hooks/exhaustive-deps
```
before:
after:

Fix ul indentation for collection delete warning

---

src/collection/components/fragment/FragmentEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-872
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/83743913-ad6c1d80-a65b-11ea-9dff-1aeb319762f1.png)|![image](https://user-images.githubusercontent.com/1710840/83743947-b52bc200-a65b-11ea-9876-7cd5190c7f14.png)|
|![image](https://user-images.githubusercontent.com/1710840/83743925-b0670e00-a65b-11ea-9c91-f9e521d65d5a.png)|![image](https://user-images.githubusercontent.com/1710840/83743956-b78e1c00-a65b-11ea-8005-1158ef76cc89.png)|
|![image](https://user-images.githubusercontent.com/1710840/83743932-b2c96800-a65b-11ea-8ac7-c519ae94828a.png)|![image](https://user-images.githubusercontent.com/1710840/83743964-b9f07600-a65b-11ea-8c05-0b13a8b83553.png)|

fix(fragment-edit): change custom_description state interaction

---

src/item/components/ItemVideoDescription.tsx

closes: https://meemoo.atlassian.net/browse/AVO-871

fix(item-video-description): add c-content class to paragraph

---

src/dynamic-route-resolver/views/DynamicRouteResolver.tsx
src/shared/helpers/link.tsx

closes: https://meemoo.atlassian.net/browse/AVO-644

fix(dynamic-route-resolver): redirect klaar/archief to other search page

---

src/admin/content-block/helpers/parsers.ts
src/admin/content-block/services/content-block.service.ts
src/admin/content/content.service.ts
src/admin/content/views/ContentDetail.tsx
src/admin/content/views/ContentEdit.tsx

also fixed some issues with contentBlockConfig format vs database format and setting the correct content_id for the duplicated blocks

fix(content-detail): set new author when duplicating content block

---

src/collection/components/CollectionOrBundleEditContent.scss
src/collection/components/CollectionOrBundleEditContent.tsx

closes: https://meemoo.atlassian.net/browse/AVO-851

feat(collection-edit): hide heading style options in RTE

---

src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx
src/admin/content-block/helpers/generators/hero.ts
src/admin/content-block/helpers/generators/media-player-title-text-button.ts
src/admin/content-block/helpers/generators/media-player.ts
src/admin/content/views/ContentEdit.tsx
src/shared/components/FileUpload/FileUpload.scss
src/shared/components/FileUpload/FileUpload.tsx
src/shared/helpers/files.ts
src/user-item-request-form/views/UserItemRequestForm.tsx

closes: https://meemoo.atlassian.net/browse/AVO-849
component PR improves flowplayer preview without poster: https://github.com/viaacode/avo2-components/pull/338
also fix filename label for other files

feat(fileupload): show video preview in file upload component

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-841
component PR: https://github.com/viaacode/avo2-components/pull/339
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/83857019-ac4df580-a71a-11ea-9212-16b412702f8a.png)|![image](https://user-images.githubusercontent.com/1710840/83857031-aeb04f80-a71a-11ea-84fd-d5ca63d9f565.png)|

fix(page-overview-wrapper): sanitize html in description

---

src/assignment/assignment.gql.ts
src/assignment/assignment.service.ts
src/assignment/views/AssignmentDetail.tsx

part of: https://meemoo.atlassian.net/browse/AVO-774

fix(assignment-detail): hide complete check for teachers, fix for pupil

---

src/admin/users/user.const.ts
src/admin/users/user.service.ts
src/admin/users/user.types.ts
src/admin/users/views/UserOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-582

fix(user-overview): fix sort columns

---

src/admin/admin.const.ts
src/admin/content/content.service.ts
src/admin/content/hooks/useContentPage.ts
src/admin/content/views/ContentDetail.tsx
src/admin/shared/components/Sidebar/Sidebar.tsx

closes: https://meemoo.atlassian.net/browse/AVO-763
back button to edit page that was deleted
Detail page when deleted

fix(content-page): improve error handling for deleted pages

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/content.const.tsx
src/admin/content/content.types.ts
src/admin/content/views/ContentEdit.tsx
src/admin/content/views/ContentEditContentBlocks.tsx
src/content-page/views/ContentPage.tsx

closes: https://meemoo.atlassian.net/browse/AVO-661
components PR: https://github.com/viaacode/avo2-components/pull/334

Feature: Allow deep linking to page overview accordion

---

src/authentication/helpers/get-profile-info.ts
src/settings/components/Profile.tsx
src/settings/settings.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-721

feat(profile): add checkbox to subscribe to newsletter after first login

---

src/authentication/helpers/redirects.ts

closes: https://meemoo.atlassian.net/browse/AVO-235
http://localhost:8080/zoeken?filters=%7B%22educationLevel%22%3A%5B%22Lager%20onderwijs%22%5D%2C%22subject%22%3A%5B%22sociale%20vaardigheden%22%5D%2C%22keyword%22%3A%5B%22relatie%22%5D%7D
http://localhost:8080/beheer/content?content_type=FAQ_ITEM&page=0

fix(login): redirect to path + query params after login

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/collection/collection.service.ts
src/collection/collection.types.ts
src/shared/services/relation-service/relation.gql.ts
src/shared/services/relation-service/relation.service.ts
src/shared/services/relation-service/relation.types.ts

closes: https://meemoo.atlassian.net/browse/AVO-288
Implemented but the database view does not return the correct counts, but instead returns 0.
See comment on: https://meemoo.atlassian.net/browse/DEV-889

feat(collections-overview): show in_bundle & in_assignment count columns

---

src/admin/content-block/helpers/generators/anchor-links.ts
src/admin/content-block/helpers/generators/buttons.ts
src/admin/content-block/helpers/generators/ctas.ts
src/admin/content-block/helpers/generators/defaults.ts
src/admin/content-block/helpers/generators/heading.ts
src/admin/content-block/helpers/generators/iframe.ts
src/admin/content-block/helpers/generators/image-grid.ts
src/admin/content-block/helpers/generators/image.ts
src/admin/content-block/helpers/generators/intro.ts
src/admin/content-block/helpers/generators/klaar.ts
src/admin/content-block/helpers/generators/media-grid.ts
src/admin/content-block/helpers/generators/media-player-title-text-button.ts
src/admin/content-block/helpers/generators/media-player.ts
src/admin/content-block/helpers/generators/page-overview.ts
src/admin/content-block/helpers/generators/project-spotlight.ts
src/admin/content-block/helpers/generators/quote.ts
src/admin/content-block/helpers/generators/rich-text-two-columns.ts
src/admin/content-block/helpers/generators/rich-text.ts
src/admin/content-block/helpers/generators/spotlight.ts

closes: https://meemoo.atlassian.net/browse/AVO-315
components PR: https://github.com/viaacode/avo2-components/pull/332
Cannot remove some padding in components, since that padding is used to add spece between repeatable blocks

feat(content-blocks): set default padding for blocks

---

src/admin/content-block/helpers/generators/heading.ts

closes: https://meemoo.atlassian.net/browse/AVO-815

feat(heading-block): expose title color option

---

src/admin/content-block/services/content-block.service.ts
src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/content.const.tsx
src/admin/content/content.gql.ts
src/admin/content/content.types.ts
src/admin/content/hooks/useContentPage.ts
src/admin/content/views/ContentDetail.tsx
src/admin/content/views/ContentDetailMetaData.tsx
src/admin/content/views/ContentEdit.tsx
src/admin/shared/helpers/render-detail-fields.tsx
src/dynamic-route-resolver/views/DynamicRouteResolver.tsx

closes: https://meemoo.atlassian.net/browse/AVO-805
also rendered html for description on detail page

feat(content-page): add seo description prop

---

src/admin/shared/helpers/content-picker/internal-link.ts
src/authentication/components/PupilOrTeacherDropdown.tsx
src/authentication/views/RegisterOrLogin.tsx
src/authentication/views/registration-flow/r4-manual-registration.tsx
src/constants.ts
src/shared/components/InteractiveTour/InteractiveTour.tsx
src/shared/constants/routes.ts

closes: https://meemoo.atlassian.net/browse/AVO-858

feat(route): replace /voor-leerlingen static page by /leerlingen cb page

---

src/admin/content/views/ContentEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-859

fix(content-edit): set block position to be at bottom of page on paste

---

src/admin/content-block/components/wrappers/MediaPlayerTitleTextButtonWrapper/MediaPlayerTitleTextButtonWrapper.tsx
src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx
src/admin/content-block/components/wrappers/index.ts
src/admin/content-block/helpers/generators/media-player.ts
src/assignment/views/AssignmentDetail.tsx
src/collection/components/fragment/FragmentDetail.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/collection/components/fragment/FragmentList.tsx
src/collection/components/modals/CutFragmentModal.scss
src/collection/components/modals/CutFragmentModal.tsx
src/collection/views/CollectionDetail.tsx
src/item/components/ItemVideoDescription.tsx
src/item/components/modals/AddToCollectionModal.scss
src/item/components/modals/AddToCollectionModal.tsx
src/item/views/ItemDetail.tsx
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.gql.ts

closes: 
* https://meemoo.atlassian.net/browse/AVO-250
* https://meemoo.atlassian.net/browse/AVO-194
Requires component PR: https://github.com/viaacode/avo2-components/pull/327
Also made alt tekst for media player block optional since it defaults to the title of the selected video. You only need to enter alt tekst for custom videos

Unify all flowplayers

---

src/constants.ts
src/shared/components/FileUpload/FileUpload.tsx
src/user-item-request-form/user-item-request-form.routes.tsx
src/user-item-request-form/views/UserItemRequestForm.tsx
src/user-item-request-form/views/UserItemRequestFormConfirm.tsx

closes: https://meemoo.atlassian.net/browse/AVO-816

feat(user-item-request-form): layout fixes + confirm on separate page

---

src/item/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-791

feat(item-detail): scroll up to top when clicking related item

---

src/admin/admin.const.ts
src/admin/admin.routes.tsx
src/admin/content-page-labels/content-page-label.const.ts
src/admin/content-page-labels/content-page-label.gql.ts
src/admin/content-page-labels/content-page-label.routes.tsx
src/admin/content-page-labels/content-page-label.service.ts
src/admin/content-page-labels/content-page-label.types.ts
src/admin/content-page-labels/views/ContentPageLabelDetail.tsx
src/admin/content-page-labels/views/ContentPageLabelEdit.tsx
src/admin/content-page-labels/views/ContentPageLabelOverview.scss
src/admin/content-page-labels/views/ContentPageLabelOverview.tsx
src/admin/content-page-labels/views/index.ts
src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/views/ContentOverview.tsx
src/shared/constants/routes.ts

closes: https://meemoo.atlassian.net/browse/AVO-234

feat(content-page-labels): create screens for content label management

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-804
requires components PR: https://github.com/viaacode/avo2-components/pull/326
related typings PR: https://github.com/viaacode/avo2-typings/pull/75

feat(page-overview-wrapper): chnage how all label works, hide other cat.

---

src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/items/views/ItemDetail.tsx
src/assignment/assignment.const.ts
src/assignment/assignment.gql.ts
src/assignment/assignment.service.ts
src/assignment/assignment.types.ts
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentOverview.tsx
src/collection/collection.gql.ts
src/collection/components/CollectionOrBundleEditAdmin.tsx
src/styles/components/_toolbar.scss
src/workspace/views/Workspace.tsx

closes: https://meemoo.atlassian.net/browse/AVO-774
requires components PR: https://github.com/viaacode/avo2-components/pull/333
mobile view for pupil:
mobile view for teacher:

Feature: Pupil workspace

---

src/dynamic-route-resolver/views/DynamicRouteResolver.tsx

closes: https://meemoo.atlassian.net/browse/AVO-764
url: http://localhost:8080/pid/qj77s9rc57 
now redirects to: http://localhost:8080/item/qj77s9rc57

fix(dynamic-route-resolver): rewrite /pid/<pid> to /item/<pid>

---

src/item/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-790

fix(item-detail): reduce header spacing

---

src/admin/content/content.service.ts

part of: https://meemoo.atlassian.net/browse/AVO-367

fix(content-service): always sanitize rich text content

---

src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/content.service.ts
src/admin/content/hooks/useContentTypes.ts

closes: https://meemoo.atlassian.net/browse/AVO-73
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/84031101-66509600-a995-11ea-8c73-80554ad7b3fb.png)|![image](https://user-images.githubusercontent.com/1710840/84031108-694b8680-a995-11ea-9043-1453365ff1f9.png)|

feat(content-edit-form): show enum descriptions instead of labels

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/views/ContentEdit.tsx

an enless render loop would occur when you connect to the QAS backend with your local frontend en add a page overview block

fix(page-overview): fix render loop + fix default page path

---

src/admin/content-block/helpers/generators/quote.ts

closes: https://meemoo.atlassian.net/browse/AVO-811

fix(quote): set correct type for quote block

---

src/item/components/ItemVideoDescription.scss
src/item/components/ItemVideoDescription.tsx
src/shared/helpers/sanitize/presets/index.ts
src/styles/components/_content.scss

closes: https://meemoo.atlassian.net/browse/AVO-885
example collection to test with: http://localhost:8080/collecties/053a27d2-d030-4502-8be7-c5b44e4cec00
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/84285935-57591780-ab3e-11ea-865f-1a49af2ea767.png)|![image](https://user-images.githubusercontent.com/1710840/84285941-5922db00-ab3e-11ea-8b2b-f5433a7a9605.png)|

AVO-885 onderzoeken waarom media items soms lege paragraphs bevat

---

src/assignment/assignment.gql.ts
src/assignment/views/AssignmentOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-774
before:
after:

AVO-774 Werkruimte LEERLINGEN

---

src/collection/components/fragment/FragmentEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-847

fix(fragment-edit): reset RTE state when toggling use_custom_fields

---

package-lock.json
src/item/views/ItemDetail.scss

closes: https://meemoo.atlassian.net/browse/AVO-790

Fix: make item detail header same height as collection header

---

src/admin/content-block/helpers/generators/hero.ts
src/admin/content/content.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-927
requires component PR: https://github.com/viaacode/avo2-components/pull/349

AVO-927 CB 'hero / header startpagina': kan deel tekst onder knoppen niet toevoegen noch link leggen

---

src/admin/content-block/helpers/generators/media-player-title-text-button.ts

Partially closes https://meemoo.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=AVO&modal=detail&selectedIssue=AVO-887

fix(media-player-title-text-button): optional alt

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/admin/content-block/content-block.const.ts
src/admin/content-block/helpers/generators/page-overview.ts

closes: https://meemoo.atlassian.net/browse/AVO-832
requires component PR: https://github.com/viaacode/avo2-components/pull/348

AVO-832 Content block 'overzicht': formaat afbeelding item type 'lijst' > 2 aangepaste formaten voorzien

---

src/dynamic-route-resolver/views/DynamicRouteResolver.tsx
src/home/views/Home.tsx

closes: https://meemoo.atlassian.net/browse/AVO-463
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/148

AVO-463 SS account als leerling - landen op Mijn werkruimte 

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content-block/components/wrappers/BlockContentPageMeta/BlockContentPageMeta.tsx

closes: https://meemoo.atlassian.net/browse/AVO-834

AVO-834 Een pagina van type 'NIEUWS_ITEM' moet 'context' hebben: datum, labels en auteur

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content-block/helpers/generators/hero.ts
src/admin/content-block/helpers/generators/search.ts

https://meemoo.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=AVO&modal=detail&selectedIssue=AVO-888

feat(cb): default padding for hero and search

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.const.ts
src/admin/content-block/components/wrappers/HeroWrapper/HeroWrapper.tsx
src/admin/content-block/components/wrappers/index.ts
src/admin/content-block/helpers/generators/hero.ts

closes: https://meemoo.atlassian.net/browse/AVO-902

fix(hero-wrapper): add wrapper around hero to set flowplayer token & id

---

src/shared/components/FileUpload/FileUpload.tsx

closes: https://meemoo.atlassian.net/browse/AVO-886

AVO-886 Formulier gebruikersaanvraag: wanneer je een document hebt opgeladen, wordt de naam van het document niet getoond

---

src/authentication/helpers/redirects.ts

closes: https://meemoo.atlassian.net/browse/AVO-899

AVO-899 Foutmelding bij inloggen als LEERLING via Smartschool

---

src/admin/content/content.service.ts

Project in de kijker: projecten werden niet ingeladen

fix(project-spotlight): retrieve items correctly

---

src/authentication/views/registration-flow/r4-manual-registration.tsx
src/shared/services/education-levels-service.ts

Closes: https://meemoo.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=AVO&modal=detail&selectedIssue=AVO-837
Proxy twin: https://github.com/viaacode/avo2-proxy/pull/153

feat(manual-request): add education level input

---

src/admin/users/user.gql.ts
src/admin/users/views/UserDetail.tsx

part of: https://meemoo.atlassian.net/browse/AVO-731

AVO-731 Sync AVO2 - ACM: basics voor gebruikersbeheer

---

src/admin/content/views/ContentDetailMetaData.tsx
src/admin/content/views/ContentOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-73

AVO-73 Naamgeving Content type beschikbaar maken in vertalingsbeheer

---

src/assignment/views/AssignmentOverview.scss

Closes: https://meemoo.atlassian.net/browse/AVO-889

fix(workspace): more specific css for mobile

---

src/admin/content/views/ContentOverview.tsx

Potentially closes: https://meemoo.atlassian.net/browse/AVO-105

fix(content-overview): display publish indicator

---

package-lock.json
package.json
src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-819

AVO-819 Content Block 'Media tegels': plaatsing knop CTA-tegel dynamisch maken + tekst onder image

---

package-lock.json
package.json
src/settings/components/Profile.tsx
src/settings/settings.service.ts
src/shared/queries/lookup.gql.ts

closes: AVO-922
Je kan dit testen door in te loggen met de lesgever account
opleidingsniveau secundair te kiezen
en dan moet je toegang hebben tot opdrachten

AVO-922 Velden per gebruikersrol bij aanmelden en op profiel

---

src/collection/components/modals/CutFragmentModal.tsx
src/item/components/modals/AddToCollectionModal.tsx
src/shared/services/video-stills-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-999
proxy PR: https://github.com/viaacode/avo2-proxy/pull/162

AVO-999 Modal om hoofdafbeelding te kiezen bij een collectie toont maar één still of geen enkele

---

src/settings/views/Settings.tsx

fix(profile): wrap translations in getter func

---

src/admin/permission-groups/views/PermissionGroupEdit.tsx

refetch permission group after save

AVO-1034 permissiegroepen op beta: educatieve uitgever en lesgever overige geven errors bij bewaren.

---

src/settings/components/Profile.tsx

closes: https://meemoo.atlassian.net/browse/AVO-982

AVO-982 Aanvullen profiel bij registratie: extra tekstje of tooltip bij veld onderwijsinstelling 'vind je je school niet, contacteer ....'

---

src/collection/collection.helpers.tsx
src/collection/collection.service.ts
src/collection/components/modals/PublishCollectionModal.tsx

refactor related to: https://meemoo.atlassian.net/browse/AVO-1009
replaced the useMutation trigger with a function in the collection service

refactor(publish-collection-modal): update publish state through service

---

src/settings/components/Profile.tsx

part of: https://meemoo.atlassian.net/browse/AVO-939

AVO-939 Update fields in campaign monitor when profile changes

---

src/assignment/assignment.const.ts
src/assignment/assignment.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1030

fix(assignment-service): load collection item meta data

---

src/collection/components/CollectionOrBundleEditMetaData.tsx
src/shared/constants/wysiwyg.ts

closes: https://meemoo.atlassian.net/browse/AVO-1047

AVO-1047 RTE bundels: hyperlinks ontbreken

---

src/shared/components/FileUpload/FileUpload.tsx

part of: https://meemoo.atlassian.net/browse/AVO-870
so we can show files without the user being able to change the uploaded file

AVO-870 Add disabled option to fileUpload component

---

src/admin/content-block/components/wrappers/MediaGridWrapper/BlockMediaList/BlockMediaList.scss
src/admin/content-block/components/wrappers/MediaGridWrapper/BlockMediaList/BlockMediaList.tsx
src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx
src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.types.ts
src/admin/content-block/components/wrappers/MediaPlayerTitleTextButtonWrapper/MediaPlayerTitleTextButtonWrapper.tsx
src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx
src/admin/content-block/helpers/generators/media-grid.ts
src/admin/shared/types/content-block.ts
src/assignment/views/AssignmentDetail.tsx
src/collection/components/fragment/FragmentDetail.tsx
src/item/components/ItemVideoDescription.tsx
src/item/components/modals/AddToCollectionModal.tsx
src/item/views/ItemDetail.tsx
src/shared/services/content-page-service.ts

partly closes: https://meemoo.atlassian.net/browse/AVO-969
proxy PR: https://github.com/viaacode/avo2-proxy/pull/163
component PR: https://github.com/viaacode/avo2-components/pull/356
Playing videos (in a modal) isn't possible yet from a media grid
http://localhost:8080/klaar/archief
http://localhost:8080/projecten/klaar

AVO-969 KLAAR pagina en archief: zichtbaarheid filmpjes uit MAM niet in orde wanneer niet aangemeld

---

src/assignment/assignment.helper.tsx
src/assignment/assignment.service.ts
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/settings/components/Profile.tsx

related to: https://meemoo.atlassian.net/browse/AVO-1030
steps:
* go to collection detail page
* click create assignment button
expected: you see create assignment page with collection as the content of the assignment
current: you see blank page with spinner and toast error saying the fetch of the assignment content failed

fix(assignment-create): fetch assignment content using the service

---

src/collection/views/CollectionDetail.tsx
src/item/views/ItemDetail.tsx
src/settings/components/Profile.tsx

closes: 
* https://meemoo.atlassian.net/browse/AVO-917
* https://meemoo.atlassian.net/browse/AVO-881 (duplicate)
lesgever secundair heeft de knoppen:
student lesgever kleuter heeft die permissie niet:

fix(item/coll-detail): show create assignment button only if perm.

---

src/admin/items/items.service.ts
src/assignment/assignment.helper.tsx
src/assignment/assignment.service.ts
src/shared/helpers/default-still.ts

- Default audio still in beheer.
- Helper functie voor applying van deze default audio still.
OUD EN FOUT : https://onderwijs-qas.hetarchief.be/beheer/items/c831f161-f785-4831-9a22-a98bf4b9af3e
NIEUW EN... : http://localhost:8080/beheer/items/c831f161-f785-4831-9a22-a98bf4b9af3e

feat(audio-still): centralize logic in helper

---

src/settings/components/Account.tsx
src/settings/components/Email.tsx
src/settings/components/Profile.tsx

Closes: https://meemoo.atlassian.net/browse/AVO-906

feat(settings): layout

---

src/shared/helpers/sanitize/presets/index.ts

closes: https://meemoo.atlassian.net/browse/AVO-928

fix(sanitize): do not remove class and style from header tags

---

src/styles/components/_content.scss

closes: https://meemoo.atlassian.net/browse/AVO-1002

fix(styles): fix mono indentation for ul ul li en ol ol li

---

src/authentication/views/registration-flow/r3-stamboek.tsx

closes: https://meemoo.atlassian.net/browse/AVO-383

fix(stamboek): add link to "why do you need my stamboek number"

---

src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/content/content.gql.ts
src/admin/users/user.gql.ts
src/admin/users/views/UserDetail.tsx
src/assignment/assignment.gql.ts
src/authentication/helpers/get-profile-info.ts
src/bundle/views/BundleDetail.tsx
src/collection/collection.gql.ts
src/shared/helpers/formatters/avatar.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1026
also relates to: https://meemoo.atlassian.net/browse/AVO-870
show company logo and name if available
collectie:
bundel:
opdracht (een leerkracht zal normaal nooit een company account zijn)
beheer:
header:

feat(avatar): show company logo/name if defined

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-968
proxy PR: https://github.com/viaacode/avo2-proxy/pull/170
page overview blocks can be used on an unauthenticated page, so we cannot use the data route to fetch pages
example page to load when you're logged out: http://localhost:8080/projecten

fix(page-overview-wrapper): move fetch logic for page overview to proxy

---

src/authentication/components/StamboekInput.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1055

fix(stamboek): validate again after valid stamboek was entered

---

src/assignment/assignment.helper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1068

fix(assignments): add screencast alert content html to the translations

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx
src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx
src/item/components/ItemVideoDescription.tsx
src/item/views/ItemDetail.tsx
src/workspace/views/BookmarksOverview.tsx

closes:
* https://meemoo.atlassian.net/browse/AVO-612
* https://meemoo.atlassian.net/browse/AVO-217
bundel detail
http://localhost:8080/beheer/content/154

fix(bundle-detail): add icon, views and bookmark counts to bundle header

---

src/settings/components/Profile.scss
src/settings/components/Profile.tsx

closes: https://meemoo.atlassian.net/browse/AVO-870
proxy PR: https://github.com/viaacode/avo2-proxy/pull/172
if company is defined:
if no company is defined:

feat(profile): show company logo on profile page if company is defined

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/admin/users/user.gql.ts
src/admin/users/views/UserDetail.tsx

part of: https://meemoo.atlassian.net/browse/AVO-926

feat(user-detail): add is_exception and oormerk + fix some dep arrays

---

src/authentication/components/LoginOptionsDropdown.tsx
src/authentication/components/PupilOrTeacherDropdown.tsx
src/shared/components/Footer/Footer.tsx
src/shared/components/Navigation/Navigation.tsx
src/shared/helpers/navigation.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1065
steps to test:
delete the "has accepted conditions" from the database for the test leerling user (profile id: 76cb7d69-b571-4d59-a89e-744f71eaba63) (already did this for your convenience :D )
go to the http://localhost:8080/leerlingen page
login using smartschool test_leerling (see 1p)
you should see:
after accepting you should see:

fix(navigation): fix mismatch between router - and nav item location

---

package-lock.json
package.json
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentOverview.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/views/CollectionDetail.tsx
src/shared/helpers/formatters/avatar.tsx

closes: https://meemoo.atlassian.net/browse/AVO-615

fix(avatar): never show user role. show name + company if available

---

src/settings/components/Account.tsx

fix(account): add first and lastname on account page

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx

part of: https://meemoo.atlassian.net/browse/AVO-968

fix(content-page-overview): deep compare for selected labels array

---

package-lock.json
package.json
src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1077
requires components PR: https://github.com/viaacode/avo2-components/pull/359

fix(media-grid-wrapper): split media tile item link from button link

---

src/shared/components/InteractiveTour/InteractiveTour.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1114
http://localhost:8080/collecties/d41c9764-8dd2-4e5c-b72a-4509545c3b3b
rondleiding
als je bewerk rechten hebt:
als je geen bewerk rechten hebt:

fix(interactive-tour): remove steps for which the target cannot be found

---

src/admin/content/helpers/get-published-state.ts
src/admin/items/views/ItemsOverview.tsx
src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx
src/dynamic-route-resolver/views/DynamicRouteResolver.tsx
src/shared/components/JsonLd/JsonLd.tsx
src/shared/helpers/formatters/date.ts

closes: https://meemoo.atlassian.net/browse/AVO-670
collection:
bundle:
public content page:

feat: Add json ld structured data for search engines

---

package-lock.json
package.json
src/bundle/views/BundleDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1026
before:
after:

fix(bundle-detail): show bundle author not logged in user

---

package-lock.json
package.json
src/authentication/views/RegisterOrLogin.tsx
src/bundle/views/BundleDetail.tsx
src/dynamic-route-resolver/views/DynamicRouteResolver.tsx

related to: https://meemoo.atlassian.net/browse/AVO-670

fix(login): update comps and redirect after login popup to correct page

---

public/index.html
scripts/env.js
scripts/env.sh

closes: https://meemoo.atlassian.net/browse/AVO-1153
the analytics tag when no js is enabled doesn't get their tag from the env variables, but this isn't an issue since the tag is set to production, and we are not going to test on qas without javascript enabled, since then the website won't load at all

feat(google-analytics): add google analytics tag in index.html

---

src/assignment/assignment.service.ts
src/bundle/views/BundleDetail.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/views/CollectionDetail.tsx

twin proxy PR: https://github.com/viaacode/avo2-proxy/pull/185
before:
after:

fix(assignment-detail): allow fetch non public coll. if linked to assig.

---

src/search/search.types.ts
src/search/views/Search.tsx

Closes: https://meemoo.atlassian.net/browse/AVO-1005

fix(search): reset filters, url and search term

---

src/bundle/views/BundleDetail.tsx

fix(bundle-detail): remove duplicate header from faulty merge

---

src/bundle/views/BundleDetail.tsx

Closes: https://meemoo.atlassian.net/browse/AVO-329
Proxy twin: https://github.com/viaacode/avo2-proxy/pull/186

feat(bundle-detail): display thumbnail meta

---

src/admin/content-block/content-block.const.ts

closes: https://meemoo.atlassian.net/browse/AVO-905

fix(content-block-consts): mark 3 more colors as dark

---

src/constants.ts

closes: https://meemoo.atlassian.net/browse/AVO-973

fix(constants): hide /, /start and /instellingen from content picker

---

src/authentication/helpers/redirects.ts

closes: https://meemoo.atlassian.net/browse/AVO-1187

fix(redirects): get full base url when we are on the / route

---

src/authentication/views/registration-flow/r10-student-teacher.tsx
src/authentication/views/registration-flow/r4-manual-registration.tsx

closes: https://meemoo.atlassian.net/browse/AVO-987

fix(student-teacher): replace back navigation with history goBack

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.const.ts
src/admin/content-block/components/wrappers/MediaPlayerTitleTextButtonWrapper/MediaPlayerTitleTextButtonWrapper.tsx
src/admin/content-block/components/wrappers/RichTextWrapper/RichTextWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-868

feat(text-block): add max text with to text blocks

---

src/authentication/helpers/redirects.ts
src/dynamic-route-resolver/views/DynamicRouteResolver.tsx
src/error/views/ErrorView.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1025
je kan dit testen door een exceptie te smijten in de check-login route in de proxy

fix(error): reload app when going back to home after error view

---

src/admin/users/user.gql.ts
src/admin/users/user.service.ts
src/admin/users/views/UserDetail.tsx
src/settings/components/Profile.tsx
src/shared/services/data-service.ts
src/shared/services/education-organizations-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1177
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/188

feat(user-detail): toggle block user, show more user fields

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.const.ts
src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/admin/content-block/content-block.const.ts

closes: https://meemoo.atlassian.net/browse/AVO-900
requires a component PR: https://github.com/viaacode/avo2-components/pull/363
also fixed issue where tabs disappear when you select a tab that doesn't have any items under it. 
* Example page: http://localhost:8080/beheer/content/380
* tab: Leerlingen

fix(page-overview): add dark mode for tabs + fix header height

---

src/authentication/helpers/get-profile-info.ts

part of: https://meemoo.atlassian.net/browse/AVO-1084

fix(get-profile-info): get user group from user if available

---

src/App.tsx
src/shared/components/ZendeskWrapper/ZendeskWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-979
desktop scrolling page top
desktop scrolling page bottom
desktop non scrolling page
mobile:
mobile bottom:

fix(zendesk-widget): move Zendesk widget so no overlap with footer

---

src/authentication/views/registration-flow/r4-manual-registration.tsx
src/item/components/modals/ReportItemModal.tsx
src/shared/services/zendesk-service.ts
src/user-item-request-form/views/UserItemRequestForm.tsx

closes: https://meemoo.atlassian.net/browse/AVO-305
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/203
Fixed for:
* manual account request
* media item request
* flag media item

fix(zendesk): send ticket with requester name and email

---

package-lock.json
package.json
src/admin/items/items.gql.ts
src/admin/shared/components/FilterTable/FilterTable.tsx
src/admin/shared/helpers/query-string-converters.ts

closes: https://meemoo.atlassian.net/browse/AVO-1199

feat(filter-table): add result count + update use-query-params package

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/error/views/ErrorView.tsx
src/settings/components/Account.tsx

closes: https://meemoo.atlassian.net/browse/DEV-889

feat(collections-overview): add count columns

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1192
before:
after:

fix(collections-overview): correctly show author last edit

---

src/admin/items/items.const.ts
src/admin/items/items.types.ts
src/admin/items/views/ItemsOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-276

feat(items-overview-admin): remove column and filter: created_at

---

src/admin/items/items.const.ts
src/admin/items/items.gql.ts
src/admin/items/items.service.ts
src/admin/items/views/ItemsOverview.tsx
src/shared/services/organizations-service.gql.ts

closes: https://meemoo.atlassian.net/browse/AVO-277

feat(items-overview-admin): add series and CP filter

---

src/admin/items/items.gql.ts
src/admin/items/items.service.ts
src/admin/shared/components/ContentPicker/ContentPicker.const.ts
src/admin/shared/components/ContentPicker/ContentPicker.tsx
src/admin/shared/components/ContentPicker/helpers/parse-picker.ts
src/admin/shared/components/ContentPicker/item-providers/collection.ts
src/admin/shared/components/ContentPicker/item-providers/content-page.ts
src/admin/shared/components/ContentPicker/item-providers/internal-link.ts
src/admin/shared/components/ContentPicker/item-providers/item.ts
src/admin/shared/components/ContentPicker/item-providers/profile.ts
src/admin/shared/helpers/index.ts
src/collection/collection.gql.ts
src/collection/collection.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-801
fixed for items, collections, bundles
private collection:
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/87689798-ef26d280-c788-11ea-95f4-8f6abb98ef9b.png)|![image](https://user-images.githubusercontent.com/1710840/87689818-f51cb380-c788-11ea-9c6f-1ebc20c26ad3.png)|
private item:
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/87689862-0239a280-c789-11ea-95e5-0615b9de764a.png)![image](https://user-images.githubusercontent.com/1710840/87689875-049bfc80-c789-11ea-81cb-0b9805eb19c3.png)|![image](https://user-images.githubusercontent.com/1710840/87689885-08c81a00-c789-11ea-993c-84055d2746bc.png)![image](https://user-images.githubusercontent.com/1710840/87689902 …

feat(content-picker): only show public content in content picker

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1191
until this task is complete:
https://meemoo.atlassian.net/browse/DEV-1070
example url that used to fail: http://localhost:8080/beheer/collecties?page=0&query=curves&sort_column=in_assignment&sort_order=desc

fix(collection-overview-admin): disable user group filtering & searching

---

src/collection/views/CollectionDetail.tsx

Resolves https://meemoo.atlassian.net/browse/AVO-1230.
Proxy twin: https://github.com/viaacode/avo2-proxy/pull/205

Related collections: more like this query niet uitvoeren bij private collecties.

---

src/shared/components/LoadingErrorLoadedComponent/LoadingErrorLoadedComponent.tsx
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.types.ts
src/workspace/views/BookmarksOverview.tsx

Resolves https://meemoo.atlassian.net/browse/AVO-1202.

fix(bookmarks): issued data catch

---

src/admin/items/items.gql.ts

Resolves: https://meemoo.atlassian.net/browse/AVO-280

fix(items-overview): pagination

---

package-lock.json
package.json
src/admin/content/content.gql.ts
src/admin/content/views/ContentDetail.tsx
src/admin/content/views/ContentEdit.tsx
src/admin/content/views/ContentOverview.tsx

Resolves https://meemoo.atlassian.net/browse/AVO-1108.

AVOO-1108 - Beheer: content pages - check edit permission & hide functionalities accordingly

---

src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/content/content.gql.ts
src/assignment/assignment.gql.ts
src/collection/collection.gql.ts

closes: https://meemoo.atlassian.net/browse/AVO-1132

fix(workspace): fetch owner profile id so we can check owner easily

---

src/search/components/SearchResultItem.tsx

part of: https://meemoo.atlassian.net/browse/AVO-1107

fix(search-result-item): add duration meta data for video and audio items

---

src/bundle/views/BundleDetail.tsx
src/collection/components/CollectionOrBundleEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1036

fix(collection-or-bundle-edit): add view and bookmark counts to header

---

src/bundle/views/BundleDetail.tsx
src/shared/helpers/formatters/date.ts

closes: https://meemoo.atlassian.net/browse/AVO-1032

fix(bundle-detail): show date instead of fromNow

---

src/collection/components/CollectionOrBundleEditContent.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1045
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/89296662-eed07780-d662-11ea-857a-14e1ab95e4ea.png)|![image](https://user-images.githubusercontent.com/1710840/89296669-f132d180-d662-11ea-8766-fa55e23ec5b5.png)|

fix(collection-or-bundle-edit): include fragment position in react key

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1033
related proxy PR: https://github.com/viaacode/avo2-proxy/pull/210
Fixes 3.5 out of 5 issues of the jira task:
1. ⛔ Het aantal items wordt niet getoond bij collecties
2. ⛔ Het aantal collecties wordt niet getoond bij bundels.
2.5. ✅ De copy is hier ook fout (er moet staan: x collecties 
3. ✅ Wanneer je doorklikt op een collectie of bundel, word je niet doorverwezen naar de collectie of bundel maar naar https://onderwijs-qas.hetarchief.be/bundels/
4. ✅ Bij bundels wordt het collectie-icoon getoond ipv het map-icoon
5. ✅ Bij bundels kleurt de link naar de collectiekleur ipv naar de map-kleur

fix(media-grid-wrapper): fix meta data and link for coll and bundles

---

src/collection/components/CollectionOrBundleEditAdmin.tsx

closes: 
* https://meemoo.atlassian.net/browse/AVO-760
* https://meemoo.atlassian.net/browse/AVO-758

feat(coll-bundle-edit-admin): show last edited by and last edit date

---

src/authentication/views/registration-flow/r3-stamboek.tsx
src/workspace/views/BookmarksOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1161

fix(stamboek): add some missing translations

---

src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1194
collection detail:
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/89620382-dbeeba80-d88f-11ea-9629-5a05d2562e66.png)|![image](https://user-images.githubusercontent.com/1710840/89620370-d8f3ca00-d88f-11ea-8327-4b275da389b8.png)|
bundle detail:
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/89620410-e1e49b80-d88f-11ea-8f33-f354d944ec52.png)|![image](https://user-images.githubusercontent.com/1710840/89620400-dee9ab00-d88f-11ea-8b7f-b427b8e36206.png)|

feat(coll-detail): show created_at in coll/bundle meta data

---

src/collection/collection.gql.ts
src/collection/collection.helpers.tsx
src/collection/collection.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1204
make a public collection:
try to make a public bundle with same name and description: (should work)
try to make same bundle again (should not work)

fix(collections): check unique title/descr. segmented by type

---

package-lock.json
src/admin/items/views/ItemDetail.tsx
src/collection/collection.gql.ts
src/collection/components/CollectionOrBundleEditAdmin.tsx

closes: https://meemoo.atlassian.net/browse/AVO-684

feat(admin-item-detail): show is-public status for collections

---

src/admin/content-block/components/wrappers/MediaPlayerTitleTextButtonWrapper/MediaPlayerTitleTextButtonWrapper.tsx
src/styles/components/_content.scss

closes: https://meemoo.atlassian.net/browse/AVO-251
teacher
hover
pupil

fix(media-player-title-text-button-wrapper): clickable title mam vids

---

src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/shared/components/ContentPicker/item-providers/profile.ts
src/admin/users/user.service.ts

part of: https://meemoo.atlassian.net/browse/AVO-747

fix(content-edit-form): prefill author, fix issue content picker

---

src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx
src/admin/content-block/helpers/generators/media-player.ts
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.scss
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx
src/shared/components/InteractiveTour/InteractiveTour.tsx

closes: https://meemoo.atlassian.net/browse/AVO-944

feat(flow-player): add annotations with copyright symbol

---

src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.service.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/shared/components/ChangeAuthorModal/ChangeAuthorModal.tsx
src/admin/shared/components/ChangeLabelsModal/ChangeLabelsModal.tsx
src/admin/shared/components/FilterTable/FilterTable.scss
src/admin/shared/components/FilterTable/FilterTable.tsx
src/shared/components/DeleteObjectModal/DeleteObjectModal.tsx
src/shared/translations/nl.json

closes: 
* https://meemoo.atlassian.net/browse/AVO-810
* https://meemoo.atlassian.net/browse/AVO-813

feat: bulk actions for collections and bundles

---

src/admin/items/items.const.ts
src/admin/items/items.types.ts
src/admin/items/views/ItemsOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-274

feat(items-overview): replace yes/no with published/depublished

---

package-lock.json
package.json
src/admin/content-block/components/wrappers/ImageGridWrapper/ImageGridWrapper.tsx
src/admin/content-block/content-block.const.ts
src/admin/content-block/helpers/generators/image-grid.ts

closes: https://meemoo.atlassian.net/browse/AVO-188
requires PR: https://github.com/viaacode/avo2-components/pull/375
||align left|align center|align right|
|:---:|:---:|:---:|:---:|
|text align left|![image](https://user-images.githubusercontent.com/1710840/89905414-72054680-dbea-11ea-9219-1ee81e92ba98.png)|![image](https://user-images.githubusercontent.com/1710840/89905635-b55fb500-dbea-11ea-86b2-96ef568bd4a9.png)|![image](https://user-images.githubusercontent.com/1710840/89905750-d4f6dd80-dbea-11ea-9825-c9ec44a3095e.png)|
|text align center|![image](https://user-images.githubusercontent.com/1710840/89905424-7598cd80-dbea-11ea-88ab-900ed36dffdc.png)|![image](https://user-images.githubusercontent.com/1710840/89905642-b7297880-dbea-11ea-8be3-a17d9cb26066.png)|![image](https://user-images.g …

feat(image-grid-wrapper): split align into text-align and global align

---

src/admin/items/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-698

fix(admin-item-detail): remove fields

---

src/authentication/helpers/redirects.ts
src/authentication/store/actions.tsx
src/authentication/views/RegisterOrLogin.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1008

feat(auth-actions): redirect to original page after automatic logout

---

src/collection/components/CollectionOrBundleEditMetaData.tsx

closes: https://meemoo.atlassian.net/browse/AVO-844

fix(bundle-edit-meta-data): update max length counter on every render

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1010
component PR: https://github.com/viaacode/avo2-components/pull/378

fix(media-grid-wrapper): cache results if query is the same

---

src/shared/components/InteractiveTour/InteractiveTour.scss
src/shared/components/InteractiveTour/InteractiveTour.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1227
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/90014175-e7365180-dca6-11ea-9fae-69a5e6b1e400.png)|![image](https://user-images.githubusercontent.com/1710840/90014186-ea314200-dca6-11ea-8d77-16452557870a.png)|

fix(interactive-tour): set spotlight color + increase scroll offset

---

src/search/components/SearchResultItem.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1150
good test url: http://localhost:8080/zoeken?filters=%7B%22serie%22%3A%5B%22KLAAR%22%5D%2C%22provider%22%3A%5B%22VRT%22%5D%2C%22query%22%3A%22hoe%20regering%22%7D
before:
after:

fix(search-result-item): remove markdown links from description

---

src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-846
collection detail:
bundle detail:

fix(collection-detail): improve extra info alignment

---

src/settings/settings.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-751

feat(settings-service): fetch subjects in alphabetical order

---

src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleEditAdmin.tsx

closes: https://meemoo.atlassian.net/browse/AVO-505
requires PR's:
* https://github.com/viaacode/avo2-proxy/pull/214
related Pr's:
* https://github.com/viaacode/avo2-typings/pull/85

feat(collection-edit-admin): allow edit of briefing property on coll.

---

src/admin/items/items.gql.ts
src/admin/items/items.service.ts
src/admin/items/views/ItemDetail.tsx
src/assignment/views/AssignmentEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-728
maak collectie aan met item
maak opdracht aan met item
bookmark een item
depubliceer het item
het fragment in de collectie wordt gewist:
de opdracht inhoud toont als verwijderd:
de bookmark is verwijderd:

feat(items): remove links to item on unpublish

---

src/admin/content/content.types.ts
src/admin/content/views/ContentOverview.tsx

fix(content-page-overview): add missing published_at column

---

src/shared/components/CheckboxDropdownModal/CheckboxDropdownModal.tsx

part of: https://meemoo.atlassian.net/browse/AVO-479

fix(checkbox-modal): reset search keyword on modal close

---

src/admin/content/content.gql.ts
src/admin/content/content.service.ts

fix(content-picker): fix issue with content picker content page search

---

src/workspace/views/BookmarksOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-326

fix(bookmarks-overview): uncomment parameter to show icon

---

src/admin/content/components/ContentEditForm/ContentEditForm.scss

part of: https://meemoo.atlassian.net/browse/AVO-747
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/90238569-761da800-de26-11ea-8a55-1b0a484eb543.png)|![image](https://user-images.githubusercontent.com/1710840/90238584-79b12f00-de26-11ea-85d8-e30054e98928.png)|

fix(content-edit-form): add margin between fields

---

src/collection/collection.helpers.tsx
src/collection/components/CollectionOrBundleEditMetaData.tsx

closes: https://meemoo.atlassian.net/browse/AVO-844
before:
after:

fix(collection-edit-meta): calculate length without html, show error

---

src/collection/views/CollectionDetail.tsx
src/shared/services/related-items-service.ts

related to: https://meemoo.atlassian.net/browse/DEV-831
This PR requires a proxy PR: https://github.com/viaacode/avo2-proxy/pull/224

fix(collection-detail): restore related items request for private coll.

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1294

fix(collections-overview): enable date filter

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/users/views/UserOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1293

fix(collections-overview): fix filter by user group

---

src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleEditContent.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/collection/components/modals/CutFragmentModal.tsx
src/shared/components/DraggableList/DraggableList.tsx
src/shared/components/DraggableList/DraggableListModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1045

fix(fragment-edit): fix issue with fragment react keys + cuepoints

---

src/admin/content/views/ContentOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1303

fix(content-overview): disable sorting for user group column

---

src/collection/components/CollectionOrBundleEditMetaData.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1300

fix(collection-meta-edit): fix short description counter and error mess.

---

src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.service.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1299

Update updated_at and last-changed-by props during bulk actions

---

src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/content.gql.ts
src/admin/content/content.types.ts
src/admin/content/helpers/parsers.ts
src/admin/content/views/ContentDetailMetaData.tsx

closes: https://meemoo.atlassian.net/browse/AVO-972

feat(content-edit-form): add meta-description for exporting content page

---

package-lock.json
src/assignment/views/AssignmentOverview.tsx
src/shared/helpers/formatters/date.ts

closes: https://meemoo.atlassian.net/browse/AVO-1301
before:
after:

fix(assignment-overview): show deadline in absolute terms not relative

---

package-lock.json
package.json
src/admin/shared/components/ChangeLabelsModal/ChangeLabelsModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1298

fix(change-labels-modal): reset labels when closing modal

---

src/admin/admin.const.ts
src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/admin/content/content.gql.ts
src/admin/content/content.service.ts
src/admin/content/views/ContentEdit.tsx
src/authentication/helpers/permission-service.ts
src/content-page/views/ContentPage.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1321
test url: http://localhost:8080/faq-overzicht-2?item=/faq-ineke-1
before while logged in:
after while logged in:
before while logged out:
after while logged out:

fix(page-overview-wrapper): load content pages through proxy

---

src/admin/content-block/helpers/generators/defaults.ts
src/admin/content-block/helpers/generators/hero.ts
src/admin/content-block/helpers/generators/media-player-title-text-button.ts
src/admin/content-block/helpers/generators/media-player.ts
src/admin/shared/helpers/validation.ts

closes: https://meemoo.atlassian.net/browse/AVO-1178

fix(media-player-block): switch video file uploader to url text field

---

src/admin/admin.const.ts
src/admin/items/items.const.ts
src/admin/items/items.gql.ts
src/admin/items/items.service.ts
src/admin/items/items.types.ts
src/admin/items/views/PublishItemsOverview.tsx
src/shared/services/data-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-358
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/232
implemented:
* status filter
* status column
* publishing behavior
Still an issue that the rows do not disappear after changing the status to "OK". Will pass this to Bart

feat(publish-items-overview): add publish behavior + status filter

---

src/search/views/Search.tsx

closes: https://meemoo.atlassian.net/browse/AVO-800
prototype:
before fix:
after fix:

fix(search): remove container so search page goes wider

---

src/authentication/views/registration-flow/r4-manual-registration.tsx
src/item/components/modals/ReportItemModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-306

fix(report-item-modal): add page url to html body of zendesk ticket

---

src/admin/content-block/helpers/generators/image-grid.ts
src/shared/components/FileUpload/FileUpload.tsx

closes: https://meemoo.atlassian.net/browse/AVO-995
before:
after:

fix(image-grid): hide delete button

---

src/item/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1064

fix(item-detail): show toast on toggle bookmark

---

src/admin/content/views/ContentOverview.tsx
src/shared/helpers/formatters/avatar.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1363

fix(content-overview): remove company from author name

---

package-lock.json
package.json
src/admin/content-block/helpers/field-attributes.ts
src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/content.types.ts
src/admin/interactive-tour/helpers/reducers/interactive-tour-edit.ts
src/admin/interactive-tour/interactive-tour.types.ts
src/admin/items/components/DepublishItemModal/DepublishItemModal.tsx
src/admin/items/views/ItemDetail.tsx
src/admin/shared/types/content-block.ts
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/collection/components/CollectionOrBundleEditMetaData.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/react-app-env.d.ts
src/shared/components/WYSIWYGWrapper/WYSIWYGWrapper.tsx
src/shared/constants/wysiwyg.ts

closes: https://meemoo.atlassian.net/browse/AVO-1335
requires component pr: https://github.com/viaacode/avo2-components/pull/392
* lazy load wysiwyg from components separate entry point
* update html sanitizer ro reduce huge package size (250KB)
* add analyse command to get insight into package sizes in bundles app

feat(wysiwyg): reduce package size by lazyloading and update sanitizer

---

src/admin/menu/views/MenuEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-660

fix(menu-edit): redirect to menu detail after create/edit page

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/shared/components/FilterTable/FilterTable.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1323
steps:

fix(filter-table): expose selection, remove selection if not match filtr

---

src/collection/components/CollectionOrBundleOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-991
requires components PR: https://github.com/viaacode/avo2-components/pull/398

fix(collections-overview): allow button wrap in empty state

---

src/shared/components/Navigation/Navigation.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1040
test url: http://localhost:8080/student-leerkracht
before:
after:

fix(navigation): trigger fetch login state when navigation loads without

---

src/authentication/components/LoginOptions.tsx
src/authentication/helpers/redirects.ts

closes: https://meemoo.atlassian.net/browse/AVO-704

fix(login-options): back button after idp login page doesn't work

---

src/shared/components/CheckboxDropdownModal/CheckboxDropdownModal.tsx
src/styles/generic/_global.scss

closes: https://meemoo.atlassian.net/browse/AVO-993
requires components PR: https://github.com/viaacode/avo2-components/pull/394

fix(checkbox-dropdown-modal): limit checkboxes  on mobile

---

src/admin/content/views/ContentEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-271

fix(content-edit): reset path error if path is valid

---

src/search/views/Search.tsx

closes: https://meemoo.atlassian.net/browse/AVO-990
partially fixed in: https://meemoo.atlassian.net/browse/AVO-993

fix(search): replace delete filters button by icon on mobile

---

src/search/components/SearchFilterControls.scss
src/search/components/SearchFilterControls.tsx
src/search/views/Search.scss
src/search/views/Search.tsx
src/shared/components/CheckboxDropdownModal/CheckboxDropdownModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-580
requires component PR: https://github.com/viaacode/avo2-components/pull/401
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/92504415-ec81b000-f202-11ea-968c-9652d3451f53.png)|![image](https://user-images.githubusercontent.com/1710840/92504365-dd026700-f202-11ea-8e66-8a0fa825664e.png)|

fix(search): make mobile filters full width inside accordion

---

src/admin/shared/components/TopBar/TopBar.scss
src/admin/shared/components/TopBar/TopBar.tsx

closes: https://meemoo.atlassian.net/browse/AVO-975
before:
after:

fix(top-bar): set max width for title and add tooltip + ellipsis

---

src/item/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-14
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/92505131-e809c700-f203-11ea-884a-95cc5508799c.png)|![image](https://user-images.githubusercontent.com/1710840/92505134-ea6c2100-f203-11ea-923a-5b6ab5682121.png)|

fix(item-detail): change add icon to scissors icon

---

src/assignment/views/AssignmentDetail.scss
src/assignment/views/AssignmentDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1019
requires components PR: https://github.com/viaacode/avo2-components/pull/400
before:
after:

fix(assignment-detail): fix styles on mobile

---

src/styles/objects/_app.scss

|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/92607898-05e33480-f2b5-11ea-8163-80f41dd1b5a2.png)|![image](https://user-images.githubusercontent.com/1710840/92607939-109dc980-f2b5-11ea-99b1-4665356819e0.png)|

fix(app): set max-width nav-bar to 100vw

---

src/App.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1066

fix(app): disable smooth scroll

---

package-lock.json
package.json
src/shared/helpers/sanitize/index.ts

since this causes issues for the cookies page: https://github.com/apostrophecms/sanitize-html/pull/410

fix(sanitize-html): revert 2.0 version of sanitize html

---

src/shared/helpers/navigation.tsx

fix(navigation): redirect login button on mobile to register-or-login

---

src/admin/admin.const.ts

part of: https://meemoo.atlassian.net/browse/AVO-1305

fix(admin-routes): disable nav items until pages are implemented

---

src/admin/items/views/PublishItemsOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1368

feat(publish-items-overview): enable search by title

---

package-lock.json
package.json
src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx
src/admin/items/items.gql.ts
src/admin/items/views/ItemDetail.tsx
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx
src/shared/helpers/get-subtitles.ts

closes: https://meemoo.atlassian.net/browse/AVO-468
requires other PR's:
* https://github.com/viaacode/avo2-proxy/pull/246
* https://github.com/viaacode/avo2-components/pull/403
related PR:
* https://github.com/viaacode/avo2-typings/pull/88
detail page:
// Media tegel block
// media speler met titel en description blok
// admin dashboard

feat(subtitles): add subtitle support for videos

---

src/admin/shared/components/ChangeAuthorModal/ChangeAuthorModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1374

fix(change-author-modal): reset selected to initial author on close

---

src/admin/items/items.const.ts
src/admin/items/items.types.ts
src/admin/items/views/PublishItemsOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-358

feat(publish-items): compute avo publish state instead of mam status

---

src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/content.service.ts
src/admin/content/views/ContentEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1387
When the path is generated from the title (kebabcase) the path doesn't seem to save correctly sometimes

bugfix(content-edit-form): correctly save default paths

---

src/settings/components/Profile.scss
src/settings/components/Profile.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1380
before:
after:

fix(profile): add more padding at the bottom of the profile page

---

src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx
src/item/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1379
item detail:
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/94428501-10e10480-0191-11eb-8b5b-19279339d6fe.png)|![image](https://user-images.githubusercontent.com/1710840/94428508-12aac800-0191-11eb-8833-34da5ea20c43.png)|
collection detail:
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/94428832-b3998300-0191-11eb-8aab-210e05bff308.png)|![image](https://user-images.githubusercontent.com/1710840/94428870-c14f0880-0191-11eb-8d29-e0120461c0b8.png)|
bundle detail:
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/94428888-c6ac5300-0191-11eb-89cd-cfaef8f83428.png)|![image](https://user-images.githubusercontent.com/1710840 …

fix(item-detail): show category items on related item thumbnails

---

src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx
src/item/views/ItemDetail.tsx
src/shared/helpers/handle-related-item-click.ts

closes: https://meemoo.atlassian.net/browse/AVO-1378

fix(item-detail): related items unify link + correct link per type

---

package-lock.json
package.json

closes: https://meemoo.atlassian.net/browse/AVO-1373

chore(package.json): update dependencies to improve security

---

src/admin/users/user.gql.ts

part of: https://meemoo.atlassian.net/browse/AVO-1401

fix(user-gql): remove fields from user overview query that are not used

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/content-page-labels/views/ContentPageLabelOverview.tsx
src/admin/content/views/ContentOverview.tsx
src/admin/interactive-tour/views/InteractiveTourOverview.tsx
src/admin/items/views/ItemsOverview.tsx
src/admin/items/views/PublishItemsOverview.tsx
src/admin/permission-groups/views/PermissionGroupOverview.tsx
src/admin/shared/components/FilterTable/FilterTable.scss
src/admin/shared/components/FilterTable/FilterTable.tsx
src/admin/user-groups/views/UserGroupOverview.tsx
src/admin/users/views/UserOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1385

feat(filter-table): add spinner while table data is loading

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

part of: https://meemoo.atlassian.net/browse/AVO-1385

fix(collection-overview): remove unused fields from query

---

src/authentication/helpers/redirects.ts
src/authentication/views/Login.tsx
src/shared/components/InteractiveTour/InteractiveTour.tsx
src/shared/helpers/fetch-with-logout.ts
src/shared/services/interactive-tour-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1399
You can check this by starting chrome with this command line option: --disable-local-storage
Then load: http://localhost:8080/projecten/klaar
before:
after:

fix(interactive-tour): check if localStorage exists before using it

---

src/admin/users/views/UserDetail.tsx
src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx
src/item/views/ItemDetail.tsx
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.const.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.gql.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.types.ts

closes: https://meemoo.atlassian.net/browse/AVO-1398
* We used to just try to insert a view of 1 into the database
* if this threw an error then we would increment the counter.
This outputs a lot of errors in the logs
So now, we check the count. 
* If it is undefined, we insert a count of 1
* if it is defined, we increate the count by one

fix(item-detail): fix issues with init view/play counters

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx

part of: https://meemoo.atlassian.net/browse/AVO-1400
requires components PR: https://github.com/viaacode/avo2-components/pull/408

chore(media-grid-wrapper): rename media list to media grid

---

src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/collection/components/CollectionOrBundleEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1328
assignment edit:
assignment create:
collection edit:
bundle edit:

feat(assignment-create): move save buttons to the left

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.const.ts
src/admin/content-block/components/wrappers/CtaWrapper/CtaWrapper.tsx
src/admin/content-block/components/wrappers/index.ts
src/assignment/views/AssignmentDetail.tsx
src/bundle/views/BundleDetail.scss
src/bundle/views/BundleDetail.tsx
src/collection/components/fragment/FragmentDetail.tsx
src/item/components/ItemVideoDescription.tsx
src/item/components/modals/AddToCollectionModal.tsx
src/item/views/ItemDetail.scss
src/item/views/ItemDetail.tsx
src/shared/helpers/media-query.ts

closes: https://meemoo.atlassian.net/browse/AVO-1290

feat(mobile): mobile layout improvements

---

src/item/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1116

feat(item-detail): add translations for item detail meta data

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

related to: https://meemoo.atlassian.net/browse/AVO-1385
before:
after:

fix(collection-overview): get full_name for last edited by column

---

src/collection/components/CollectionOrBundleOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1302
collectie werkruimte:
bundels werkruimte:

feat(collection-overview): show update date instead of from now date

---

src/collection/components/CollectionOrBundleEditMetaData.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1075

feat(collection-edit): add placeholder translation for short description

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/shared/components/AddOrRemoveLinkedElementsModal/AddOrRemoveLinkedElementsModal.tsx
src/admin/users/user.const.ts
src/admin/users/user.gql.ts
src/admin/users/user.service.ts
src/admin/users/user.types.ts
src/admin/users/views/UserDetail.tsx
src/admin/users/views/UserOverview.tsx
src/shared/services/data-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1342
block:
unblock:
add subjects:
remove subjects:

feat(user-overview): add bulk actions: block, unblock, edit subjects

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/users/user.const.ts
src/admin/users/user.gql.ts
src/admin/users/views/UserDetail.tsx
src/admin/users/views/UserOverview.tsx
src/authentication/helpers/get-profile-info.ts
src/settings/components/Profile.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1286

fix(user-overview): allow sorting of users by their user group

---

src/authentication/helpers/redirects.ts
src/authentication/views/RegisterOrLogin.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1415

fix(register-or-login): correctly redirect to home page for mobile

---

src/admin/content/views/ContentDetail.scss
src/admin/content/views/ContentDetail.tsx

|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/98005929-e74f7480-1df1-11eb-822d-22af13b7e583.png)|![image](https://user-images.githubusercontent.com/1710840/98005935-e9b1ce80-1df1-11eb-9181-d8800f451ed1.png)|

fix(content-detail): remove redundant wrapper that causes scrollbar

---

src/search/search.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1406
do not include time
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/97998214-1cf05f80-1dea-11eb-917f-652c771f91de.png)|![image](https://user-images.githubusercontent.com/1710840/97998221-1e218c80-1dea-11eb-971c-504d7665df5e.png)|

fix(search-service): search items by date only

---

src/admin/items/views/ItemsOverview.tsx
src/settings/components/Profile.tsx
src/shared/hooks/useCompanies.ts
src/shared/services/organizations-service.gql.ts
src/shared/services/organizations-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1304
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/97900737-633ab580-1d3b-11eb-942a-ffb130e2386f.png)|![image](https://user-images.githubusercontent.com/1710840/97900744-65047900-1d3b-11eb-8685-4d2f40974040.png)|

feat(item-overview): only show CP's that have items

---

src/admin/users/user.gql.ts
src/admin/users/user.service.ts
src/admin/users/views/UserDetail.tsx
src/admin/users/views/UserOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1366
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/263

feat(user-overview): block user + send email

---

src/assignment/assignment.const.ts
src/assignment/assignment.gql.ts
src/assignment/assignment.service.ts
src/assignment/views/AssignmentEdit.scss
src/assignment/views/AssignmentOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1423
fix issue with fetching duplicate assignments when duplicate responses existed:
also fixed issue with date popup causing scrollbar:

fix(assignment-overview): avoid fetching duplicate assignments

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.const.ts
src/admin/content-block/components/wrappers/LogoGridWrapper/LogoGridWrapper.tsx
src/admin/content-block/components/wrappers/UspGridWrapper/UspGridWrapper.tsx
src/admin/content-block/components/wrappers/index.ts
src/admin/content-block/content-block.const.ts
src/admin/content-block/helpers/generators/logo-grid.ts
src/admin/content-block/helpers/generators/usp-grid.ts
src/admin/shared/types/content-block.ts

closes: https://meemoo.atlassian.net/browse/AVO-732
requires components PR: https://github.com/viaacode/avo2-components/pull/420
test page: http://localhost:8080/usp-test-page

feat(usp-grid-wrapper): add usp block

---

src/admin/Admin.tsx
src/admin/admin.const.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/content-page-labels/content-page-label.service.ts
src/admin/content-page-labels/hooks/useContentPageLabelOptions.ts
src/admin/content-page-labels/views/ContentPageLabelOverview.tsx
src/admin/content/content.const.tsx
src/admin/content/content.gql.ts
src/admin/content/content.types.ts
src/admin/content/views/ContentDetailMetaData.tsx
src/admin/content/views/ContentOverview.tsx
src/admin/interactive-tour/views/InteractiveTourOverview.tsx
src/admin/items/views/ItemsOverview.tsx
src/admin/items/views/PublishItemsOverview.tsx
src/admin/menu/views/MenuEdit.tsx
src/admin/permission-groups/views/PermissionGroupOverview.tsx
src/admin/shared/components/UserGroupSelect/UserGroupSelect.tsx
src/admin/shared/helpers/filters.ts
src/admin/user-groups/hooks/useUserGroupOptions.ts
src/admin/user-groups/hooks/useUserGroups.ts
src/admin/user-groups/user-group.const.ts
src/admin/user-groups/user-group.service.ts
src/admin/user-groups/views/UserGroupOverview.tsx
src/admin/users/views/UserOverview.tsx
src/authentication/helpers/get-profile-info.ts
src/shared/helpers/set-selected-checkboxes.ts

partially closes: https://meemoo.atlassian.net/browse/AVO-1232
still TODO: 
* Kolom publicatie
* Kolom laatste bewerkt
search by slug:
filter by user group of the author:
filter by label and show labels column:
sort author by first name
sort by update at date by default:
filter by current user by default:
sort by author user group:
add column: visible for:

feat(content-overview): add columns and filters

---

src/admin/user-groups/views/UserGroupDetail.tsx

feat(user-group-detail): implement permission group edit button

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.const.ts
src/admin/content-block/content-block.const.ts
src/admin/content-block/helpers/generators/eventbrite.ts
src/admin/shared/types/content-block.ts

closes: https://meemoo.atlassian.net/browse/AVO-451
requires components PR: https://github.com/viaacode/avo2-components/pull/422

feat(eventbrite-block): add eventbrite block to content block list

---

src/admin/content/components/ContentEditForm/ContentEditForm.tsx
src/admin/content/views/ContentDetailMetaData.tsx

fix(content-page-edit): use generic getFullName function to fetch name

---

src/admin/users/views/UserOverview.tsx

fixes issue in: https://meemoo.atlassian.net/browse/AVO-115

fix(user-overview): wrap csv values in export in double quotes + escape

---

src/admin/content/views/ContentOverview.tsx
src/admin/users/views/UserEdit.tsx
src/shared/components/MultiUserSelectDropdown/MultiUserSelectDropdown.scss
src/shared/components/MultiUserSelectDropdown/MultiUserSelectDropdown.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1232

fix(content-overview): fix minor issues with content page overview table

---

src/admin/content-block/helpers/generators/eventbrite.ts

closes: https://meemoo.atlassian.net/browse/AVO-451

feat(eventbrite): add align option

---

src/settings/components/Account.tsx

closes: https://meemoo.atlassian.net/browse/AVO-978
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/99688003-96907a80-2a85-11eb-8f11-5065c746abdf.png)|![image](https://user-images.githubusercontent.com/1710840/99688010-985a3e00-2a85-11eb-801d-0d05043ec690.png)|

fix(account): hide alert and link idp's from pupils

---

src/bundle/views/BundleDetail.scss
src/bundle/views/BundleDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1078
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/99686835-45cc5200-2a84-11eb-95a5-944f085b6bfd.png)|![image](https://user-images.githubusercontent.com/1710840/99686932-5bda1280-2a84-11eb-93e4-b37eaef0b7fd.png)|

fix(bundle-detail): fix header width on desktop

---

src/shared/helpers/files.ts

closes: https://meemoo.atlassian.net/browse/AVO-1100

feat(files): allow svg upload

---

src/assignment/views/AssignmentEdit.tsx
src/error/views/ErrorView.scss
src/error/views/ErrorView.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1290
component pr: https://github.com/viaacode/avo2-components/pull/424

fix(edit-views): fix issues with wrapping in edit views

---

src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1405

Show fragment cut indicator on video based on sanitized values

---

src/settings/components/Profile.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1390

fix(profile): pass correct ids to proxy instead of org label

---

src/collection/components/CollectionOrBundleEdit.tsx
src/shared/components/DraggableList/DraggableList.scss

closes: https://meemoo.atlassian.net/browse/AVO-1437

fix(draggable-list): fix layout of draggable list items

---

src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1450

fix(collection-overview): show yes/no in is_copy column

---

src/admin/users/views/UserEdit.tsx
src/shared/services/organizations-service.gql.ts

closes: https://meemoo.atlassian.net/browse/AVO-1336
company selected and has logo:
no company selected: 
company selected, but company does not have logo

feat(user-edit): show avatar of company when available

---

src/shared/helpers/cut-start-and-end.ts

closes: https://meemoo.atlassian.net/browse/AVO-1447
example video: http://localhost:8080/collecties/57b75873-bbb1-4080-a170-63b30ffda283/bewerk

feat(cut-start-and-end): remove cut if start and end are identical

---

src/assignment/assignment.helper.tsx
src/assignment/views/AssignmentDetail.scss
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentEdit.scss
src/assignment/views/AssignmentEdit.tsx
src/error/views/ErrorView.scss

closes: https://meemoo.atlassian.net/browse/AVO-1290

fix(mobile-views): fix minor css issues with the mobile views

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/items/views/PublishItemsOverview.tsx
src/admin/shared/components/FilterTable/FilterTable.tsx
src/admin/users/views/UserOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1466

fix(publish-items-overview): fix checkboxes for bulk publish

---

src/shared/components/Navigation/Navigation.scss
src/shared/components/Navigation/Navigation.tsx
src/styles/elements/_base.scss
src/styles/generic/_global.scss

closes: https://meemoo.atlassian.net/browse/AVO-1290
try to scroll sideways:
scroll down and open mobile menu

fix(global-styles): disable body scrolling + make mobile menu fixed

---

src/admin/shared/helpers/filters.ts
src/admin/users/views/UserOverview.tsx
src/shared/components/MultiEducationalOrganisationSelectModal/MultiEducationalOrganisationSelectModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1339

feat(user-overview): fix multiple filters

---

src/assignment/assignment.gql.ts
src/assignment/assignment.helper.tsx
src/assignment/assignment.service.ts
src/assignment/views/AssignmentDetail.tsx
src/shared/hooks/useEffectDebugger.ts

closes: https://meemoo.atlassian.net/browse/AVO-1371
proxy PR: https://github.com/viaacode/avo2-proxy/pull/294
http://localhost:8080/opdrachten/69
http://localhost:8080/opdrachten/25e9aff0-5445-41ba-9644-f7a026319d00
load legacy and new url as pupil works
select first radio by default

fix(assignment): fix issues with assignment legacy ids

---

src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1468
fixed for videos we have been cut:
fixed for videos who have not been cut

fix(flowplayer-wrapper): remove cuepoints if start = 0 and end = vid end

---

src/admin/users/views/UserDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1489
@benji test this using safari en see if it opens in a new tab (good) or in a new window (bad)

feat(user-detail): open acm page using a href instead of javascript

---

src/admin/users/user.gql.ts
src/admin/users/user.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1508
proxy pr: https://github.com/viaacode/avo2-proxy/pull/301

fix(users-overview): export users from view instead of table

---

src/admin/content-block/content-block.const.ts

fix(content-block): fix bg color names

---

src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx
src/shared/helpers/formatters/duration.ts

closes: https://meemoo.atlassian.net/browse/AVO-1511

fix(duration): deduct hours from seconds before calculating minutes

---

src/admin/users/user.const.ts
src/admin/users/views/UserOverview.tsx

part of: https://meemoo.atlassian.net/browse/AVO-1343
proxy PR: https://github.com/viaacode/avo2-proxy/pull/302

feat(users): re-enable bulk delete/block/unblock users

---

src/assignment/assignment.const.ts
src/assignment/assignment.gql.ts
src/assignment/assignment.service.ts
src/assignment/views/AssignmentOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1517
sort by teacher name is now possible:
disabled sorting on "submitted" since this doesn't seem possible in the database:

fix(assignments): fix sort on teacher name, disable sort on submitted_at

---

src/collection/collection.gql.ts
src/collection/collection.helpers.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEditMarcom.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1311
proxy PR: https://github.com/viaacode/avo2-proxy/pull/308
insert a new note:
update an existing note:

feat(marcom): add note field

---

scripts/whitelist-gql-queries.ts
src/admin/content-page-labels/content-page-label.gql.ts
src/admin/permission-groups/permission-group.gql.ts
src/collection/collection.gql.ts
src/shared/services/relation-service/relation.gql.ts

closes: https://meemoo.atlassian.net/browse/AVO-1521
proxy PR: https://github.com/viaacode/avo2-proxy/pull/312

fix(whitelist): avoid duplicate labels, add check in extraction script

---

src/admin/users/user.const.ts

Resolves issue given in comments of https://meemoo.atlassian.net/browse/AVO-1341.

fix(users-overview): disable sort by id

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts

Resolves https://meemoo.atlassian.net/browse/AVO-1566

feat(marcom): hide lastEditedBy column by default

---

src/admin/collectionsOrBundles/helpers/render-collection-columns.tsx
src/collection/collection.const.ts
src/collection/components/CollectionOrBundleEditMarcom.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1555

fix(marcom): fix marcom channel labels, dropdowns, sorting

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/helpers/collection-filters.ts
src/admin/collectionsOrBundles/helpers/render-collection-columns.tsx
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1486
proxy pr: https://github.com/viaacode/avo2-proxy/pull/313

feat(collections-overview): add editorial column + filter + sort

---

src/assignment/assignment.gql.ts

Resolves https://meemoo.atlassian.net/browse/AVO-1578

fix(assignment): add is_deleted clause to select

---

src/collection/collection.gql.ts
src/collection/collection.service.ts

Resolves
https://meemoo.atlassian.net/browse/AVO-1560
https://meemoo.atlassian.net/browse/AVO-1562

fix(collection): save editorial tabs

---

src/shared/components/JsonLd/JsonLd.tsx

Resolves https://meemoo.atlassian.net/secure/RapidBoard.jspa?rapidView=32&modal=detail&selectedIssue=AVO-1547

feat(ga): send title

---

src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/authentication/helpers/get-profile-info.ts

Should resolve: https://meemoo.atlassian.net/browse/AVO-1590

feat(collection-overview): new query

---

src/collection/collection.const.ts

https://meemoo.atlassian.net/secure/RapidBoard.jspa?rapidView=32&modal=detail&selectedIssue=AVO-1568&quickFilter=65

feat(marcom): type & name changes

---

src/admin/user-groups/user-group.const.ts
src/collection/helpers/can-manage-editorial.ts

https://meemoo.atlassian.net/secure/RapidBoard.jspa?rapidView=32&projectKey=AVO&modal=detail&selectedIssue=AVO-1573&quickFilter=65

feat(editorial): special user groups

---

src/admin/permission-groups/permission-group.gql.ts

Resolves: https://meemoo.atlassian.net/browse/AVO-1594

fix(permission-group): gql query

---

src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.service.ts
src/admin/collectionsOrBundles/helpers/collection-filters.ts
src/admin/collectionsOrBundles/helpers/render-collection-columns.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleActualisationOverview.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleQualityCheckOverview.tsx
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/shared/components/FilterTable/FilterTable.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/shared/helpers/formatters/avatar.tsx

Resolves https://meemoo.atlassian.net/browse/AVO-1612 & https://meemoo.atlassian.net/browse/AVO-1613

fix(marcom): show labels on overview

---

scripts/whitelist-gql-queries.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
tsconfig.json

Resolves https://meemoo.atlassian.net/browse/AVO-1615

fix(collections): show subjects & educ levels

---

src/admin/content/content.service.ts
src/admin/translations/translations.service.ts
src/collection/collection.const.ts
src/collection/collection.gql.ts
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEditMarcom.tsx

https://meemoo.atlassian.net/browse/AVO-1552

fix(marcom): delete entry

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.service.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/permission-groups/permission-group.const.ts
src/admin/shared/components/FilterTable/FilterTable.tsx
src/admin/user-groups/user-group.const.ts
src/admin/users/user.const.ts
src/shared/helpers/generate-order-gql-query.ts

fix(collections-overview): sort order

---

src/shared/components/JsonLd/JsonLd.tsx

Fix error when ga not fully loaded

fix(adblock): fixed error when ga not fully loaded

---

src/admin/Admin.tsx
src/admin/admin.const.ts

closes: https://meemoo.atlassian.net/browse/AVO-1543
before:
after:

feat(admin): remove extra filter on owner of the content pages

---

src/dynamic-route-resolver/views/DynamicRouteResolver.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1657
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/353

feat(route-resolver): redirect 404 pages to the proxy not-found route

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/helpers/collection-filters.ts
src/admin/collectionsOrBundles/helpers/render-collection-columns.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleActualisationOverview.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleMarcomOverview.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleQualityCheckOverview.tsx
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/shared/helpers/filters.ts
src/admin/users/views/UserOverview.tsx
src/shared/hooks/useCompanies.ts
src/shared/services/organizations-service.gql.ts
src/shared/services/organizations-service.ts

Updated organisation filter on users page
Based on: https://github.com/viaacode/avo2-client/pull/1227

feat(columnfilter): update organisation filter

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.types.ts
src/admin/collectionsOrBundles/helpers/collection-filters.ts
src/admin/collectionsOrBundles/helpers/render-collection-columns.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleActualisationOverview.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleMarcomOverview.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleQualityCheckOverview.tsx
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/shared/helpers/filters.ts
src/shared/hooks/useCompanies.ts
src/shared/services/organizations-service.gql.ts
src/shared/services/organizations-service.ts

https://meemoo.atlassian.net/browse/AVO-1455
Add organisation column and filter
fixes education levels filter
Also requires: https://github.com/viaacode/avo2-proxy/pull/354

feat(columnfilter): add organisation column and filter

---

public/robots.txt

closes: https://meemoo.atlassian.net/browse/AVO-1659
validity testing:
https://www.google.com/webmasters/tools/robots-testing-tool

feat(robot-txt): add robot.txt file with urls to be ignored

---

public/unsupported-browser.html
src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.scss
src/admin/content-block/components/fields/ColorSelect/ColorSelect.tsx
src/admin/content/views/ContentEdit.scss
src/admin/menu/views/MenuDetail.scss
src/admin/shared/components/Sidebar/Sidebar.scss
src/admin/shared/layouts/AdminLayout/AdminLayout.scss
src/error/views/ErrorView.scss
src/shared/components/FileUpload/FileUpload.scss
src/shared/components/Footer/Footer.scss
src/shared/components/Navigation/Navigation.scss
src/shared/components/ResizablePanels/ResizablePanels.tsx
src/shared/components/ResizablePanels/components/Resizer.tsx
src/styles/components/_checkbox-radio.scss
src/styles/components/_content.scss
src/styles/components/_filter-dropdown.scss
src/styles/components/_input.scss
src/styles/components/_label.scss
src/styles/components/_navbar.scss
src/styles/components/_oauth-buttons.scss
src/styles/components/_progress-bar.scss
src/styles/components/_projects-grid.scss
src/styles/components/_table-view.scss
src/styles/components/_tri.scss
src/styles/components/_usp-grid.scss
src/styles/elements/_base.scss
src/styles/trumps/_mq-debug.scss
src/styles/utilities/_generic.scss

closes: https://meemoo.atlassian.net/browse/AVO-1493
requires component PR: https://github.com/viaacode/avo2-components/pull/453
Please try to access this page while logged in as a teacher/student on Safari: http://localhost:8080/beheer
You should see:
and not:

fix(error-view): attempt to fix background-color on safari

---

src/admin/users/user.gql.ts

fix(filtering): fixed wrong query

---

src/admin/users/user.service.ts
src/admin/users/views/UserDetail.tsx

Closes: https://meemoo.atlassian.net/browse/AVO-465

AVO-465: Send temp access email to users who already has access.

---

src/collection/collection.gql.ts
src/workspace/workspace.gql.ts

fix(collections): only show public bundles and collections for partners

---

src/search/components/BlockSearch.scss

fix(search): center suggestions under input

---

src/settings/components/Profile.tsx

fix(profile): show spinner when saving user profile

AV0-1668 save profile info

---

src/settings/components/Profile.tsx

fix(spinner): add spacer around spinner

---

src/shared/helpers/idps-to-taglist.tsx

Handles https://meemoo.atlassian.net/browse/AVO-1775

fix(tags): idp colors

---

src/settings/components/LinkedAccounts.tsx

Confirm modals toegevoegd bij verbreken van koppeling

AVO-1709 add confirm modal

---

src/authentication/helpers/redirects.ts
src/shared/components/ACMIDMNudgeModal/ACMIDMNudgeModal.tsx
src/shared/components/InteractiveTour/InteractiveTour.tsx
src/store.ts
src/uistate/store/actions.ts
src/uistate/store/initial-state.ts
src/uistate/store/reducer.ts
src/uistate/store/selectors.ts
src/uistate/store/types.ts

Ineke's feedback processed
Charlotte's feedback NOT (yet)

fix: update nudging logic

---

src/admin/users/user.gql.ts
src/admin/users/views/UserOverview.tsx
src/settings/components/Account.tsx
src/settings/components/Profile.tsx

https://meemoo.atlassian.net/browse/AVO-1777

feat(account): hide temp access if off

---

src/error/views/ErrorView.tsx

fix: incomplete logout param check

fix: incomplete logout param check

---

src/admin/users/components/UserDeleteModal.tsx
src/admin/users/views/UserDetail.tsx
src/admin/users/views/UserOverview.tsx

- Extract delete modals in separate file
- implemented on user overview and user detail

feat: add user delete modal on user detail page

---

src/admin/collectionsOrBundles/helpers/collection-filters.ts
src/admin/collectionsOrBundles/views/CollectionOrBundleMarcomOverview.tsx

hides communication entries for collections and bundles with channel type 'overige'

AVO-1727 hide entries with channel type overige

---

src/authentication/components/LoginOptions.tsx
src/shared/components/ACMIDMNudgeModal/ACMIDMNudgeModal.tsx
src/shared/constants/index.ts

https://meemoo.atlassian.net/browse/AVO-1836?focusedCommentId=28974

feat(avo-1836): use localstorage to avoid nudging

---

package-lock.json
package.json
src/collection/components/modals/AutoplayCollectionModal.tsx

fix(avo-1724): autoplay bugfixes

---

src/admin/content-block/services/content-block.service.ts
src/admin/content/content.service.ts

https://meemoo.atlassian.net/browse/AVO-1933
before:
after:

fix(AVO-1933): Show only one error if content block save fails

---

src/shared/services/quick-lane-filter-service.ts

https://meemoo.atlassian.net/browse/AVO-1869

fix(avo-1869): add missing sorting mapper

---

src/App.tsx

quick fix for react datepicker styles:
before:
after:

fix(avo-1954): Add css for react-date-picker

---

src/assignment/assignment.gql.ts

fix: pupil assignment queries

---

src/assignment/assignment.gql.ts
src/assignment/assignment.service.ts
src/assignment/pupil-collection.gql.ts
src/assignment/pupil-collection.service.ts
src/assignment/views/AssignmentResponseEdit.tsx
src/authentication/helpers/permission-service.ts
src/collection/helpers/fragment.ts
src/item/components/modals/AddToAssignmentModal.tsx
src/item/views/ItemDetail.tsx

https://meemoo.atlassian.net/browse/AVO-1911
Login as a user:
accounts+leerling@meemoo.be
Go to a detail page inside an assignment:
http://localhost:8080/opdrachten/24e6164e-5dda-4de9-af05-4363499c3a96?selectedSearchResultId=d795748m0f&tab=SEARCH
click the add to collection button
crop the video and click the "knip" button
Toast message is shown:
fragment is added to the collection and loaded to be rendered in the "my collection" tab:

feat(avo-1911): add fragment to pupil collection

---

package-lock.json
package.json
src/bundle/views/BundleDetail.tsx
src/collection/views/CollectionDetail.tsx
src/shared/components/QuickLaneModal/QuickLaneModal.types.ts

The render loop would occur when visiting a collection detail. eg:
http://localhost:8080/collecties/82451704-ffb0-4466-a126-4f0a1dc724de
Now it doesn't loop.

fix(avo-1910): fix render loop collection detail

---

src/admin/pupil-collection/views/PupilCollectionsOverview.tsx
src/pupil-collection/pupil-collection.gql.ts
src/pupil-collection/pupil-collection.service.ts

https://meemoo.atlassian.net/browse/AVO-1935

feat(avo-1935): also delete assignment response when deleting pupil coll

---

src/assignment/components/ShareAssignmentWithPupil.scss
src/assignment/components/ShareAssignmentWithPupil.tsx
src/assignment/views/AssignmentEdit.tsx

https://meemoo.atlassian.net/browse/AVO-1898

feat(avo-1898): add share assignment link with pupil button

---

package-lock.json
src/shared/components/StickySaveBar/StickySaveBar.scss
src/styles/components/_index.scss
src/styles/components/_sticky-edge-bar.scss

fix(save-bar): change z-index to be behind modals

---

package-lock.json
package.json
src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponseSearchTab.tsx
src/shared/services/event-logging-service.ts

https://meemoo.atlassian.net/browse/AVO-2001
track search queries from pupils searching inside an assignment context and store them in the eventlogger database
```typescript
trackEvents(
{
object: assignment.id,
object_type: 'avo_assignment',
action: 'search',
resource: newFilterState.filters,
},
user
);
```

feat(avo-2001): track event for pupil search queries

---

src/collection/components/CollectionFragmentMeta.tsx
src/collection/components/CollectionOrBundleEditContent.tsx
src/collection/views/CollectionDetail.tsx
src/shared/components/BlockList/blocks/CollectionFragmentTypeItem.tsx

since switching to the new layout was not in scope for "zoek en bouw"

fix(collection-detail-and-edit): hide new blocks

---

src/admin/assignments/assignments.const.ts
src/admin/assignments/views/AssignmentsOverviewAdmin.tsx
src/assignment/assignment.const.ts
src/assignment/assignment.gql.ts
src/assignment/assignment.service.ts
src/assignment/views/AssignmentResponseEdit/AssignmentResponseEditPage.tsx

https://meemoo.atlassian.net/browse/AVO-1990
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/463
Increments the view count in assignment_v2_views when a pupil visits the assignment share link
Also triggers an event in the event logging hasura

feat(avo-1990): add assignment view count

---

src/assignment/modals/AddBookmarkFragmentModal.tsx
src/assignment/views/AssignmentCreate.tsx

add callback config for modals
wrap addbookmarkfragmentmodal withUser

fix(create-assign): fix add fragments and collections to new assignment

---

src/assignment/assignment.service.ts
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/collection/views/CollectionDetail.tsx

https://meemoo.atlassian.net/browse/AVO-1999

feat(avo-1999): track event when user imports collection into assignment

---

src/admin/content-block/helpers/parsers.ts
src/assignment/helpers/insert-at-position.ts
src/assignment/helpers/switch-positions.ts
src/assignment/hooks/assignment-blocks-list.tsx
src/assignment/hooks/assignment-content-modals.tsx
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponsePupilCollectionTab.tsx
src/collection/components/CollectionFragmentRichText.tsx
src/collection/components/CollectionFragmentTitle.tsx
src/collection/components/fragment/FragmentList.tsx
src/shared/components/ListSorter/ListSorter.tsx
src/shared/helpers/index.ts
src/shared/helpers/sort.ts

https://meemoo.atlassian.net/browse/AVO-2007
* ensure swapped blocks are sorted correctly in the blocks array
* merge insertAtPosition and insertMultipleAtPosition
* replace insertAtPosition with simpler implementation

fix(avo-2007): ensure swapped blocks are sorted, reduce duplication

---

src/shared/components/DataQueryComponent/DataQueryComponent.tsx

Fix bug when trying to fetch navigation elements in avo admin dashboard:
In the future we want to get rid of apollo entirely and replace it with strongly typed queries + the react-query library
```
useQuery.ts:463 Uncaught TypeError: Cannot read properties of undefined (reading 'bind')
at useQuery.ts:463:1
at mountMemo (react-dom.development.js:15442:1)
at Object.useMemo (react-dom.development.js:15738:1)
at useMemo (react.development.js:1521:1)
at InternalState.useObservableQuery (useQuery.ts:461:1)
at InternalState.useQuery (useQuery.ts:135:1)
at useQuery (useQuery.ts:48:1)
at DataQueryComponent (DataQueryComponent.tsx:46:1)
at renderWithHooks (react-dom.development.js:14803:1)
at mountIndeterminateComponent (react-dom.development.js:17482:1)
react-dom.development.js:19527 The above …
```

fix(data-query-component): replace useQuery with dataService

---

package-lock.json
src/assignment/components/AssignmentUnload.tsx
src/assignment/components/blocks/AssignmentBlockEditItem.tsx
src/assignment/hooks/assignment-block-description-buttons.tsx
src/assignment/hooks/assignment-blocks.tsx
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponsePupilCollectionTab.tsx
src/shared/components/ConfirmModal/ConfirmModal.tsx
src/shared/components/StickySaveBar/StickySaveBar.tsx
src/shared/translations/nl.json

https://meemoo.atlassian.net/browse/AVO-2006
https://meemoo.atlassian.net/browse/AVO-2005
https://meemoo.atlassian.net/browse/AVO-2009

Bugfix/avo 2006 + Bugfix/avo 2005 + Bugfix/avo 2009

---

src/admin/assignments/assignments.const.ts
src/admin/assignments/assignments.types.ts
src/admin/assignments/views/AssignmentsOverviewAdmin.tsx
src/assignment/assignment.const.ts
src/assignment/assignment.types.ts

https://meemoo.atlassian.net/browse/AVO-2019

fix(avo-2019): fix sorting by teacher in pupil assignment overview

---

src/admin/assignments/views/AssignmentsOverviewAdmin.tsx

https://meemoo.atlassian.net/browse/AVO-2043

fix(avo-2043): also filter by teacher when linking to pupil collections

---

src/assignment/views/AssignmentResponseEdit/AssignmentResponseEditPage.tsx
src/shared/translations/nl.json

https://meemoo.atlassian.net/browse/AVO-2010

fix(avo-2010): add custom warning for teacher visiting assignment link

---

src/assignment/components/AssignmentPupilPreview.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentResponseEdit/AssignmentResponseEdit.tsx
src/shared/translations/nl.json

https://meemoo.atlassian.net/browse/AVO-2052

fix(avo-2052): show toast message for all actions in preview mode

---

src/assignment/hooks/assignment-pupil-tabs.tsx
src/assignment/views/AssignmentResponseEdit/AssignmentResponseEdit.tsx

https://meemoo.atlassian.net/browse/AVO-2029

fix(avo-2029): only count fragments for pupil collection counter

---

src/assignment/modals/AddBlockModal.tsx
src/shared/translations/nl.json

https://meemoo.atlassian.net/browse/AVO-2036

fix(avo-2036): show different description on disabled search block

---

src/assignment/assignment.service.ts

https://meemoo.atlassian.net/browse/AVO-2050
before:
after:

fix(avo-2050): set use_custom_fields to true if description not imported

---

src/assignment/views/AssignmentOverview.tsx

https://meemoo.atlassian.net/browse/AVO-2055

fix(avo-2055): add messages when no results with filters for pupil

---

package-lock.json
package.json
src/collection/components/CollectionFragmentTitle.scss
src/collection/components/CollectionFragmentTitle.tsx

https://meemoo.atlassian.net/browse/AVO-2056
before:
after:

fix(avo-2056): override heading margin for CollectionFragmentTitle

---

src/collection/components/CollectionOrBundleEditAdmin.tsx

https://meemoo.atlassian.net/browse/AVO-2025
before:
after:

fix(avo-2025): remove assignments list from collection edit page

---

src/admin/users/components/UserDeleteModal.tsx
src/shared/translations/nl.json

https://meemoo.atlassian.net/browse/AVO-2060
before:
after:

fix(avo-2060): link to assignments from delete user content modal

---

src/assignment/assignment.const.ts
src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponseSearchTab.tsx
src/search/components/SearchFiltersAndResults.tsx
src/search/search.const.ts
src/search/search.types.ts

https://meemoo.atlassian.net/browse/AVO-1910

fix(avo-1910): limit sort options for pupil search in assignment

---

src/assignment/components/AssignmentDetailsFormEditable.tsx

https://meemoo.atlassian.net/browse/AVO-2051

fix(avo-2051): make assignment labels optional

---

src/assignment/modals/AddCollectionModal.tsx
src/assignment/modals/AddItemsModals.scss

https://meemoo.atlassian.net/browse/AVO-2046
before:
after:

bugfix AVO-2046 align collection title to radio button

---

src/assignment/views/AssignmentEdit.tsx

https://meemoo.atlassian.net/browse/AVO-2040
https://user-images.githubusercontent.com/1710840/180017885-aeabe541-946f-40fe-adc0-5818a4b64f59.mp4

fix(avo-2040): show spinner during assignment loading

---

src/assignment/views/AssignmentResponseEdit/AssignmentResponseEditPage.tsx

Show error to student when assignment deadline not yet set

fix(avo-2003): error when assignment deadline not yet set

---

src/assignment/views/AssignmentOverview.tsx
src/assignment/views/AssignmentResponses.tsx

Explicitly close delete modals

fix(avo-2073): close delete modals

---

src/assignment/hooks/assignment-content-modals.tsx

fix(avo-2071): copy trim info on import collection

---

src/assignment/views/AssignmentEdit.tsx

https://meemoo.atlassian.net/browse/AVO-2112
before:
after:

fix(avo-2112): reset changes before redirect after assignment delete

---

src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponsePupilCollectionTab.tsx
src/collection/components/CollectionOrBundleEditContent.tsx
src/collection/components/fragment/FragmentAdd.tsx
src/shared/components/ListSorter/ListSorter.tsx

https://meemoo.atlassian.net/browse/AVO-2099
for
* collection
* ![image](https://user-images.githubusercontent.com/1710840/185641862-3f1347d8-2023-4fca-bdd0-38e049bf564e.png)
* assignment create
* ![image](https://user-images.githubusercontent.com/1710840/185641968-f46136d8-167a-4c85-8521-7250cc7b1dbe.png)
* assignment edit
* ![image](https://user-images.githubusercontent.com/1710840/185642048-f1ff2945-8997-4856-86ac-f7e9823193ef.png)
* assignment response
* ![image](https://user-images.githubusercontent.com/1710840/185642077-b5751ab4-6797-47b1-94ef-95d5267b1258.png)

feat(avo-2099): add an add block button before the first block

---

package-lock.json
package.json
src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx
src/admin/items/views/ItemDetail.tsx
src/admin/users/views/UserDetail.tsx
src/item/components/ItemVideoDescription.tsx
src/shared/services/content-page-service.ts

https://meemoo.atlassian.net/browse/AVO-1722
Requires PR's:
* https://github.com/viaacode/avo2-components/pull/496
* https://github.com/viaacode/avo2-proxy/pull/483
bookmark button for logged in users:
no bookmark button for logged out users:
link to detail:

feat(avo-1722): add bookmark button inside video popup in mediaGridBlock

---

src/assignment/modals/ConfirmImportToAssignmentWithResponsesModal.tsx

https://meemoo.atlassian.net/browse/AVO-2117

fix(avo-2117): add space between 2 translations

---

src/collection/collection.helpers.tsx
src/collection/collection.service.ts
src/shared/translations/nl.json

https://meemoo.atlassian.net/browse/AVO-2154

fix(avo-2154): rename lom_typical_age_range before saving collection

---

src/collection/views/CollectionDetail.tsx

https://meemoo.atlassian.net/browse/AVO-2157
before:
after:

fix(avo-2157): fix collections view count on the collections detail page

---

src/collection/collection.service.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.gql.ts

https://meemoo.atlassian.net/browse/AVO-2125
Requires https://github.com/viaacode/avo2-proxy/pull/497

feat(avo-2125): add hard delete for collection bookmarks

---

src/content-page/views/ContentPage.tsx

https://meemoo.atlassian.net/browse/AVO-2134

feat(avo-2134): add scroll reset on new page

---

src/settings/views/Settings.tsx

https://meemoo.atlassian.net/browse/AVO-1833

fix(avo-1833): show link screen for pupils

---

package-lock.json
package.json
src/authentication/helpers/redirects.ts
src/collection/components/modals/AutoplayCollectionModal.tsx
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.scss
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx

https://meemoo.atlassian.net/browse/AVO-1724
* show active video with background color
* fix scrubber handle to be centered on the progress bar
* set cuepoints for playlist items in collection
* on cue end event, pause video and set player to cue start point when not in playlist mode
* use renderPlaylistTile instead of having the avo2-components choose media-card automatically (so it can also be used in react-components)
https://user-images.githubusercontent.com/1710840/191941013-b51dbe72-30d0-4fd5-b07c-230bfda00efb.mp4

fix(avo-1724): fix cuepoints in playlist + show active video

---

src/collection/components/modals/CutFragmentModal.tsx
src/item/components/modals/AddToAssignmentModal.tsx
src/item/components/modals/AddToCollectionModal.scss
src/item/components/modals/AddToCollectionModal.tsx
src/shared/components/TimeCropControls/TimeCropControls.scss
src/shared/components/TimeCropControls/TimeCropControls.tsx

https://meemoo.atlassian.net/browse/AVO-2160
This avoid implementing this logic 3 times (reducing the codebase by 145 lines of code)
https://user-images.githubusercontent.com/1710840/192227141-190d57af-e1fe-4d1a-8f9d-9b92ba2fc892.mp4

fix(avo-2160): move time crop controls to separate components

---

src/admin/items/items.service.ts
src/assignment/views/AssignmentResponses.tsx
src/error/views/ErrorView.tsx
src/shared/components/LoadingErrorLoadedComponent/LoadingErrorLoadedComponent.tsx

https://meemoo.atlassian.net/browse/AVO-1946
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/500
3 items:
* item 1: depublish without a reason
* ![image](https://user-images.githubusercontent.com/1710840/192313828-2e7e9eec-4ede-444d-93ba-a96ebc8d0b18.png)
* item 2: depublish with a reason
* ![image](https://user-images.githubusercontent.com/1710840/192313897-dfd561da-bf6e-4e56-96de-c3fe92eea9f7.png)
* item 3: depublish with a replacement
* ![image](https://user-images.githubusercontent.com/1710840/192313930-3f5ddc58-7bd5-4bf2-950b-8340b726ccf2.png)
a collection with 3 items before depublishing the items:
an assignment with the 3 items before depublishing the items
item 1 after depublish without a reason:
item 2 after depublish with a reason:
item 3 after depublish with a …

fix(avo-1946): show pancarte or replacement item for unpublished items

---

src/admin/users/user.const.ts

https://meemoo.atlassian.net/browse/AVO-1726

feat(avo-1726): add education level to filter: Andere

---

src/admin/users/views/UserOverview.tsx
src/search/views/Search.tsx
src/shared/components/ACMIDMNudgeModal/ACMIDMNudgeModal.tsx

https://meemoo.atlassian.net/browse/AVO-2136
Otherwise it opens right after you break the link with vlaamse overheid idp
https://user-images.githubusercontent.com/1710840/193238183-df64e5a2-b5a6-439a-a043-4eff0ade1356.mp4

fix(avo-2136): hide nudging modal on link accounts screen

---

src/collection/components/CollectionOrBundleOverview.tsx

https://meemoo.atlassian.net/browse/AVO-2125
there were 2 locations that deleted collections. One was a deprecated way of deleting collections using the useMutation hook from apollo
https://user-images.githubusercontent.com/1710840/193545485-4e181683-ed68-420c-a725-a23e4bc06f75.mp4

fix(avo-2125): also delete bookmark for deleted collections

---

src/admin/users/user.service.ts
src/shared/helpers/formatters/date.ts

https://meemoo.atlassian.net/browse/AVO-1779
also deprecate moment js function
proxy companion PR: https://github.com/viaacode/avo2-proxy/pull/516

fix(avo-1779): send direct temp access mail if from date <= now

---

src/collection/components/modals/CutFragmentModal.scss
src/collection/components/modals/CutFragmentModal.tsx
src/item/components/modals/AddToAssignmentModal.scss
src/item/components/modals/AddToAssignmentModal.tsx
src/item/components/modals/AddToCollectionModal.scss
src/item/components/modals/AddToCollectionModal.tsx
src/shared/helpers/set-modal-video-seek-time.ts

https://meemoo.atlassian.net/browse/AVO-2227

fix(avo-2227): set seek time when fragment cut start is updated

---

package-lock.json
package.json

https://meemoo.atlassian.net/browse/AVO-1730
https://github.com/viaacode/avo2-components/compare/3e2c78aaa1c23c816bb433cc60ebcd5f233a7d74...d64d1d24070acc41958f67f37b47173216f14564

fix(avo-1730): bump components

---

src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/collection/components/modals/DeleteCollectionModal.tsx
src/collection/views/CollectionDetail.tsx

https://meemoo.atlassian.net/browse/AVO-2236
http://localhost:8080/collecties/dad31340-43c5-46aa-a742-c88e8e6b1d4c
https://hasura-graphql-qas-avo.private.cloud.meemoo.be/console/data/default/schema/app/tables/collections/browse?filter=id%3B%24eq%3Bdad31340-43c5-46aa-a742-c88e8e6b1d4c

feat(avo-2236): remove assignment check

---

src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.scss

https://meemoo.atlassian.net/browse/AVO-2182

fix(avo-2182): expand selector

---

src/admin/items/items.gql.ts
src/collection/collection.helpers.tsx

https://meemoo.atlassian.net/browse/AVO-2181?focusedCommentId=35540
Requires https://github.com/viaacode/avo2-proxy/pull/530

feat(avo-2181): remove excess bookmarks

---

src/item/components/ItemVideoDescription.scss

https://meemoo.atlassian.net/browse/AVO-2219?focusedCommentId=35412

fix(avo-2219): adjust flex layout in modal

---

src/App.scss

https://meemoo.atlassian.net/browse/AVO-2246

fix(avo-2246): adjust modal scaling

---

src/assignment/components/blocks/AssignmentBlockEditItem.tsx
src/collection/components/CollectionFragmentFlowPlayer.tsx
src/collection/components/fragment/FragmentDetail.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/collection/components/modals/CutFragmentModal.tsx
src/item/components/ItemVideoDescription.tsx
src/item/components/modals/AddToAssignmentModal.tsx
src/item/components/modals/AddToCollectionModal.tsx
src/item/views/ItemDetail.tsx
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx

https://meemoo.atlassian.net/browse/AVO-2239

fix(AVO-2239): video now plays when changing starttime

---

package-lock.json
package.json

https://meemoo.atlassian.net/browse/AVO-2238
only a few lines of code needed to be removed in the components repo:
https://github.com/viaacode/avo2-components/commit/d6728aec701e28403ea8d37727b2f94543d9da19

fix(avo-2238): allow playback outside of cuepoints

---

src/App.scss
src/styles/components/_media-card-list.scss

https://meemoo.atlassian.net/browse/AVO-2246

fix(avo-2246): improve responsivity

---

src/admin/items/items.gql.ts
src/admin/items/items.service.ts

https://meemoo.atlassian.net/browse/AVO-2181?focusedCommentId=35843
Requires https://github.com/viaacode/avo2-proxy/pull/537

fix(avo-2181): change EITHER condition to BOTH

---

src/shared/services/assignment-labels-service/assignment-labels-service.gql.ts
src/shared/services/assignment-labels-service/assignment-labels-service.ts

https://meemoo.atlassian.net/browse/AVO-2256
Requires https://github.com/viaacode/avo2-proxy/pull/538

fix(avo-2256): transform where clause

---

src/assignment/components/modals/ManageAssignmentLabels.scss

https://meemoo.atlassian.net/browse/AVO-2257

fix(avo-2257): set height for color selector

---

src/shared/services/player-ticket-service.ts

https://meemoo.atlassian.net/browse/AVO-2192
Requires proxy and admin-core PR's
* https://github.com/viaacode/react-admin-core-module/pull/67
* https://github.com/viaacode/avo2-proxy/pull/551

feat(avo-2192): use ticket service from admin-core routes

---

src/search/components/SearchFilterControls.tsx
src/search/components/SearchFiltersAndResults.tsx

feat(AVO-2333): fix lag on input when typing

---

src/admin/content-page-labels/views/ContentPageLabelEdit.tsx

fix(content-page-labels): fix edit and insert screens

---

src/admin/shared/hoc/with-admin-core-config.const.tsx

fix(avo-2363): the default content page width should be 1300px

---

src/admin/shared/layouts/AdminLayout/AdminLayout.scss

https://meemoo.atlassian.net/browse/AVO-2365
before:
after:

fix(avo-2365): fix admin layout style leakes

---

package-lock.json
package.json
src/admin/translations/views/index.ts
src/admin/user-groups/views/index.ts
src/admin/users/views/index.ts
src/styles/components/react-components/_flowplayer.scss
src/styles/components/react-components/_index.scss

https://meemoo.atlassian.net/browse/AVO-2369
Also contains changes from react-components v2.22.2 (copied from avo2-components)
https://github.com/viaacode/react-components/commit/2927eece6c1e646d6421196fe41c05e2169b179f
before:
after:

fix(avo-2369): fix flowplayer playlist

---

src/admin/translations/views/TranslationsOverviewPage.tsx

https://meemoo.atlassian.net/browse/ARC-1360
before:
after:

fix(avo-1360): remove underlay, modal component already provides it

---

src/shared/components/BlockList/blocks/AssignmentBlockTypeSearch.tsx

https://meemoo.atlassian.net/browse/AVO-2372
page: http://localhost:8080/werkruimte/opdrachten/maak
add a search block and click the "bekijk als leerling"
before:
after:

fix(avo-2372): add import for styles for search block in assignments

---

src/admin/shared/hoc/with-admin-core-config.const.tsx
src/admin/shared/hoc/with-admin-core-config.tsx

https://meemoo.atlassian.net/browse/AVO-2393
requires admin-core PR: https://github.com/viaacode/react-admin-core-module/pull/112

fix(avo-2393): fix author name in admin-config

---

src/collection/components/CollectionOrBundleOverview.tsx

https://meemoo.atlassian.net/browse/AVO-2409
page: http://localhost:8080/werkruimte/collecties
after:

fix(avo-2409): do not parse collection uuid's as numbers

---

src/assignment/assignment.service.ts
src/assignment/helpers/is-item-with-meta.ts

https://meemoo.atlassian.net/browse/AVO-2377
page: http://localhost:8080/werkruimte/opdrachten/c68fc081-bc91-42fa-a8be-ef92ca8f404c/antwoorden
before:
after:

fix(avo-2377): fetch pupil collection response objects fragment metaData

---

src/styles/generic/_global.scss

https://meemoo.atlassian.net/browse/AVO-2405
page: https://onderwijs-qas.hetarchief.be/vervolledig-profiel
before:
after:

fix(avo-2405): add padding to complete profile page for dropdown

---

package-lock.json
package.json
src/assignment/assignment.service.ts

https://meemoo.atlassian.net/browse/AVO-2444
currently all assignments that are not set to BOUW or ZOEK types are set to undefined
this should be KIJK instead

ARC-2444 Set KIJK type correctly on assignments

---

src/pupil-collection/pupil-collection.service.ts

https://meemoo.atlassian.net/browse/AVO-2494

bugfix(avo-2494): remove original title/desc before save pupil collection

---

src/admin/assignments/views/AssignmentsOverviewAdmin.tsx
src/admin/pupil-collection/views/PupilCollectionsOverview.tsx
src/assignment/helpers/links.ts
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentOverview.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/collection/views/CollectionDetail.tsx
src/item/views/ItemDetail.tsx

Ticket: https://meemoo.atlassian.net/browse/AVO-2609

feat(avo-2609): change edit assignment links to detailpage

---

src/assignment/views/AssignmentDetail.tsx
src/shared/services/related-items-service.ts
src/shared/translations/nl.json

Ticket: https://meemoo.atlassian.net/browse/AVO-2610

feat(avo-2610): show related assignments

---

src/collection/collection.service.ts
src/collection/queries/get-collections-by-owner.graphql
src/shared/generated/graphql-db-types.ts

Ticket: https://meemoo.atlassian.net/browse/AVO-2511

feat(avo-2511): change collection to new overview table

---

scripts/extract-and-replace-translations.ts
src/assignment/components/AssignmentActions.tsx
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/collection/collection.helpers.tsx

- Delete loms and contributors keys from assignment object before updating, fix typing issue
- Add conditional render to publish en share button

fix: general fixes

---

src/assignment/modals/AddCollectionModal.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleOverview.tsx
src/shared/translations/nl.json

Ticket: https://meemoo.atlassian.net/browse/AVO-2620

feat(avo-2620): added share type filter on collection overview page

---

src/assignment/assignment.service.ts
src/assignment/components/AssignmentActions.tsx
src/assignment/helpers/delete-assignment.ts
src/assignment/queries/get-assignments-by-owner.graphql
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentOverview.tsx
src/shared/generated/graphql-db-types.ts
src/shared/translations/nl.json

Ticket: https://meemoo.atlassian.net/browse/AVO-2675
(+ bugfix when trying to create a new assignment, this error was shown:
)

feat(avo-2675): show appropriate message when deleting assignment + create assignment bugfix

---

package-lock.json
package.json
src/assignment/assignment.helper.tsx
src/assignment/assignment.service.ts
src/assignment/views/AssignmentDetail.tsx
src/authentication/helpers/permission-service.ts
src/shared/translations/nl.json

https://meemoo.atlassian.net/browse/AVO-2726
backend PR: https://github.com/viaacode/avo2-proxy/pull/640
* don't load related items if you don't have access to the assignment
* fix error around keys not being added for lom values rendering
* add inviteToken query param to view request to backend
* cleanup permission checking for contributors in the permission service

fix(avo-2726): fix key issue, add invitetoken to view request, cleanup

---

package.json
src/admin/assignments/views/AssignmentsOverviewAdmin.scss
src/admin/assignments/views/AssignmentsOverviewAdmin.tsx
src/assignment/assignment.service.ts
src/assignment/queries/get-assignments-by-response-owner-id.graphql
src/assignment/queries/getAssignmentWithResponse.graphql
src/assignment/queries/getAssignmentsAdminOverview.graphql
src/assignment/queries/getAssignmentsByOwnerOrContributor.graphql
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEditAdmin.tsx
src/collection/queries/get-quality-labels.graphql
src/shared/generated/graphql-db-types.ts
src/shared/hooks/useCollectionQualityLabels.ts
src/shared/services/quality-labels.service.ts

https://meemoo.atlassian.net/browse/AVO-2666
required backend PR: https://github.com/viaacode/avo2-proxy/pull/650
when you click the link:
When all selected assignments are being edited:

feat(avo-2666): add warning before bulk actions for assignments admin

---

src/assignment/assignment.const.ts
src/assignment/assignment.service.ts
src/assignment/helpers/delete-assignment.ts
src/assignment/hooks/assignment-form.tsx
src/assignment/views/AssignmentResponses.tsx
src/shared/helpers/block-types-to-lom-learning-resource-type.ts

https://meemoo.atlassian.net/browse/AVO-2635

feat(avo-2635): replace assignment type with lom_learning_resource_type

---

src/assignment/views/AssignmentEdit.tsx
src/collection/components/CollectionOrBundleEdit.tsx

[AVO-2709](https://meemoo.atlassian.net/browse/AVO-2709)
[AVO-2710](https://meemoo.atlassian.net/browse/AVO-2710)
[AVO-2709]: https://meemoo.atlassian.net/browse/AVO-2709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AVO-2710]: https://meemoo.atlassian.net/browse/AVO-2710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(avo-2710): action on failed edit status requests

---

src/assignment/views/AssignmentEdit.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/shared/components/InActivityWarningModal/InActivityWarningModal.tsx

[AVO-2652](https://meemoo.atlassian.net/browse/AVO-2652)
[AVO-2661](https://meemoo.atlassian.net/browse/AVO-2661)
[AVO-2652]: https://meemoo.atlassian.net/browse/AVO-2652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AVO-2661]: https://meemoo.atlassian.net/browse/AVO-2661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(avo-2652): Add an attempt to request edit status and redirect in case of fail with toast message

---

src/assignment/assignment.service.ts
src/assignment/components/AssignmentActions.tsx

[AVO-2704](https://meemoo.atlassian.net/browse/AVO-2704)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/661)
[AVO-2704]: https://meemoo.atlassian.net/browse/AVO-2704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2704): fix transfer ownership

---

src/assignment/hooks/assignment-content-modals.tsx
src/authentication/helpers/permission-service.ts
src/authentication/helpers/redirects.ts
src/bundle/views/BundleDetail.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/collection/components/modals/AddToBundleModal.tsx
src/collection/views/CollectionDetail.tsx
src/item/components/modals/AddToCollectionModal.tsx
src/quick-lane/quick-lane.service.ts

proxy PR: https://github.com/viaacode/avo2-proxy/pull/662

fix(share-collection): fix issues with the share collection flow

---

src/shared/generated/graphql-db-types.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.types.ts
src/shared/services/bookmarks-views-plays-service/queries/get-bookmark-statuses.graphql

[AVO-2538](https://meemoo.atlassian.net/browse/AVO-2538)
Before: 
After:
[AVO-2538]: https://meemoo.atlassian.net/browse/AVO-2538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2538): display bookmarked assignments in bookmark overview

---

src/shared/components/HeaderOwnerAndContributors/HeaderOwnerAndContributors.tsx

[AVO-2608](https://meemoo.atlassian.net/browse/AVO-2608)
[AVO-2608]: https://meemoo.atlassian.net/browse/AVO-2608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2608): owner and contributors spacing

---

src/assignment/views/AssignmentEdit.tsx
src/collection/components/CollectionOrBundleEdit.tsx

[AVO-2760](https://meemoo.atlassian.net/browse/AVO-2760)
[AVO-2760]: https://meemoo.atlassian.net/browse/AVO-2760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2760): fix error screen on assignment and collection load

---

src/assignment/assignment.service.ts

[AVO-2703](https://meemoo.atlassian.net/browse/AVO-2703)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/664)
[AVO-2703]: https://meemoo.atlassian.net/browse/AVO-2703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2703): fix duplicate public assignment

---

src/shared/components/ShareWithColleagues/ShareWithColleagues.scss

[AVO-2597](https://meemoo.atlassian.net/browse/AVO-2597)
Before:
After:
[AVO-2597]: https://meemoo.atlassian.net/browse/AVO-2597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(2597): adjust styles of share with colleague component

---

src/assignment/views/AssignmentDetail.tsx

[AVO-2650](https://meemoo.atlassian.net/browse/AVO-2650)
[AVO-2650]: https://meemoo.atlassian.net/browse/AVO-2650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2650): Add to is being edited check

---

src/shared/generated/graphql-db-types.ts
src/workspace/queries/get-workspace-tab-counts.graphql
src/workspace/views/Workspace.tsx

[AVO-2763](https://meemoo.atlassian.net/browse/AVO-2763)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/666)
Before:
After:
[AVO-2763]: https://meemoo.atlassian.net/browse/AVO-2763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2763): fix tab counts issue

---

src/assignment/assignment.service.ts

[AVO-2762](https://meemoo.atlassian.net/browse/AVO-2762)
Before:
After: 
[AVO-2762]: https://meemoo.atlassian.net/browse/AVO-2762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2762): fix students assignments issue

---

src/assignment/queries/get-assignments-by-response-owner-id.graphql
src/shared/generated/graphql-db-types.ts

[AVO-2624](https://meemoo.atlassian.net/browse/AVO-2624)
[Avo2-proxy](https://github.com/viaacode/avo2-proxy/pull/671)
[AVO-2624]: https://meemoo.atlassian.net/browse/AVO-2624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2624): add is public to get assignments by response owner id

---

src/shared/components/LomFieldsInput/LomFieldsInput.helpers.ts
src/shared/components/LomFieldsInput/LomFieldsInput.tsx

[AVO-2753](https://meemoo.atlassian.net/browse/AVO-2753)
Before:
After:
[AVO-2753]: https://meemoo.atlassian.net/browse/AVO-2753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2753): merge education degrees and levels

---

src/assignment/assignment.helper.tsx
src/collection/collection.helpers.tsx
src/collection/components/CollectionOrBundleEditMetaData.tsx
src/settings/components/Profile.tsx

[AVO-2686](https://meemoo.atlassian.net/browse/AVO-2686)
[AVO-2693](https://meemoo.atlassian.net/browse/AVO-2693)
[Avo2-typings PR](https://github.com/viaacode/avo2-typings/pull/130)
[AVO-2686]: https://meemoo.atlassian.net/browse/AVO-2686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AVO-2693]: https://meemoo.atlassian.net/browse/AVO-2693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2686): add themes to publication details

---

src/settings/components/Profile.scss
src/settings/components/Profile.tsx
src/shared/components/CommonMetaData/CommonMetaData.tsx
src/shared/components/LomFieldsInput/LomFieldsInput.tsx

fix(profile): make education levels and degrees readonly on profile page

---

src/admin/shared/components/SubjectsBeingEditedWarningModal/SubjectsBeingEditedWarningModal.tsx
src/assignment/views/AssignmentDetail.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/views/CollectionDetail.tsx
src/shared/components/QuickLaneModal/QuickLaneModalPublicationTab.tsx

https://meemoo.atlassian.net/browse/AVO-2766
proxy PR: https://github.com/viaacode/avo2-proxy/pull/676
before:
after:

fix(avo-2766): fix issues with the inactivity modal forced exit

---

src/assignment/views/AssignmentOverview.tsx

https://meemoo.atlassian.net/browse/AVO-2775
before:
after:

fix(avo-2775): hide public/shared status on mobile assignments overview

---

src/assignment/assignment.helper.tsx
src/assignment/views/AssignmentEdit.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/shared/components/QuickLaneModal/QuickLaneModalPublicationTab.tsx

[AVO-2781](https://meemoo.atlassian.net/browse/AVO-2781)
[AVO-2781]: https://meemoo.atlassian.net/browse/AVO-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2781): move update lom functionality to collection service, add publish validation check to assignment update

---

src/search/components/SearchResultItem.tsx

[AVO-2636](https://meemoo.atlassian.net/browse/AVO-2636)
Before:
After:
[AVO-2636]: https://meemoo.atlassian.net/browse/AVO-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2636): fix is item check on search result

---

src/assignment/assignment.service.ts

[AVO-2703](https://meemoo.atlassian.net/browse/AVO-2703)
Before:
After:
[AVO-2703]: https://meemoo.atlassian.net/browse/AVO-2703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2703): fix assignment labels being duplicated

---

src/assignment/views/AssignmentOverview.tsx

[AVO-2784](https://meemoo.atlassian.net/browse/AVO-2784)
[AVO-2784]: https://meemoo.atlassian.net/browse/AVO-2784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2781): fix student overview assignments redirecting to wrong detail page

---

src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentEdit.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/helpers/collection-share-with-collegue-handlers.ts
src/search/store/actions.ts

https://meemoo.atlassian.net/browse/AVO-2793
also fixed getting status code using elvis operators everywhere

fix(avo-2793): transfer owner of collection using profile id

---

src/assignment/views/AssignmentDetail.tsx

[AVO-2538](https://meemoo.atlassian.net/browse/AVO-2538)
[AVO-2538]: https://meemoo.atlassian.net/browse/AVO-2538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2538): Fix bookmarking assignments

---

src/shared/components/ShareWithColleagues/ShareWithColleagues.tsx

[AVO-2789](https://meemoo.atlassian.net/browse/AVO-2789)
[AVO-2789]: https://meemoo.atlassian.net/browse/AVO-2789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(vo-2789): adjust can delete check

---

src/shared/components/MultiThemeSelectDropdown/MultiThemeSelectDropdown.tsx

[AVO-2791](https://meemoo.atlassian.net/browse/AVO-2791)
[AVO-2791]: https://meemoo.atlassian.net/browse/AVO-2791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2791): Replace placeholder with null if undefined

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

https://meemoo.atlassian.net/browse/AVO-2671

fix(avo-2671): link to collection/bundle detail instead of edit page

---

src/assignment/views/AssignmentEdit.tsx

[AVO-2792](https://meemoo.atlassian.net/browse/AVO-2792)
[AVO-2792]: https://meemoo.atlassian.net/browse/AVO-2792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2792): replace existing check with permission service check and refactor

---

src/collection/components/CollectionOrBundleOverview.tsx

https://meemoo.atlassian.net/browse/AVO-2825
before:
after:

fix(avo-2825): fix permissions for delete me from collection button

---

src/assignment/hooks/assignment-pupil-tabs.tsx

[AVO-2808](https://meemoo.atlassian.net/browse/AVO-2808)
Before:
After:
[AVO-2808]: https://meemoo.atlassian.net/browse/AVO-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2808): fix check for bouw or zoek assignment lom learning resource type

---

src/assignment/views/AssignmentOverview.tsx

[AVO-2835](https://meemoo.atlassian.net/browse/AVO-2835)
[AVO-2835]: https://meemoo.atlassian.net/browse/AVO-2835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2835): add is array check and replace type any

---

src/assignment/components/AssignmentTitle.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleTitle.tsx

[AVO-2828](https://meemoo.atlassian.net/browse/AVO-2828)
[AVO-2828]: https://meemoo.atlassian.net/browse/AVO-2828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2828): add edit title on cancel to reset to initial value

---

src/shared/components/HeaderOwnerAndContributors/HeaderOwnerAndContributors.tsx

[AVO-2848](https://meemoo.atlassian.net/browse/AVO-2848)
Before:
After:
[AVO-2848]: https://meemoo.atlassian.net/browse/AVO-2848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2848): fix organisation missing from owner

---

src/assignment/views/AssignmentOverview.tsx
src/collection/components/CollectionOrBundleOverview.tsx

[AVO-2826](https://meemoo.atlassian.net/browse/AVO-2826)
Before:
After:
[AVO-2826]: https://meemoo.atlassian.net/browse/AVO-2826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2826): fix share status contributors list by removing null values from list

---

src/assignment/components/AssignmentActions.tsx
src/assignment/views/AssignmentEdit.tsx

[AVO-2831](https://meemoo.atlassian.net/browse/AVO-2831)
[AVO-2831]: https://meemoo.atlassian.net/browse/AVO-2831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2831): fix publish icon on assignment edit page by adding extra dependency in use memo

---

src/assignment/views/AssignmentDetail.tsx

[AVO-2814](https://meemoo.atlassian.net/browse/AVO-2814)
[AVO-2814]: https://meemoo.atlassian.net/browse/AVO-2814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2814): fix refresh on assignment invite accept

---

src/assignment/views/AssignmentDetail.tsx

[AVO-2829](https://meemoo.atlassian.net/browse/AVO-2829)
[AVO-2829]: https://meemoo.atlassian.net/browse/AVO-2829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2829): fix share with pupil error links

---

src/assignment/assignment.helper.tsx

[AVO-2830](https://meemoo.atlassian.net/browse/AVO-2830)
Before:
After:
[AVO-2830]: https://meemoo.atlassian.net/browse/AVO-2830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2830): fix publish validation

---

src/shared/generated/graphql-db-types.ts
src/workspace/queries/get-workspace-tab-counts.graphql
src/workspace/views/Workspace.tsx

[AVO-2816](https://meemoo.atlassian.net/browse/AVO-2816)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/684)
Before:
After:
[AVO-2816]: https://meemoo.atlassian.net/browse/AVO-2816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2816): fix bookmark count by add assignment bookmark aggregate count to tab count sum

---

src/assignment/components/AssignmentActions.tsx
src/assignment/components/AssignmentHeading.scss
src/assignment/views/AssignmentEdit.tsx

[AVO-2854](https://meemoo.atlassian.net/browse/AVO-2854)
Before:
After:
[AVO-2854]: https://meemoo.atlassian.net/browse/AVO-2854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2854): add view button on assignment edit page

---

src/assignment/components/DeleteAssignmentButton.tsx
src/assignment/helpers/delete-assignment.ts
src/assignment/views/AssignmentDetail.tsx
src/assignment/views/AssignmentOverview.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/collection/helpers/delete-collection.ts
src/collection/views/CollectionDetail.tsx

[AVO-2839](https://meemoo.atlassian.net/browse/AVO-2839)
[AVO-2840](https://meemoo.atlassian.net/browse/AVO-2840)
[AVO-2842](https://meemoo.atlassian.net/browse/AVO-2842)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/686)
[AVO-2839]: https://meemoo.atlassian.net/browse/AVO-2839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AVO-2840]: https://meemoo.atlassian.net/browse/AVO-2840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AVO-2842]: https://meemoo.atlassian.net/browse/AVO-2842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2839): fix remove me from assignment/collection and visibilty and labels of remove buttons

---

src/shared/components/ShareDropdown/ShareDropdown.tsx
src/shared/components/ShareModal/ShareModal.tsx
src/shared/components/ShareWithColleagues/ShareWithColleagues.tsx

[AVO-2857](https://meemoo.atlassian.net/browse/AVO-2857)
[AVO-2857]: https://meemoo.atlassian.net/browse/AVO-2857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2857): fix pending invites not showing in contributor list

---

src/search/components/SearchResultItem.tsx

Ticket: https://meemoo.atlassian.net/browse/AVO-3020

fix(avo-3020): prioritize company avatar

---

src/assignment/views/AssignmentDetail.tsx
src/shared/components/ShareDropdown/ShareDropdown.tsx

Ticket: https://meemoo.atlassian.net/browse/AVO-3004

fix(arc-3004): disable shareButton when expired

---

src/assignment/views/AssignmentOverview.tsx
src/bundle/bundle.types.tsx
src/bundle/views/BundleDetail.tsx

https://meemoo.atlassian.net/browse/AVO-3005

feat(AVO-3005): use enum for assignment and bundle actions everywhere

---

src/item/views/ItemDetail.scss

Ticket: https://meemoo.atlassian.net/browse/AVO-2719

fix(avo-2719): align buttons right

---

package-lock.json
package.json
src/admin/collectionsOrBundles/helpers/collection-filters.ts
src/admin/collectionsOrBundles/helpers/render-collection-columns.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleEditQualityCheck.tsx
src/collection/helpers/ok-nok-parser.ts

https://meemoo.atlassian.net/browse/AVO-2495
requires proxy pr:
* https://github.com/viaacode/avo2-proxy/pull/695

fix(AVO-2495): fix quality control filters in collections overview

---

src/collection/collection.service.ts
src/item/components/modals/AddToCollectionModal.tsx

Ticket: https://meemoo.atlassian.net/browse/AVO-3041

fix(avo-3041): fetch collections by contributor aswell

---

src/shared/components/InActivityWarningModal/InActivityWarningModal.tsx

Before:
After: 
Ticket: https://meemoo.atlassian.net/browse/AVO-2846

fix(avo-2846): show timer in tab title

---

src/collection/collection.service.ts
src/collection/components/modals/AddToBundleModal.tsx
src/item/components/modals/AddToCollectionModal.tsx

https://meemoo.atlassian.net/browse/AVO-3014
take in account all blocks, not only newly added blocks
https://github.com/viaacode/avo2-client/assets/1710840/f2a391ee-67cb-49b4-a5d2-59b6e41113cc

fix(AVO-3014): set block positions in collections and bundles correctly

---

src/assignment/helpers/insert-at-position.ts
src/assignment/modals/AddCollectionModal.tsx

https://meemoo.atlassian.net/browse/AVO-2970
https://github.com/viaacode/avo2-client/assets/1710840/07151534-225f-4980-93ea-6ff77188631a

fix(AVO-2970): correctly add collection blocks to assignment with blocks

---

src/admin/assignments/assignments.types.ts
src/admin/assignments/views/AssignmentsOverviewAdmin.tsx
src/assignment/queries/getAssignmentsAdminOverview.graphql

Ticket: https://meemoo.atlassian.net/browse/AVO-2738

fix(avo-2738): fix query

---

src/collection/collection.types.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/collection/views/CollectionDetail.tsx

https://meemoo.atlassian.net/browse/AVO-2934
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/701
https://github.com/viaacode/avo2-client/assets/1710840/90ad0683-c0c0-4517-897c-c829766b9d00

fix(AVO-2934): fix delete buttons on edit collection page

---

src/collection/collection.helpers.tsx

https://meemoo.atlassian.net/browse/AVO-2464
https://github.com/viaacode/avo2-client/assets/1710840/a22a64ab-e238-4111-9284-99dca3a8a342

fix(AVO-2464): omit more fields for before updating the updated_at date

---

src/item/views/ItemDetail.scss
src/item/views/ItemDetail.tsx
src/shared/translations/nl.json

Ticket: https://meemoo.atlassian.net/browse/AVO-285

feat(avo-285): add edit item button itemDetail page

---

src/assignment/modals/PublishAssignmentModal.tsx

Ticket: https://meemoo.atlassian.net/browse/AVO-2990

fix(avo-2990): clear validation error on cancel

---

src/admin/users/views/UserEditPage.tsx

Ticket: https://meemoo.atlassian.net/browse/AVO-2552

feat(avo-2552): disable name fields in admin UserEditPage

---

src/assignment/views/AssignmentDetail.tsx
src/shared/generated/graphql-db-operations.ts
src/shared/generated/graphql-db-react-query.ts
src/shared/generated/graphql-db-types.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.const.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.ts
src/shared/services/bookmarks-views-plays-service/queries/getAssignmentViewCount.graphql
src/shared/services/bookmarks-views-plays-service/queries/getMultipleAssignmentViewCounts.graphql
src/shared/services/bookmarks-views-plays-service/queries/incrementAssignmentViews.graphql

requires proxy pr: https://github.com/viaacode/avo2-proxy/pull/709
Ticket: https://meemoo.atlassian.net/browse/AVO-3035

fix(avo-3035): show view and bookmark count assignment

---

src/settings/components/Profile.tsx
vite.config.js

https://meemoo.atlassian.net/browse/AVO-3073

fix(AVO-3073): remove globalthis replacement during vite build

---

src/settings/components/Profile.tsx
src/shared/components/LomFieldsInput/LomFieldsInput.tsx
src/shared/components/LomInfoField/LomInfoField.tsx

https://meemoo.atlassian.net/browse/AVO-2881
before:
after:

feat(AVO-2881): allow users to change their education degree

---

src/workspace/workspace.routes.tsx

https://meemoo.atlassian.net/browse/AVO-3087?filter=10159

feat(AVO-3087): add redirect for legacy assignment urls

---

package-lock.json
package.json
src/assignment/components/AssignmentTitle.tsx

https://meemoo.atlassian.net/browse/AVO-2827

fix(AVO-2827): add maxLength to assignment title

---

package-lock.json
package.json

Described in https://github.com/vercel/turbo/issues/1769

fix: add missing devDependency for apple CPU's

---

src/admin/items/helpers/index.ts
src/admin/items/helpers/map-item-used-by-to-quick-lane.ts
src/admin/items/items.types.ts
src/admin/items/views/ItemDetail.tsx
src/shared/components/QuickLaneFilterTableCell/QuickLaneFilterTableCell.tsx
src/workspace/views/QuickLaneOverview.tsx

https://meemoo.atlassian.net/browse/AVO-3093

feat(AVO-3093): use existing cell for quicklane urls, add mapper

---

.eslintrc.js
package-lock.json
package.json
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx

https://meemoo.atlassian.net/browse/AVO-2394
includes changes in react-components: https://github.com/viaacode/react-components/commit/1ada5e35599d44e273bbabecb10a47c4a44b3d4a
https://github.com/viaacode/avo2-client/assets/1710840/036332f0-9602-4b31-a263-dec7040bae7c

fix(AVO-2394): fix audio playback + stricter eslint react hook checks

---

src/workspace/workspace.routes.tsx

https://meemoo.atlassian.net/browse/AVO-3087

fix(AVO-3087): keep query params when redirecting to new assignments url

---

src/admin/content-page/views/ContentPage.scss
src/admin/shared/components/Sidebar/Sidebar.scss
src/admin/shared/components/Sidebar/Sidebar.test.tsx
src/admin/shared/components/Sidebar/Sidebar.tsx

https://meemoo.atlassian.net/browse/AVO-3106

feat(AVO-3106): avoid pseudo colors, add encapsulation

---

src/admin/shared/components/ContentPicker/ContentPicker.tsx
src/admin/shared/components/ContentPicker/helpers/parse-picker.ts

https://meemoo.atlassian.net/browse/AVO-3113

bugfix(AVO-3113): remove dead code

---

src/shared/helpers/files.ts

https://meemoo.atlassian.net/browse/AVO-3138
before:
after:

fix(AVO-3138): show webp images in file upload preview

---

src/shared/components/ShareWithPupils/ShareWithPupils.tsx

https://meemoo.atlassian.net/browse/AVO-3131
before:
after:

fix(AVO-3131): give prio to the expired title over the incomplete title

---

src/settings/components/Email/hooks/getEmailPreferences.ts

https://meemoo.atlassian.net/browse/AVO-3149

fix(AVO-3149): disable caching for fetching email preferences

---

src/authentication/components/LoginOptions.scss
src/authentication/components/LoginOptions.tsx

- feat(AVO-3160): make log in with email option less appealing for pupils

Feature/AVO-3160 Herwerk aanmeldopties voor alle leerlingen

---

openshift/Jenkinsfile
scripts/robots-QAS.txt

https://meemoo.atlassian.net/browse/AVO-3238

feat(AVO-3238): disable search engine indexing for QAS environment

---

src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponseSearchTab.tsx

feat(AVO-3187): force educationLevel for elementary users

---

src/authentication/views/registration-flow/accept-elementary-pupil-conditions.tsx
src/shared/hooks/useDisablePictureInPicture.tsx

Note: this nearly drove me insane today

feat(AVO-3327): add hook and implement for elementary pupil conditions

---

src/workspace/views/QuickLaneOverview.tsx

https://meemoo.atlassian.net/browse/AVO-3315

fix(AVO-3315): remove edit option from quicklane overview options

---

src/assignment/views/AssignmentDetail.tsx
src/collection/views/CollectionDetail.tsx

https://meemoo.atlassian.net/browse/AVO-3281

feat(AVO-3281): set assignment title as page title

---

src/assignment/assignment.service.ts
src/item/views/ItemDetail.tsx

https://meemoo.atlassian.net/browse/AVO-3267
assignment:
collection:
add collection to assingment. result:

fix(AVO-3267): do not reorder blocks before adding them to assignment

---

src/search/components/SearchFiltersAndResults.tsx
src/search/components/SearchResults.tsx
src/search/search.types.ts

https://meemoo.atlassian.net/browse/AVO-3409

fix(AVO-3409): set item total based on api response, not total pages

---

src/embed/components/Embed.tsx

Testable codepen: https://codepen.io/ikkimausi/pen/xbGeEJL

AVO-3715: log error in case parent page is not filled in

---

src/assignment/hooks/useGetKlascementAssignmentPublishInfo.tsx
src/assignment/views/AssignmentEditMarcom.tsx
src/collection/components/CollectionOrBundleEditMarcom.tsx
src/collection/hooks/useGetKlascementPublishInfo.tsx

https://meemoo.atlassian.net/browse/AVO-3778

fix(AVO-3778): only fetch klascement publish info if permission
