package-lock.json
src/item/views/Item.tsx
src/search/views/Search.tsx
src/shared/components/CheckboxDropdown/CheckboxDropdownModal.tsx
src/shared/helpers/formatters/date.ts

* client would crash when date is null for a search result.
* steps to reproduce: search for "archief"
* fix warnings with useEffects not having all of their dependencies defined
* fix filters inside filter button when no filters are selected. empty div causes a little extra width, causes the filter buttons to wrap to 2 lines on desktop

fix: fix null date crash, fix useEffect warnings in search and item page

---

package-lock.json
package.json

This should allow you to do npm i without the need to delete the old typings first

fix: fix @viaa/types .git folder error by updating to @viaa/types@1.4.2

---

src/404/views/NotFound.tsx
src/item/views/Item.tsx
src/shared/components/DataComponent/DataQueryComponent.tsx

closes: https://district01.atlassian.net/browse/AVO2-93
Should be merged after: https://github.com/viaacode/avo2-proxy/pull/25
Je kan dit testen door in de server de response aan te passen naar lege array, of de proxy af te zetten voor een error of door altijd DELETED terug te geven
https://github.com/viaacode/avo2-proxy/pull/25/files#diff-b73a9dfcd930b3525610630d3926caebR20

fix: show item deleted instead of not found if item was soft deleted

---

src/collection/components/CollectionFragment.tsx
src/collection/helpers.ts
src/collection/views/Collection.tsx
src/collection/views/EditCollectionMetadata.tsx

fix: fragments with external_id === -1 are text blocks

---

src/App.tsx
src/my-workspace/routes.tsx
src/shared/components/Navigation/Navigation.scss
src/shared/components/Navigation/Navigation.tsx

current situation:
wrong color for active state:
when going to assignments, the workspace navigation item isn't active:
After this PR both issues are resolved:
closes: https://district01.atlassian.net/browse/AVO2-635

fix(navigation): fix active navigation item color

---

src/shared/components/FlowPlayer/FlowPlayer.tsx

fixes issue where cuepoints would throw an error when no start, end times are passed.

fix(flowplayer): only set cuepoints if fragment end time is passed

---

src/collection/components/FragmentDetail.tsx
src/collection/components/FragmentEdit.tsx
src/collection/components/modals/CollectionStillsModal.tsx
src/collection/graphql.ts
src/collection/helpers.ts

closes: https://district01.atlassian.net/browse/AVO2-663
You can use this collection to test: http://localhost:8080/collectie/29/bewerk

fix(collection-edit-meta): show one audio thumbnail for select cover

---

package.json
src/item/components/ItemVideoDescription.tsx
src/shared/components/FlowPlayer/FlowPlayer.tsx

Allows the user to jump to a video timestamp by clicking the timestamp in the video description after the video is initialized.
Good test url with timestamps: http://localhost:8080/item/8911n96442

feat(flowplayer): add seektime support

---

package-lock.json
src/assignment/services.ts
src/assignment/views/AssignmentDetail.tsx
src/collection/components/modals/ShareCollectionModal.tsx
src/collection/views/CollectionDetail.tsx
src/collection/views/CollectionEdit.tsx
src/collection/views/CollectionOverview.tsx
src/item/components/modals/FragmentAddToCollection.tsx
src/shared/services/data-service.ts
src/shared/services/event-logging-service.ts

This solves the issue where you see old data in the client after you did a mutation
Steps to see the issue in the old version:
* search for a video
* click: add to collection
* create a new collection
* add
* search for another video
* add to collection
current result: dropdown list does not contain previously created collection
expected result: dropdown list contains all collections, even the one that was created just before this action

fix(apollo-cache): clear cache after graphql mutations

---

src/assignment/views/AssignmentEdit.tsx

this bug causes a spinner to keep showing on the assignment create/edit page

fix(assignment-edit): remove race condition fetching assignment content

---

src/item/components/modals/FragmentAddToCollection.tsx

found a new bug while trying to reproduce: https://district01.atlassian.net/browse/AVO2-736
Steps:
add an item to a new collection
try adding the same item to a collection again
expected: the add to collection modal opens up, so you can choose between new or existing collection
current behavior: after adding the item to a collection the first time, the modal doesn't want to open anymore.
This issue has been fixed in this PR
The issue linked from jira was not reproducible

fix(fragment-add-collection-modal): fix issue when adding fragment twice

---

src/collection/components/FragmentEdit.tsx
src/collection/components/modals/CutFragmentModal.tsx
src/collection/helpers/validation.ts
src/collection/views/CollectionEdit.tsx
src/collection/views/CollectionEditContent.tsx

* go to a collection
* edit a fragment start time
* save the collection
* reload the page
* open the cut fragment modal
the previously set start_oc cut time should be shown
the start_oc _cut time is set to 0
This is caused by the asynchronous nature of setState functions. So try to avoid this pattern in the future:
Calling 2 functions that set the state, right after eachother, where the functions internally take a copy of the current state, and then set that state at the end of the function.
https://github.com/viaacode/avo2-client/blob/3c96c4a7dcc0098d6e6e78188620852429858379/src/collection/components/modals/CutFragmentModal.tsx#L47-L48
What happened was:
* update start_oc function is called
* it clones the currentCollection, modifies it and calls setState with the copy
* update start_end …

fix(cut-fragment-modal): start_oc never gets saved

---

src/collection/components/FragmentEdit.tsx
src/item/components/modals/FragmentAddToCollection.tsx

If we always apply the start/end time, we will never know whether a fragment was cut. Hence don't always apply the start/end. Only if cut.

fix(cut-fragment): not update start/end when no cut.

---

src/styles/components/_index.scss
src/styles/components/_toolbar.scss

fix(toolbars): fix dropdown button margin in all toolbars

---

src/authentication/helpers/get-profile-info.ts
src/authentication/helpers/redirect-to-idp.ts

This PR requires a PR on the backend to work: https://github.com/viaacode/avo2-proxy/pull/53
You can test this by logging in with any idp and the trying to click the logout button

fix(smartschool-auth): implement logout routes for multiple idps

---

src/assignment/views/AssignmentEdit.tsx
src/collection/views/CollectionEdit.tsx

this was probably lost in a previous commit
Collection edit page:
Assignment edit page:

fix(collection-edit, assignment-edit): re-add second save button

---

src/collection/views/CollectionOverview.tsx

This is by item instead of by page, so for page 2 we need to pass 20 instead of 1

fix(collections-overview): fix collection paging offset

---

src/assignment/views/AssignmentDetail.tsx
src/collection/components/fragment/FragmentDetail.tsx
src/collection/components/fragment/FragmentListDetail.tsx
src/collection/views/CollectionDetail.tsx
src/item/components/ItemVideoDescription.tsx

closes: https://district01.atlassian.net/browse/AVO2-931
items should only be clickable in collection detail for teachers (not for pupils)
items should not be clickable inside the preview of an assignment (view as pupil)

feat(fragment-detail): make fragment detail title clickable

---

src/collection/components/modals/CutFragmentModal.tsx
src/item/components/modals/AddToCollectionModal.tsx

closes: https://district01.atlassian.net/browse/AVO2-929
a video can have a duration of: "00:02:01" => 121 seconds
and the fragment can have an end set to 122 seconds
The range selector component will throw an error if you try to set the value to a value larger than the max value.
Fixed by limiting the fragmentEnd to the duration of the video

fix(coll-fragment): ensure range selector value is never > duration

---

src/item/components/ItemVideoDescription.tsx

fix(item-video-description): hide scrollbar when desc. is collasped

---

src/admin/content-block/components/ContentBlockForm/ContentBlockForm.tsx
src/admin/content-block/components/ContentBlockFormGroup/ContentBlockFormGroup.tsx

fix(content-block-form): improve location of delete button

---

src/admin/content/views/ContentEdit.tsx
src/content-page/views/ContentPage.tsx

When adding a path to a content page, we check if the path is unique by doing a query if the path already exists in the database
We should check if it already exists and if this existing content page isn't equal to the content page that is currently being edited

fix(content-edit): check if path isn't current content page path

---

src/admin/content-block/helpers/generators/heading.ts

Default center align in heading block.

fix(cb-heading): center align as default

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content-block/content-block.const.ts
src/admin/content-block/helpers/generators/image-grid.ts
src/admin/content/views/ContentEdit.scss
src/admin/content/views/ContentEditContentBlocks.tsx
src/admin/shared/types/content-block.ts
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx

Heb dit al even staan, zorgt ervoor dat de sidebar niet meer opzij wordt geduwd bij lange woorden in previews (niet dat dit veel gaat voorkomen normaal gezien)

fix(admin-content): prevent sidebar being pushed by long content

---

src/collection/collection.gql.ts
src/collection/collection.service.ts

so the queries work again since this field is removed from the database
before:
after:

fix(collections): remove label_redactie from queries

---

src/shared/components/CheckboxDropdownModal/CheckboxDropdownModal.tsx

hide the search field until we decide to implement the search
before:
after:

chore(checkbox-modal-filter): hide search field until we implement it

---

src/admin/permission-groups/permission-group.const.ts
src/admin/permission-groups/permission-group.gql.ts
src/admin/permission-groups/permission-group.service.ts
src/admin/permission-groups/permission-group.types.ts
src/admin/permission-groups/views/PermissionGroupOverview.tsx
src/admin/user-groups/user-group.gql.ts
src/admin/user-groups/user-group.service.ts
src/admin/user-groups/views/UserGroupOverview.tsx

permission groups was build before we had the filter table, so we can unify this, resulting in less lines of code, more uniform code and better filter/sort capability
before:
after:

feat(permission-group-overview): use filter table for permission groups

---

src/authentication/helpers/redirects.ts
src/settings/components/Profile.tsx
src/shared/components/Navigation/Navigation.tsx

also correctly redirect to logged-in home and logged-out home when clicking the home image at the left side of the top navbar

fix(login): redirect to home page after login instead of search

---

src/authentication/components/LoginOptions.tsx
src/authentication/components/LoginOptionsDropdown.tsx
src/authentication/helpers/redirects.ts
src/authentication/views/RegisterOrLogin.tsx

When you visit a url to a secure route, you need to login. But after the login, you are not redirected to the original page you requested, instead you go to the search page.
This PR fixes this
example:
http://localhost:8080/item/pk06x1db2t
http://localhost:8080/collecties/d2795434-7531-45fc-9552-fc1da8d01559

fix(auth): redirect to originally requested page after logging in

---

src/admin/content-block/helpers/generators/ctas.ts

closes: https://meemoo.atlassian.net/browse/AVO-100
Thi PR also has a component twin, but they do not depend on each other: 
https://github.com/viaacode/avo2-components/pull/265

fix(cta): allow one or two CTAs in a CTA block

---

src/item/components/modals/AddToCollectionModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-130
Fixed:
* entering a value that is larger than start/end of video => clamp to video range
* entering value for end that is smaller than start value => updates both values
* entering value for start that is bigger than end value => updates both values
* evaluate on change if duration has correct format (uu:mm:ss)
* evaluate on blur, check format, if invalid, revert to 0 or duration and show toast

fix(add-to-collection): improve behavior of fragment duration inputs

---

src/authentication/authentication.routes.tsx
src/authentication/components/SecuredRoute.tsx
src/authentication/store/selectors.ts
src/authentication/views/registration-flow/l8-accept-conditions.tsx
src/constants.ts
src/content-page/views/ContentPage.tsx
src/dynamic-route-resolver/views/DynamicRouteResolver.tsx
src/shared/components/Footer/Footer.tsx
src/shared/constants/routes.ts
src/shared/services/content-page-service.ts
src/shared/services/interactive-tour-service.ts
src/shared/services/navigation-items-service.ts
src/shared/services/notification-service.gql.ts
src/shared/services/notification-service.ts

closes: https://district01.atlassian.net/browse/AVO2-460
Twin PR: https://github.com/viaacode/avo2-proxy/pull/108
The accept conditions page loads 2 content page below each other with an accept conditions button at the bottom of the page.
We split this page into 2 because the privacy conditions also need to be accessible from the sites footer.

feat(auth): add accept conditions page for new users

---

src/admin/content-block/components/ContentBlockFieldEditor/ContentBlockFieldEditor.tsx
src/admin/content-block/helpers/generators/buttons.ts
src/admin/content-block/helpers/generators/ctas.ts
src/admin/content-block/helpers/generators/defaults.ts
src/admin/content-block/helpers/generators/heading.ts
src/admin/content-block/helpers/generators/image-grid.ts
src/admin/content-block/helpers/generators/image.ts
src/admin/content-block/helpers/generators/media-player-title-text-button.ts
src/admin/content-block/helpers/generators/media-player.ts
src/admin/content-block/helpers/generators/page-overview.ts
src/admin/menu/components/MenuEditForm/MenuEditForm.tsx
src/admin/shared/components/ContentPicker/ContentPicker.helpers.ts
src/admin/shared/components/IconPicker/IconPicker.test.tsx
src/admin/shared/constants/index.ts
src/admin/shared/types/content-picker.ts

This is a cleaner fix than defaultProps.options() since it doesn't require options to be handled any differently
This fixes the bug:

fix(content-blocks): add missing function brackets to const options

---

src/admin/users/user.gql.ts

cache query issue:
```
Store error: 
the application attempted to write an object with no provided id 
but the store already contains an id of shared_users: 23 for this object.
```

fix(admin-user-overview): fix query select id for apollo cache

---

src/admin/content-block/helpers/generators/image-grid.ts

This way, claire will be able to pick some presets that work for her, and then we can replace these sliders with some dropdown select options
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/77789730-e12b3580-7063-11ea-99a4-e45a88cda0de.png)|![image](https://user-images.githubusercontent.com/1710840/77789740-e4262600-7063-11ea-804b-dd567fe84fd1.png)|

chore(image-grid-block): show slider numeric value

---

src/shared/translations/i18n.ts

|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/78161062-32ad3900-7445-11ea-80e3-e92247a68e6b.png)|![image](https://user-images.githubusercontent.com/1710840/78161066-3476fc80-7445-11ea-817d-d0ddc5d8b964.png)|
Stars added to draw attention of developer to the fact that the translation is missing

fix(translations): improve usability if translations are missing or cannot be loaded

---

src/admin/content-block/content-block.const.ts
src/admin/content/views/ContentEdit.scss
src/admin/content/views/ContentEditContentBlocks.tsx

* Move block select dropdown to the top
* make primary color to draw attention
* do not scroll it out of view when scrolling in the sidebar
* always show the placeholder in the select component (requires component change)
* when adding a block, scroll to the bottom, so the user sees something
Component twin PR: https://github.com/viaacode/avo2-components/pull/272

feat(content-page-edit): move select to top + scroll when adding block

---

src/admin/Admin.tsx
src/admin/content-block/content-block.const.ts
src/admin/content/views/ContentDetail.scss
src/admin/content/views/ContentDetail.tsx
src/admin/content/views/ContentEdit.scss
src/admin/content/views/ContentEdit.tsx
src/admin/content/views/ContentEditContentBlocks.tsx
src/admin/content/views/ContentOverview.tsx
src/admin/interactive-tour/views/InteractiveTourDetail.tsx
src/admin/interactive-tour/views/InteractiveTourEdit.tsx
src/admin/interactive-tour/views/InteractiveTourOverview.tsx
src/admin/items/views/ItemDetail.tsx
src/admin/menu/views/MenuDetail.tsx
src/admin/menu/views/MenuEdit.tsx
src/admin/menu/views/MenuOverview.tsx
src/admin/permission-groups/views/PermissionGroupDetail.tsx
src/admin/permission-groups/views/PermissionGroupEdit.tsx
src/admin/permission-groups/views/PermissionGroupOverview.tsx
src/admin/shared/components/TopBar/TopBar.tsx
src/admin/shared/layouts/AdminLayout/AdminLayout.scss
src/admin/shared/layouts/AdminLayout/AdminLayout.slots.tsx
src/admin/shared/layouts/AdminLayout/AdminLayout.tsx
src/admin/shared/layouts/index.ts
src/admin/translations/views/TranslationsOverview.tsx
src/admin/user-groups/views/UserGroupDetail.tsx
src/admin/user-groups/views/UserGroupEdit.tsx
src/admin/user-groups/views/UserGroupOverview.tsx
src/admin/users/views/UserDetail.tsx

* Do not scroll them out of view
* This ensures that the action buttons are always visible on screen without needing another footer bar which saves some screen realestate

Make all admin headers uniform and minimize their height

---

src/collection/components/CollectionOrBundleEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-272

fix(collection-edit): fragment reorder buttons have inverted directions

---

src/admin/content-block/helpers/parsers.ts

Since we disabled accordions, pages that still contain this block crash hard.
This PR will just omit the blocks for which a configuration cannot be found and show an error toast.
example: http://localhost:8080/beheer/content/36

fix(content-blocks): avoid crashing on pages that contain an accordion

---

src/admin/shared/types/content-picker.ts
src/shared/helpers/link.tsx

Otherwise the "projecten in de kijker" block doesn't list PROJECT content pages but instead PAGINA content pages and the links on the block do not work correctly

fix(content-picker): fix projects type for linking and allowedTypes

---

src/admin/content-block/helpers/generators/media-player-title-text-button.ts
src/admin/content-block/helpers/generators/media-player.ts
src/admin/shared/components/ContentPicker/ContentPicker.tsx

Mediaspeler-blok heeft geen targetSelf switch nodig.

fix(content-picker): hide target switch

---

src/admin/content-block/helpers/generators/defaults.ts
src/admin/content-block/helpers/generators/media-player-title-text-button.ts
src/admin/content-block/helpers/generators/media-player.ts
src/admin/shared/components/ContentPicker/ContentPicker.tsx

- This implements the error when you clear the content picker after an item was selected. It will say that the video-item is mandatory.

fix(cb-media-player): validate onClear content picker

---

src/collection/components/modals/CutFragmentModal.tsx

Start time of cut is now saved too.
Known issue: blue banner on video doesn't update but that's seperate ticket.

fix(fragment-cut): save start time

---

src/collection/components/fragment/FragmentDetail.tsx
src/item/components/ItemVideoDescription.tsx

Het was niet zichtbaar op de collectiedetail pagina dat een fragment ge-cut was. Nu wel.
Voorbeeld: fragment 2 op http://localhost:8080/collecties/86307cca-c264-4aa6-a219-a8a63df51534

feat(collection-detail): show cut on fragments

---

src/admin/users/user.gql.ts
src/admin/users/user.types.ts
src/admin/users/views/UserDetail.tsx

This makes it easier for an avo admin to troubleshoot missing permissions for a user

feat(user-detail): show user groups, perm groups and perms

---

src/admin/content-block/components/ContentBlockForm/ContentBlockForm.tsx
src/admin/content/views/ContentEditContentBlocks.tsx

* Now the whole accordion is clickable to expand/contract the content.
* The order buttons are combined in a button group
* The edit button is removed, since the whole accordion is clickable and the icon on the right can also be used to expand/contract the accordion
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/79781818-642b6d00-833e-11ea-9f6d-7738ef6df63b.png)|![image](https://user-images.githubusercontent.com/1710840/79781823-67265d80-833e-11ea-804d-1b823bba3ec5.png)|

fix(content-block-form): simplify accordion buttons/behavior

---

src/search/components/SearchFilterControls.tsx

closes: https://meemoo.atlassian.net/browse/AVO-200
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/79957344-b923cc00-8481-11ea-9ab2-3ad719f8233a.png)|![image](https://user-images.githubusercontent.com/1710840/79957352-bb862600-8481-11ea-8b47-0d372e1bfffd.png)|

fix(search): remove language name capitalization in search filter

---

src/admin/content-block/helpers/generators/defaults.ts
src/admin/content-block/helpers/generators/page-overview.ts

closes: https://meemoo.atlassian.net/browse/AVO-653
Textblock doesn't show it anymore:
page overview block still shows it:

fix(page-overview-block): show title bar bg color only for this block

---

src/admin/shared/layouts/AdminLayout/AdminLayout.scss

Due to top bar H1 style, this looked like a H2 instead of a H1.

AVO-78 / Fix H1 style in title block.

---

src/admin/items/items.gql.ts
src/admin/items/items.service.ts
src/admin/items/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-284
if any other fields need editing, we should create a separate edit page. For this single notes field, it seems a bit overkill.

feat(admin-item-detail): allow entering notes for an item

---

src/admin/menu/views/MenuEdit.tsx
src/admin/shared/components/ContentPicker/ContentPicker.tsx

- Switching the target toggle made it that the value was an object instead of the id of whatever was selected, hence the link didn't work anymore, and the second content picker select field showed empty as the object was not part of the options.

fix(content-picker): fix target switch resetting value

---

package-lock.json
package.json
src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx
src/admin/content/views/ContentEditContentBlocks.tsx

recloses: https://meemoo.atlassian.net/browse/AVO-652

fix(content-block-preview): resize header height on resize, state change

---

src/shared/components/CheckboxDropdownModal/CheckboxDropdownModal.tsx

When there are no filters in search, disable "Toepassen" button and display text.

feat(checkbox-dropdown): disable button if no filter

---

src/error/views/ErrorView.tsx

closes: https://meemoo.atlassian.net/browse/AVO-675
Proxy pr: https://github.com/viaacode/avo2-proxy/pull/137
This way, the saml ticket gets refreshed between login attempts, so new settings made in ldap are reflected in the new saml ticket.
steps:
* user tries to login
* server sees that the user does not have access to avo
* server redirects to client error page with logout=true query param
* client error page logs the user out by redirecting to the server logout route
* server logs the user off of the idp
* server redirects back to error page without query param: logout=true
* user can contact the helpdesk
* helpdesk can give the user access to avo through the meemoo account manager dashboard
* user tries to login again
* the server receives a NEW saml ticket with the avo group
* user …

fix(error-view): logout if error occurs during login flow

---

src/admin/content-block/components/ContentBlockForm/ContentBlockForm.scss
src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.scss
src/admin/content-block/components/fields/PaddingSelect/PaddingSelect.tsx
src/admin/content-block/helpers/generators/defaults.ts
src/admin/content-block/helpers/generators/heading.ts
src/admin/content-block/helpers/generators/page-overview.ts
src/admin/content/views/ContentEdit.scss

closes: 
* https://meemoo.atlassian.net/browse/AVO-315
* https://meemoo.atlassian.net/browse/AVO-192
components pr: https://github.com/viaacode/avo2-components/pull/312
Problem where headersblock content has its own padding:
Fixed by removing padding from block content and increasing the block padding:
Add extra padding option:
Remove padding image block:
Remove padding rich text block:

fix(block-preview): block padding handles padding, not block content

---

src/authentication/helpers/redirects.ts
src/authentication/views/Logout.tsx
src/error/views/ErrorView.tsx
src/shared/constants/routes.ts

closes: https://meemoo.atlassian.net/browse/AVO-455
This cannot be tested locally since there is a bug in the idp for localhost development.
You can go to http://localhost:8080/leerlingen and see the page
and you should end up on /start when you login instead of /home
testing logout for pupils will have to be done after deploying

feat(logout): redirect to /leerlingen when pupil logs out

---

src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx

steps to reproduce before this patch:
* edit an assignment
* add a label
* save assignment
expected result: labels stay visible
result before patch: labels reset to initial labels

fix(assignment-edit): ensure labels are saved correctly

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx

part of: https://meemoo.atlassian.net/browse/AVO-215
When you do not select a custom media tile button action, it should correctly link to the media item that was selected for the time

fix(media-tiles-block): correctly map button action to media tile

---

src/admin/shared/helpers/filters.ts

part of: https://meemoo.atlassian.net/browse/AVO-515
steps to reproduce bug before this patch:
* go to bundle overview in admin dashboard
* filter bundels by public: true
expected result: only public bundles are shown
result before this patch: error page

fix(admin-bundle-overview): set correct prop for boolean filters

---

src/assignment/assignment.helper.tsx

this was introduced when the duplicate code was extracted and the branches were not merged correctly

fix(assignment-create): regression of default select radio button

---

src/workspace/views/BookmarksOverview.tsx

before this patch bookmarks to a bundle would use the collection detail route resulting in a "not found" error

bookmark for bundles

---

src/assignment/assignment.gql.ts
src/assignment/assignment.service.ts
src/assignment/views/AssignmentOverview.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/collection/components/modals/DeleteCollectionModal.tsx
src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-386
This creates a DeleteCollectionModal that is used on:
* collectionOverview
* collectionDetail
* collectionOrBundleEdit
This PR also reworks the way we fetch the collections in the overview using the useCallback/service method instead of the dataFetchComponent
Finally i also fixed a glitch where the assignments would show the assignment responses instead. This was due to the assignments being fetched before we determined the correct user permissions, so the fetch function would assume you were a pupil instead of a teacher

feat(collection): warn if collection used by assignment on delete

---

src/collection/components/CollectionOrBundleEditAdmin.tsx
src/collection/components/CollectionOrBundleEditMetaData.tsx

Bij bundels en collecties staat "Persoonlijke notities" nu weer onder meta data en niet onder beheer.
Fixes: AVO-319 & AVO-295

AVO-319 & AVO-295: Move personal notes to meta data tab

---

src/authentication/components/StamboekInput.tsx

AVO-702: Reeds in gebruikt toont nu in Danger toast in plaats van Success.

---

src/admin/content/content.service.ts
src/admin/shared/helpers/omitByDeep.ts

closes: https://meemoo.atlassian.net/browse/AVO-786
We cloned the state before omitting the rte editor state, but the editor state is either so huge that is locks up the browser or more likely: the editorstate contains circulr references which put the clone deep function in an infinite loop.
Solved by combining the cloneDeep and the omitByRecursive functions into one, so we can omit the rte states and clone the object at the same time.
with styles:
without styles:

fix(omit-by-deep): avoid cloning the rte state, since it is huge

---

src/styles/components/_content.scss

closes: https://meemoo.atlassian.net/browse/AVO-784
left:
right:

Fix image-margin for inline images inside RTE

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/admin/content/views/ContentDetailMetaData.tsx
src/admin/content/views/ContentOverview.tsx
src/admin/users/user.service.ts
src/authentication/authentication.const.ts
src/authentication/authentication.types.ts
src/authentication/views/Login.tsx
src/dynamic-route-resolver/views/DynamicRouteResolver.tsx
src/shared/helpers/formatters/avatar.tsx

closes: https://meemoo.atlassian.net/browse/AVO-463
after login by pupil, they are redirected to their workspace:

feat(dynamic-route-resolver): after login redirect pupils to workspace

---

src/shared/helpers/fetch-with-logout.ts
src/shared/services/data-service.ts

steps to reproduce:
* logout
* goto http://localhost:8080
The page should only reload once, not infinitly due to 401 errors

fix(login-page): avoid infinite reload loop due to 401 errors

---

src/admin/content-block/components/ContentBlockForm/ContentBlockForm.tsx
src/admin/content/helpers/reducers/content-edit.ts

closes: https://meemoo.atlassian.net/browse/AVO-891
also reduced the number of rerenders because of SET_ERROR_STATE in the reducer setting an empty list of errors every time

AVO-891 Content block 'hero': titel, beschrijving en knoppen verschijnen niet in preview beheer

---

src/shared/helpers/sanitize/presets/index.ts

closes: https://meemoo.atlassian.net/browse/AVO-928
before: 
after:

AVO-928 RTE: ik kan geen tekst meer centreren

---

src/admin/content/content.service.ts
src/admin/shared/components/ContentPicker/ContentPicker.tsx
src/admin/shared/helpers/content-picker/content-page.ts

closes: https://meemoo.atlassian.net/browse/AVO-929
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/84486445-b84b3180-ac9d-11ea-83fa-de335717d600.png)|![image](https://user-images.githubusercontent.com/1710840/84486453-ba14f500-ac9d-11ea-969e-a6fe6e488000.png)|
since these only contain the title and the path, there is little use to pull them through the converter function
also improved the error handling, so we get a toast message when the content picker fails to "inflate"

AVO-929 CB hero / header startpagina: kan geen link leggen naar bepaalde pagina's voor de knoppen

---

src/admin/content/content.service.ts

Zoeken van content in content picker werkte niet omdat daar een refactor-issue opgedoken is, weer met die convert naar content blocks zoals bij project in de kijker vorige week.

HOTFIX: content picker - search content

---

src/authentication/views/registration-flow/r4-manual-registration.tsx

Closes: https://meemoo.atlassian.net/browse/AVO-837
Onderwijsniveau's worden nu proper opgelijst (met spaties na de komma's 😉).

fix(manual-registration): zendesk format

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1046
newsletter pages: 2 published, 2 unpublished:
before page overview would show all:
after page overview only show published pages:

AVO-1046 Enkel gepubliceerde pagina's mogen getoond worden in overzichtspagina's

---

src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1048
example page with avo1 collection id: http://localhost:8080/collecties/938051
before you saw a short flash of failed to load + error toast: failed to load related collections:
Then you see the correct collection on the correct url:
After this fix you see a spinner:
And then the correct page on the correct url:

AVO-1048 Collecties: blanco scherm in bewerkmodus

---

src/item/components/modals/AddToCollectionModal.tsx
src/shared/services/video-stills-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1004
collection thumbnail before and after
collection detail before:
collection detail after

AVO-1004 Collecties: bij niet-geknipte items wordt opnieuw de eerste still getoond, ipv de standaardstill

---

src/admin/users/views/UserDetail.tsx

part of: https://meemoo.atlassian.net/browse/AVO-731
Smartschool user should be bannable from the avo platform:
Ldap users should be banned from the account manager by removing their avo app access:

fix(user-detail): only show ban button for SS users without ldap account

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/shared/services/file-upload-service.ts

closes:
* https://meemoo.atlassian.net/browse/AVO-1018
* https://meemoo.atlassian.net/browse/AVO-735
Proxy PR: https://github.com/viaacode/avo2-proxy/pull/169
allow upload of bigger files for the regular files. Zendesk attachments still use the old upload approach since those files generally are not that big (word/excel/pdf)

fix(asset-service): upload assets using multipart form upload

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/items/views/ItemsOverview.tsx

part of: https://meemoo.atlassian.net/browse/AVO-878
item overview without the VIEW_ANY_UNPUBLISHED_ITEMS should not throw this error, but instead only show published items
items detail in the admin dashboard is already correct:

fix(item-overview): only query for items the user is allowed to see

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/admin/shared/components/ContentTypeAndLabelsPicker/ContentTypeAndLabelsPicker.tsx

closes: https://meemoo.atlassian.net/browse/AVO-937

fix(page-overview-block): reset labels when changing content type

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.scss
src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1185

fix(content-block-preview): make cb z-index 1 only if header bg color

---

src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1222
proxy PR: https://github.com/viaacode/avo2-proxy/pull/201
example url that didn't work: http://localhost:8080/collecties/5491d72a-f136-44b4-86fa-dd44f1deea3d

fix(collection-detail): show collection even if no subjects/edu levels

---

src/shared/components/WYSIWYGWrapper/WYSIWYGWrapper.scss
src/shared/components/WYSIWYGWrapper/WYSIWYGWrapper.tsx

|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/87684673-d1566f00-c782-11ea-86df-6cdee7b90b89.png)|![image](https://user-images.githubusercontent.com/1710840/87684680-d3b8c900-c782-11ea-9064-0b3783ef5650.png)|

fix(wysiwyg-wrapper): remove margin so caret and placeholder align

---

src/admin/interactive-tour/views/InteractiveTourEdit.tsx
src/admin/interactive-tour/views/InteractiveTourEditStep.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1081
example page that would go really slow when typing in the last step description: http://localhost:8080/beheer/interactieve-tours/21/bewerk

fix(interactive-tour-edit): memoize tour step edit controls

---

src/admin/admin.const.ts
src/admin/content/views/ContentDetail.tsx
src/admin/content/views/ContentEdit.tsx
src/admin/content/views/ContentOverview.tsx

part of: https://meemoo.atlassian.net/browse/AVO-1108
This PR adds additional checks on top of: https://github.com/viaacode/avo2-client/pull/912
* only show start page menu items to users that can edit all content pages. So educatonal partners do not see these, since they can't edit them anyway.
* Check permissions before loading detail and edit pages, otherwise users that know the url can still see these really easily. The perminant fix for this is: https://meemoo.atlassian.net/browse/AVO-260
* Fix issues with dependency arrays for useCallback functions in the ContentOverview page

fix(content-pages): hide nav, check permissions before edit/detail

---

src/admin/translations/translations.service.ts
src/admin/translations/views/TranslationsOverview.tsx
src/shared/services/data-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1240
This fixes 90% of the overwrite issues with translations, by only saving the changed values to the database.
Users can still overwrite the same translation if the change it at the same time.
After step 4 this is the result:
After step 6 this is the result:

fix(translations): only update changed translations in the database

---

src/admin/content-block/components/wrappers/BlockContentPageMeta/BlockContentPageMeta.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1144
example page: http://localhost:8080/beheer/content/356
ignore the american formatting

fix(content-page-meta): show published date instead of update date

---

src/bundle/views/BundleDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1223
newly created bundles do not have any keywords

fix(bundle-detail): default keywords to empty array for json-ld data

---

src/authentication/helpers/redirects.ts
src/dynamic-route-resolver/views/DynamicRouteResolver.tsx
src/error/views/ErrorView.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1158
clicking the navigate to homepage button on an error page now takes to to the respective logged in homepage:
Also added redirect to logged out startpage so they are redirect to the logged in startpage if the user is logged in:
teachers:
http://localhost:8080/ => http://localhost:8080/start
of
pupils: 
http://localhost:8080/ => http://localhost:8080/werkruimte/opdrachten

fix(error-view): redirect to logged in homepage if logged in

---

src/admin/Admin.tsx

steps:
* go to http://localhost:8080
* click "beheer" in the menu bar
expected result: zendesk widget is not visible in the admin dashboard
current result: zendesk widget is visible
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/89762190-38501500-daf0-11ea-92cf-57a3832203b9.png)|![image](https://user-images.githubusercontent.com/1710840/89762191-3a19d880-daf0-11ea-85b6-ee58bbee570a.png)|

fix(zendesk): remove zendesk widget when switching to admin dashboard

---

src/collection/components/CollectionOrBundleOverview.tsx
src/workspace/views/BookmarksOverview.tsx

For collections, bundles and bookmarks:
Resolves: https://meemoo.atlassian.net/browse/AVO-328

fix(workspace): show created data as data instead of fromNow

---

src/authentication/helpers/get-profile-info.ts
src/settings/components/Profile.tsx

closes: https://meemoo.atlassian.net/browse/AVO-977
* hide complete profile step
* make subjects optional
* make education levels read only + hide if undefined
* make educational organisation readonly and remove required asterix
create account:
complete profile step is not show
profile page looks like this:
create second account:
complete profile step is not show
profile page looks like this:

feat(profile): change profile fields for exception accounts

---

src/admin/items/items.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1262
test page: http://localhost:8080/media/de-teloorgang-van-de-regie-maritiem-transport/lTKGYYUfrRN9RZkkdM7Cyqgp
should redirect to: http://localhost:8080/item/db7vm5bb7r
before:
after:

fix(items-service): await response json from proxy for mediamosa resolve

---

src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1273
test page: http://localhost:8080/test-cp-inekes
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/89885400-4888f280-dbcb-11ea-8f30-809bc84b6f77.png)|![image](https://user-images.githubusercontent.com/1710840/89885405-4aeb4c80-dbcb-11ea-80e6-f2605e3862aa.png)|

fix(media-player-wrapper): do not pass item obj if mediaitem is undef

---

src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.scss

part of: https://meemoo.atlassian.net/browse/AVO-944
before:
after:

fix(flow-player-wrapper): center play button when adding annotations

---

src/shared/components/ZendeskWrapper/ZendeskWrapper.tsx

https://caniuse.com/#feat=resizeobserver

fix(zendesk-wrapper): avoid error for resize observer on safari < 13.1

---

src/collection/components/CollectionOrBundleEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1289
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/90503123-3a991b80-e14f-11ea-8992-9a3ef6875aa5.png)|![image](https://user-images.githubusercontent.com/1710840/90503108-34a33a80-e14f-11ea-85bd-46f9fd3c4117.png)|

fix(collection-edit): default to fragment description for drag item

---

src/admin/content/views/ContentDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1296
content partners should not be able to duplicate content pages:
before:
after:

fix(content-detail): hide duplicate content page for edit own permission

---

package-lock.json
package.json
src/admin/users/views/UserOverview.tsx

since the sort causes the query to time out
This is a hotfix until we can fix this issue more thoroughly

fix(user-overview): set default sort to last_name asc

---

src/admin/users/user.gql.ts
src/admin/users/views/UserDetail.tsx

part of: https://meemoo.atlassian.net/browse/AVO-1331
This still doesn't work correctly since the ldap object doesn't pass us the correct value.
But this PR makes our code more correct.

fix(user-detail): show business_category field

---

src/styles/generic/_global.scss

fix(admin): move announcements div to top to remove double scrollbar

---

src/admin/content/views/ContentDetail.tsx
src/bundle/views/BundleDetail.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1326
So we can close them from the parent component when one of their options is clicked
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/91751834-b66e7b80-ebc5-11ea-8782-fb99daf9106e.png)|![image](https://user-images.githubusercontent.com/1710840/91751840-b79fa880-ebc5-11ea-9a61-c13c8934c714.png)|

fix(dropdown): replace some controlled dropdown with dropdowns

---

src/App.tsx
src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx
src/shared/components/Navigation/Navigation.tsx
src/shared/helpers/inside-iframe.ts
src/shared/helpers/link.tsx
src/styles/objects/_app.scss

closes: https://meemoo.atlassian.net/browse/AVO-1354
You can test this by installing live-server globally:
```
npm i -g live-server
```
Then creating a folder with index.html file with this content:
```
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Avo2 iframe</title>
<style>
body {
margin: 0;
padding: 0;
border: 0;
overflow: hidden;
}
iframe {
width: 100vw;
height: 100vh;
box-sizing: border-box;
overflow: hidden;
}
</style>
</head>
<body>
<iframe src="http://localhost:8080/projecten/klaar" frameborder="0"></iframe>
</body>
</html>
```
Then start your client and proxy of avo2
Then start …

fix(klaar-iframe): hide nav bars, zendesk and open links in new tab

---

src/collection/components/fragment/FragmentEdit.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1382

fix(fragment-edit): add openOptionsId to meoize comparison function

---

src/admin/items/items.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleEditContent.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/collection/components/fragment/FragmentList.tsx
src/collection/helpers/fragment.ts
src/item/views/ItemDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-700
show warning on collection edit screen as well as the collection detail screen:
also: replace url for replaced items, so we don't have any issues with replaced items being added to a collection/assignment.

fix(fragment): show replacement warning on edit, redirect item detail

---

src/authentication/helpers/redirects.ts

closes: https://meemoo.atlassian.net/browse/AVO-1391
steps to reproduce:
* open http://localhost:8080/faq-overzicht-2
* leave it open for a night
* log back in
expected result: you should be redirected to http://localhost:8080/faq-overzicht-2 again
current result: you are redirect to: http://localhost:8080/faq-overzicht-2undefined

fix(redirects): output empty string when hash is undefined

---

src/home/views/Home.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1395

fix(home): add translatable title to logged in home page

---

src/shared/translations/i18n.ts

only delete any none alphanumeric characters if the key contains "___", otherwise just render the untranslated string with a " ***" suffix
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/97292210-3ffb9c00-184b-11eb-9679-7ff422ad3242.png)|![image](https://user-images.githubusercontent.com/1710840/97292220-41c55f80-184b-11eb-959f-d6523dcfddda.png)|

fix(i18n): improve display of untranslated strings

---

src/admin/content-block/components/wrappers/ImageGridWrapper/ImageGridWrapper.tsx
src/admin/content-block/content-block.const.ts
src/admin/shared/types/content-block.ts

closes: https://meemoo.atlassian.net/browse/AVO-1060
het afknippen van de logos is een gevolg van het rare image formaat die geupload is:
before:
after:

feat(image-grid): add new image format: 400x150

---

src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/content-page-labels/views/ContentPageLabelDetail.tsx
src/admin/content-page-labels/views/ContentPageLabelEdit.tsx
src/admin/content-page-labels/views/ContentPageLabelOverview.tsx
src/admin/content/views/ContentDetail.tsx
src/admin/content/views/ContentEdit.tsx
src/admin/content/views/ContentOverview.tsx
src/admin/dashboard/views/Dashboard.tsx
src/admin/interactive-tour/views/InteractiveTourDetail.tsx
src/admin/interactive-tour/views/InteractiveTourEdit.tsx
src/admin/interactive-tour/views/InteractiveTourOverview.tsx
src/admin/items/views/ItemDetail.tsx
src/admin/items/views/ItemsOverview.tsx
src/admin/items/views/PublishItemsOverview.tsx
src/admin/menu/views/MenuDetail.tsx
src/admin/menu/views/MenuEdit.tsx
src/admin/menu/views/MenuOverview.tsx
src/admin/permission-groups/views/PermissionGroupDetail.tsx
src/admin/permission-groups/views/PermissionGroupEdit.tsx
src/admin/permission-groups/views/PermissionGroupOverview.tsx
src/admin/shared/components/TopBar/TopBar.tsx
src/admin/shared/layouts/AdminLayout/AdminLayout.slots.tsx
src/admin/shared/layouts/AdminLayout/AdminLayout.tsx
src/admin/shared/layouts/index.ts
src/admin/translations/views/TranslationsOverview.tsx
src/admin/user-groups/views/UserGroupDetail.tsx
src/admin/user-groups/views/UserGroupEdit.tsx
src/admin/user-groups/views/UserGroupOverview.tsx
src/admin/users/views/UserDetail.tsx
src/admin/users/views/UserOverview.tsx

makes admin layout header width match body and reduces the amount of code at the same time 💪 
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/97422079-9a5d3100-190d-11eb-8225-0c51bd29e280.png)|![image](https://user-images.githubusercontent.com/1710840/97422084-9d582180-190d-11eb-86c3-73b5b562a186.png)|
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/97422120-a9dc7a00-190d-11eb-83c5-153ddaad115a.png)|![image](https://user-images.githubusercontent.com/1710840/97422113-a6e18980-190d-11eb-99aa-6b824292be9f.png)|
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/97422166-b9f45980-190d-11eb-9e58-c1779ccffeb3.png)|![image](https://user-images.githubusercontent.com/1710840/97422 …

feat(admin-layout): make admin layout topbar same width as body

---

src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.scss
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1414
ios doesn't support hls playlists
@benjaminnaesen als je deze eens kan testen op je iphone, of had jij er geen?
deze video zou moeten kunnen afspelen op ios safari:
http://localhost:8080/flowplayer-met-m-3-u-8-url

fix(flowplayer): rewrite flowplayer m3u8 urls to mp4 on ios

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/admin/content-page-labels/content-page-label.gql.ts
src/admin/content-page-labels/content-page-label.service.ts
src/admin/content/content.gql.ts
src/admin/content/views/ContentOverview.tsx
src/admin/shared/components/ContentTypeAndLabelsPicker/ContentTypeAndLabelsPicker.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1410
This should allow users to rename page labels without breaking overview pages.
links to specific labels on overview pages will still break. not much we can do about that.
overview pagina met label:
rename the label:
overview page loads with changed label:

feat(page-overview-wrapper): save labels by id

---

src/authentication/helpers/redirects.ts

closes: https://meemoo.atlassian.net/browse/AVO-1430

fix(redirects): decode url before trying to split it by the path

---

src/admin/content-block/content-block.const.ts

closes: https://meemoo.atlassian.net/browse/AVO-664
asc is old => new
desc is new => old
not the other way around

fix(content-block-consts): flip sort orders for date page overview block

---

src/dynamic-route-resolver/dynamic-route-resolver.const.ts
src/dynamic-route-resolver/views/DynamicRouteResolver.tsx
src/shared/services/content-page-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1421
Requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/270
example url of a depublished event content page:
http://localhost:8080/depublished-event-page
example url of a depublished regular content page:
http://localhost:8080/depublished-content-page

feat(dynamic-route-resolver): custom error message for depublished pages

---

src/shared/components/DateRangeDropdown/DateRangeDropdown.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1406
safari fails on this code:
```
new Date('2020-11-10 00:00:00') // => Invalid time value
```
so changed it to:
```
moment('2020-11-10 00:00:00', 'YYYY-MM-DD HH:mm:ss').toDate()
```

fix(date-range-dropdown): use moment for parsing instead of date obj

---

src/collection/views/CollectionDetail.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1446
how to test:
* ga naar: http://localhost:8080/item/cv4bp1t14v
* edit de link naast de video to point to: http://localhost:8080/collecties/2255881 ipv https://onderwijs.hetarchief.be/collecties/2255881
* use the back button once
expected result: you go back to the item page
result before this PR: you would stay on the collection page

fix(collection-detail): replace history when redirecting from old id

---

src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/collectionsOrBundles/collections-or-bundles.service.ts
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/admin/content/content.gql.ts
src/admin/content/content.service.ts
src/admin/content/views/ContentDetail.tsx
src/admin/content/views/ContentOverview.tsx
src/admin/users/user.gql.ts
src/admin/users/user.service.ts
src/admin/users/user.types.ts
src/admin/users/views/UserDetail.tsx
src/admin/users/views/UserOverview.tsx
src/collection/collection.gql.ts
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/shared/helpers/idps-to-taglist.tsx
src/shared/services/organizations-service.gql.ts
src/workspace/workspace.gql.ts

closes: https://meemoo.atlassian.net/browse/AVO-1343
proxy PR: https://github.com/viaacode/avo2-proxy/pull/286
De gebruiker verdwijnt momenteel nog niet uit de lijst aangezien bart maandag nog de is_deleted property toevoegt aan de benodigde view:
https://github.com/viaacode/avo2-client/pull/1143/files#diff-68ccf6700a4dc412197a969c1948398a5fa4d5efe144198644eb21b82dc714f1R216-R217
Link delete ui to backend route
add soft delete where clause to all content queries:
is_deleted: false
for tables:
* users_profiles
* shared_users
* app_collections
* app_assignments
* app_content

feat(user-service): link delete users ui to backend route

---

src/admin/content/components/PublishContentPageModal.scss
src/admin/content/components/PublishContentPageModal.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1445
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/285
initial news page:
Suppose you want the first article to show up below the second. Change the display date:
Now the ordering is different:
Tooltip:

feat(publish-content-page-modal): add input to set published_at date

---

src/authentication/helpers/redirects.ts

closes: https://meemoo.atlassian.net/browse/AVO-1461
proxy PR: https://github.com/viaacode/avo2-proxy/pull/289
This mainly fixes this scenario:
* getest met ineke.vandam+1
* via acm AVO app verwijderd+syncen
* aanmelden lukt niet op avo
* via acm AVO app terug toevoegen + syncen
* aanmelden lukt niet op avo

fix(redirects): never redirect a user back to an error page after login

---

src/shared/services/data-service.ts

so we can replace these queries with the same query from the whitelist. This way we avoid any tampering with the query on the client or during transit to the server

fix(data-service): fetch graphql data without types

---

src/admin/collectionsOrBundles/collections-or-bundles.gql.ts
src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx
src/collection/collection.gql.ts
src/shared/services/content-page-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1482
proxy PR: https://github.com/viaacode/avo2-proxy/pull/291
This fixes 2 issues with media grids:
* multiple queries had the same name, causing the whitelisting in the proxy to check the wrong permissions
* when manually selecting tiles for the media grid the grid did not re-render, so you wouldn't see your changes until you saved an reloaded.

fix(media-grid): fix issue with media grid fetching collections

---

src/admin/content-block/components/wrappers/MediaPlayerTitleTextButtonWrapper/MediaPlayerTitleTextButtonWrapper.tsx
src/admin/content-block/components/wrappers/MediaPlayerWrapper/MediaPlayerWrapper.tsx
src/authentication/helpers/redirects.ts
src/collection/components/fragment/FragmentEdit.tsx
src/collection/components/modals/CutFragmentModal.tsx
src/item/components/ItemVideoDescription.tsx
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx
src/shared/components/SmartLink/SmartLink.tsx
src/shared/helpers/link.tsx
src/shared/services/smartschool-analytics-service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1471
i've added console info statements so we can easily debug this once it is on production. During the next deploy we can then remove those console info statements again.
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/292

feat(smartlink): trigger analytics events to SmartSchool when inside iframe

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1226
http://localhost:8080/faq-focus-test?item=/faq-leerling/waarom-lerarenkaart-of-stamboeknummer

fix(page-overview-wrapper): reset focused page when changing pages

---

src/assignment/assignment.service.ts
src/authentication/store/actions.tsx
src/collection/collection.service.ts

closes: https://meemoo.atlassian.net/browse/AVO-1371
fix issue where assignmentUuid isn't correctly passed to the proxy, causing the collection content of an assignment to not show up
make sure only one assignment_response entry is created by removing the caching for the request to check if a response already exists and fixing the issue where the user object is stored twice in the redux store.

fix(assignment-detail): only create one response entry

---

src/error/views/ErrorView.scss
src/error/views/ErrorView.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1493
since safari otherwise shows some strange render glitch
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/104216851-e878cf80-543a-11eb-8126-2df677fae89e.png)|![image](https://user-images.githubusercontent.com/1710840/104216856-ea429300-543a-11eb-94fc-8b2934be2cd9.png)|

feat(error-view): set min height on error view container

---

src/admin/users/user.const.ts

closes: https://meemoo.atlassian.net/browse/AVO-1341
names starting with a lowercase are no longer sorted separately from the capitalised names

feat(users-overview): sort by lowercase first/last name

---

.gitignore
package.json
scripts/env.js

We hebben dit aangepast om support te voorzien voor .env variables met `=` in de url.

fix(package.json): add start-with-env script

---

src/collection/components/CollectionOrBundleEdit.tsx

Render an error message when a user has no rights to edit a collection or bundle

fix(collection-edit): error on no permissions

---

package-lock.json
package.json
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.scss
src/styles/components/_checkbox-radio.scss
src/styles/components/_projects-grid.scss

switch node-sass to sass since node-sass is deprecated
and node-sass is a pain to get installed on windows because it depends on node-gyp
https://sass-lang.com/blog/libsass-is-deprecated
the sass package uses dart instead of c++ code, so it doesn't need node-gyp and its smaller and faster

fix(sass): switch node-sass to sass since node-sass is deprecated

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1619
to test on page: http://localhost:8080/nieuws

fix(page-overview-wrapper): encode labels in the url query params

---

src/settings/views/Settings.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1605
as a student these are the results when you now load various settings pages:

fix(settings): check perms before loading newsletter/notification pages

---

src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.const.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.gql.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.ts
src/shared/services/bookmarks-views-plays-service/bookmarks-views-plays-service.types.ts

closes: https://meemoo.atlassian.net/browse/AVO-1531
The syncrator will ensure a row is created for each item/collection/bundle with count 0, so we do not need to initialise this count when a user views the page. All we have to do is increment.
You can test this on any item/collection/bundle detail page. The view count should increment on page reload.
http://localhost:8080/item/sx64487s06

feat(bookmark-views-plays-service): remove init count code and queries

---

src/admin/content-block/components/wrappers/MediaPlayerTitleTextButtonWrapper/MediaPlayerTitleTextButtonWrapper.tsx
src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx

closes: https://meemoo.atlassian.net/browse/AVO-1660
requires components PR: https://github.com/viaacode/avo2-components/pull/452
Replaces button with onClick by a href where possible:
* page overview block labels
* media player buttons

feat(page-overview-wrapper): use links instead of buttons for SEO

---

src/admin/collectionsOrBundles/collections-or-bundles.const.ts

AVO-1455 hide organisations column by default

fix(columns): hide organisations column by default

---

src/admin/users/user.gql.ts

Fixes issue where the unblocked date on a user detail page was undefined.
Proxy fix: https://github.com/viaacode/avo2-proxy/pull/380

fix: fetch unblocked_at property from database

---

src/admin/users/user.gql.ts
src/admin/users/user.service.ts
src/admin/users/user.types.ts

query and show ldap organisationname

feat(organisationname): query and show ldap organisationname

---

src/admin/collectionsOrBundles/helpers/collection-filters.ts
src/admin/collectionsOrBundles/views/CollectionOrBundleActualisationOverview.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleMarcomOverview.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleQualityCheckOverview.tsx
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx

Optie 'no role' toegevoegd bij filteren in collecties en bundles
Queries geupdate

feat: filter on no-role for collections and bundles

---

src/assignment/views/AssignmentOverview.tsx
src/constants.ts

https://meemoo.atlassian.net/browse/AVO-1908
When clicking a link to an assignment in the workspace as a pupil:
You are now correctly taken to the first tab of the assignment response detail page:

fix(avo-1908): fix link from workspace to assignment response detail

---

package-lock.json
src/assignment/views/AssignmentResponseEdit.tsx
src/collection/collection.types.ts
src/collection/components/CollectionFragmentFlowPlayer.tsx
src/collection/components/CollectionFragmentMeta.tsx
src/collection/components/CollectionFragmentRichText.tsx
src/collection/components/CollectionFragmentTitle.tsx
src/collection/components/CollectionFragmentTypeItem.tsx
src/collection/components/CollectionFragmentTypeText.tsx
src/collection/components/index.ts
src/collection/views/CollectionDetail.tsx
src/shared/components/BlockList/BlockList.tsx
src/shared/components/BlockList/BlockList.types.tsx

Instead of toggling features by passing a boolean, pass through optional configurations of all underlying components. In scenarios where these configurations are shared/duplicated they can be split into constants as needed.
Related to https://github.com/viaacode/avo2-client/pull/1384#discussion_r913476732

feat(avo-1908): adjust BlockList to pass configs

---

src/search/components/SearchFiltersAndResults.tsx
src/search/views/Search.tsx
src/shared/helpers/formatters/avatar.tsx

pagination was broken on the regular search page after avo-1910 which moved the page param to the url params

fix(avo-1910): fix pagination on the teacher search page

---

src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponsePupilCollectionTab.tsx

https://meemoo.atlassian.net/browse/AVO-1912
Since pupils have no bookmarks or own collections, they can only add text blocks using the plus button.
To add fragments they need to use the search tab.

feat(avo-1912): plus button on pupil collection adds text block

---

src/assignment/views/AssignmentEdit.tsx

When importing a collection from the assignment edit page (plus button => collection)
before:
after:

fix(assignment-edit): import collection under item_meta instead of item

---

src/assignment/modals/AddBookmarkFragmentModal.tsx
src/assignment/modals/AddCollectionModal.tsx
src/assignment/modals/AddItemsModals.scss

so the action buttons are always visible
also make all video thumbnails the same size
before:
after:

feat(add-item-coll-modal): make table scrollable

---

src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponsePupilCollectionTab.tsx

It seems like this one got lost during the big merging

fix(pupil-collection): add block can only be text

---

src/collection/components/CollectionFragmentMeta.tsx

https://meemoo.atlassian.net/browse/AVO-2016

fix(avo-2016): format publish date in fragment metadata

---

src/assignment/components/AssignmentPupilPreview.tsx
src/assignment/views/AssignmentResponseEdit/AssignmentResponseEdit.tsx
src/assignment/views/AssignmentResponseEdit/AssignmentResponseEditPage.tsx

https://meemoo.atlassian.net/browse/AVO-2020
before:
after:

fix(avo-2020): hide back button on preview as pupil

---

src/shared/components/WYSIWYGWrapper/WYSIWYGWrapper.scss

https://meemoo.atlassian.net/browse/AVO-2023
Add outline to rich text editor buttons so it is clear to the user where the focus is during tabbing

fix(avo-2023): add outline to rich text editor buttons

---

src/assignment/assignment.service.ts

https://meemoo.atlassian.net/browse/AVO-2037
* delete answer_url 
* set available_at to duplication date
original assignment:
copied assignment:

fix(avo-2037): remove available_at and answer_url from duplicate

---

src/assignment/views/AssignmentPupilCollectionDetail.tsx

https://meemoo.atlassian.net/browse/AVO-2041
example url:
http://localhost:8080/werkruimte/opdrachten/48b8f26d-a151-4d3c-8809-ca1ee6060f7d/antwoorden/947b030d-dcac-4133-9ad5-12f209c059e3
before:
after:

fix(avo-2041): rename urls params from id to responseId everywhere

---

src/App.scss
src/App.tsx
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx
src/assignment/views/AssignmentResponseEdit/AssignmentResponseEdit.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/shared/components/ConfirmModal/ConfirmModal.tsx

https://meemoo.atlassian.net/browse/AVO-2049
* show unsaved changes modal on top of opened modals
* also show unsaved changes modal during previews

fix(avo-2049): show unsaved changes modal above the other modals

---

src/assignment/views/AssignmentResponses.tsx

https://meemoo.atlassian.net/browse/AVO-1934
also added missing permissions to the database:
- VIEW_OWN_ASSIGNMENT_RESPONSES
- VIEW_ANY_ASSIGNMENT_RESPONSES

fix(avo-1934): correctly check permissions for assignment responses view

---

src/assignment/assignment.service.ts
src/assignment/hooks/assignment-content-modals.tsx

- origineel tab === onediteerbaar, tekst zoals te zien bij het collectie item
- eigen tekst === initieel zelfde tekst als origineel, maar wel editeerbaar
De toggle voor importeren met/zonder beschrijving heeft geen invloed op de overgenomen data, maar wel op welk tabje (origineel/geen beschrijving) standaard 'actief' is na importeren in de opdracht

fix(avo-2076): update collection import logic

---

src/assignment/views/AssignmentResponseEdit/AssignmentResponseEdit.tsx

https://meemoo.atlassian.net/browse/AVO-2087
After this PR only tab values that match the assignment type are allowed:
For an assignment with type: KIJK:
* ?tab=MY_COLLECTION => ?tab=ASSIGNMENT
* ?tab=SEARCH => ?tab=ASSIGNMENT
* ?tab=BLABLA => ?tab=ASSIGNMENT
for an assignment with type: ZOEK:
* ?tab=MY_COLLECTION => ?tab=ASSIGNMENT
* ?tab=SEARCH => ?tab=SEARCH
* ?tab=BLABLA => ?tab=ASSIGNMENT
for an assignment with type: BOUW:
* ?tab=MY_COLLECTION => ?tab=MY_COLLECTION 
* ?tab=SEARCH => ?tab=SEARCH
* ?tab=BLABLA => ?tab=ASSIGNMENT

fix(avo-2087): reset active tab if no search or build assignment

---

src/assignment/views/AssignmentEdit.tsx
src/collection/collection.gql.ts
src/collection/collection.service.ts

https://meemoo.atlassian.net/browse/AVO-2114
I'm guessing the collection was removed and the bookmark was not?
We'll need to investigate this further in the future.
before: blank screen because of error:
```
Cannot read properties of null (reading 'id')
```
after:

fix(avo-2114): avoid collections that are null in bookmarks

---

src/App.tsx

https://meemoo.atlassian.net/browse/AVO-2045
pupils do not see the widget anymore:
other user groups and logged out users still see the widget:

feat(avo-2045): hide zendesk widget for logged in pupils

---

src/assignment/assignment.gql.ts

https://meemoo.atlassian.net/browse/AVO-2103
requires proxy PR to whitelist the modified query: https://github.com/viaacode/avo2-proxy/pull/480
before:
after:

fix(avo-2103): only count items in responses overview, no text blocks

---

public/index.html
scripts/add-cookiebot-ignore-attributes.ts

https://meemoo.atlassian.net/browse/AVO-2133
Vroeger was het formaat:
```
<script src="/static/js/main.c866a515.chunk.js"></script></body></html>
```
en nu is het formaat:
```
<script  defer="defer" src="/static/js/main.c866a515.js"></script>
```

fix(avo-2133): change cookiebot script to account for new script format

---

src/shared/components/ACMIDMNudgeModal/ACMIDMNudgeModal.tsx

https://meemoo.atlassian.net/browse/AVO-2156
We'll only be able to test this on QAS, but from debugging QAS, it is clear what the issue is:

fix(avo-2156): don't show nudging modal when user logs in using leerid

---

src/admin/admin.const.ts

https://meemoo.atlassian.net/browse/AVO-1454
before:
after:

fix(avo-1454): remove some content page link from the admin sidebar

---

public/index.html

https://meemoo.atlassian.net/browse/AVO-1545
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/501
If no localstorage detected or accessing localstorage throws an error, we redirect the browser to a backend error page.

fix(avo-1545): detect no localstorage, redirect to backend error page

---

src/admin/content-block/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx
src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponseSearchTab.tsx
src/shared/hooks/scroll-to-selector.ts

https://meemoo.atlassian.net/browse/AVO-1473
if the label query param has a value scroll down to the first page overview block on the page if it exists
page used in the example: https://onderwijs-qas.hetarchief.be/partners
before:
https://user-images.githubusercontent.com/1710840/192516065-7b8caa69-37ca-4c64-9eed-13b435a00b34.mp4
after:
https://user-images.githubusercontent.com/1710840/192516060-a42bbc6f-706f-4e8e-9156-dbe7e5e9e83a.mp4

feat(avo-1473): scroll to overview block when url contains label param

---

src/admin/content-block/components/ContentBlockPreview/ContentBlockPreview.scss

https://meemoo.atlassian.net/browse/AVO-1672
We want the headings to decrease 1 by 1 for seo reasons. But an h2 is too large esthetically.
So for page overview blocks we resize the h2 font size to 2.1 instead of 2.4 rem
in https://meemoo.atlassian.net/browse/AVO-2176 we'll make this configurable, so the user can choose their own size. But this task should best be taken up after the integration of the admin-core in avo.

fix(avo-1672): make the h2 titles in a page overview block smaller

---

src/shared/components/ACMIDMNudgeModal/ACMIDMNudgeModal.tsx
src/shared/services/profile-preferences.service.ts

Currently the nudging modal is visible after logging in with itsme.
That is probably due to:
```
const hasVlaamseOverheidLinked =
!!user &&
hasIdpLinked(user, 'VLAAMSEOVERHEID__SUB_ID') &&
hasIdpLinked(user, 'VLAAMSEOVERHEID__ACCOUNT_ID');
```
which should be using an OR operator:
```			
const hasVlaamseOverheidLinked =
!!user &&
(hasIdpLinked(user, 'VLAAMSEOVERHEID__SUB_ID') ||
hasIdpLinked(user, 'VLAAMSEOVERHEID__ACCOUNT_ID'));
```
But also this doesn't seem to react to changes in routes, since we only update the show/hide modal if certain conditions are true. But we should also hide it, in the other case when the conditions are false.
```
if (user && !isOnAccountLinkingPage && (!isPupil || (isPupil && !isOnAssignmentPage))) {
fetchProfilePreference();
}
```

fix(avo-2136): rework nudging modal show/hide

---

package-lock.json
package.json
src/quick-lane/views/QuickLaneDetail.tsx
src/search/components/BlockSearch.tsx
src/search/views/Search.tsx
src/shared/services/event-logging-service.ts

https://meemoo.atlassian.net/browse/AVO-1895
https://meemoo.atlassian.net/browse/AVO-2177
also fixed event url => split url from query params
event for search on homepage:
event for search on search page:
event for search from assignment page:

fix(avo-1895): track search events + disable quick_lane events for now

---

src/admin/users/user.const.ts
src/admin/users/user.gql.ts
src/admin/users/user.service.ts
src/admin/users/user.types.ts
src/admin/users/views/UserDetail.tsx
src/admin/users/views/UserOverview.tsx

https://meemoo.atlassian.net/browse/AVO-2129
Requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/508
This should make the get users query less resource intensive when no blocked_at or unblocked_at filters are used.

fix(avo-2129): change queries to use last blocked at

---

package-lock.json
package.json

https://meemoo.atlassian.net/browse/AVO-2221
only when screen width is > 700px
example: http://localhost:8080/item/x34mk94f4m
code is located in this commit on avo2 components: https://github.com/viaacode/avo2-components/commit/91d98856c99464ab216446e756c29552450ed2d7
```
@media (min-width: $g-bp2) {
.fp-captions {
font-size: 43px; // https://meemoo.atlassian.net/browse/AVO-2221
}
}
```
before:
after:

fix(avo-2221): increase subtitle fontsize when flowplayer is fullscreen

---

src/admin/content-block/components/wrappers/MediaGridWrapper/MediaGridWrapper.tsx

https://meemoo.atlassian.net/browse/AVO-2175
before:
after:

fix(avo-2175): correctly set audio still svg in media grid block

---

src/assignment/components/modals/ManageAssignmentLabels.translations.ts
src/assignment/components/modals/ManageAssignmentLabels.tsx

I'd like to move forward separating translations from components with something like this; thoughts?

feat(avo-2159): adjust how to handle translations

---

src/admin/assignments/assignments.const.ts
src/admin/collectionsOrBundles/collections-or-bundles.const.ts
src/admin/content-page-labels/views/ContentPageLabelOverview.tsx
src/admin/content/content.const.tsx
src/admin/interactive-tour/interactive-tour.const.ts
src/admin/items/items.const.ts
src/admin/items/views/ItemDetail.tsx
src/admin/pupil-collection/pupil-collection.const.ts
src/admin/shared/components/FilterTable/FilterTable.tsx
src/admin/users/user.const.ts
src/collection/components/CollectionOrBundleEditAdmin.tsx
src/quick-lane/components/AssociatedQuickLaneTable.tsx
src/shared/components/QuickLaneFilterTableCell/QuickLaneFilterTableCell.tsx
src/shared/constants/quick-lane.ts
src/workspace/views/QuickLaneOverview.tsx

This helps with the GRAPHQL query => REST endpoint migration
since we get typescript errors if the column ids do not match the correct columnId type

fix(avo-2210): Add better typing for FilterableColumn ids

---

src/dynamic-route-resolver/dynamic-route-resolver.const.ts

The /projecten/klaar page has been changed to /projecten/uitgeklaard
In various content pages, they still reference /projecten/klaar
This PR adds a redirect from /projecten/klaar to /projecten/uitgeklaard to the dynamic route resolver component
You can test the redirect by visiting: http://localhost:8080/projecten/klaar

feat(avo-2343): redirect klaar to uitgeklaard project page

---

src/collection/components/modals/CutFragmentModal.tsx
src/item/components/modals/AddToCollectionModal.tsx
src/shared/helpers/set-modal-video-seek-time.ts

Sometimes the cut video modal can get into a state where the range control does not update the video.
https://user-images.githubusercontent.com/1710840/210817760-917aad1a-355a-43a1-ab27-7c5648839e25.mp4
This is because there can be 2 videos in different modals, and we're updating the wrong video in a hidden modal:
Also when you move the range control, the video does not jump to that location after the video initializes.
So i added an onPlay once handler to set the video start point to the start cuepoint when the video is initialized.

fix(avo-2239): set player start point when initializing + select visible

---

src/admin/content-page/content-page.routes.tsx

/content/maak needs a higher priority than route: /content/:id otherwise maak is interpreted as :id

fix(content-page): ensure create route has priority over detail route

---

src/admin/content-page/views/ContentPage.scss
src/admin/shared/hoc/with-admin-core-config.const.tsx
src/admin/shared/layouts/AdminLayout/AdminLayout.scss
src/styles/components/_content-page.scss
src/styles/components/_index.scss
src/styles/settings/_variables.scss

before: whole page scrolls
after: each side panel scrolls separately
avo button types are selectable and are styled correctly through styles in avo2-client:

fix(content-page): fix content page button styles and edit page layout

---

src/App.tsx
src/admin/shared/layouts/AdminLayout/AdminLayout.scss

https://meemoo.atlassian.net/browse/AVO-2371
pagina: https://onderwijs-qas.hetarchief.be/instellingen/koppelingen
before:
after:

fix(avo-2371): show success link account toast after translations were loaded

---

src/admin/users/views/UserDetailPage.scss
src/admin/users/views/UserDetailPage.tsx

https://meemoo.atlassian.net/browse/AVO-2373
fix styling on the user detail page
page: http://localhost:8080/admin/gebruikers/69ccef3b-751a-4be4-95bc-5ef365fbd504
before:
after:

fix(avo-2373): fix styling on the user detail page

---

src/admin/content-page/views/ContentPageDetailPage.tsx
src/admin/content-page/views/ContentPageEditPage.tsx
src/admin/shared/hoc/with-admin-core-config.const.tsx
src/styles/admin-core/_back-button.scss
src/styles/admin-core/_index.scss
src/styles/admin-core/_spinner.scss

https://meemoo.atlassian.net/browse/AVO-2375
requires PR: https://github.com/viaacode/react-admin-core-module/pull/104
page:
* http://localhost:8080/admin/gebruikers/a900a663-c319-4b3c-99da-ede663ad29fc
* http://localhost:8080/admin/gebruikers/a900a663-c319-4b3c-99da-ede663ad29fc/bewerk
* http://localhost:8080/admin/content/1529
* http://localhost:8080/admin/content/1529/bewerk
* http://localhost:8080/admin/navigatie/footer-links
* http://localhost:8080/admin/navigatie/footer-links/1/bewerk
before:
after:

fix(avo-2375): add back buttons to detail and edit pages

---

src/admin/shared/layouts/AdminLayout/AdminLayout.scss

https://meemoo.atlassian.net/browse/AVO-2359
page: http://localhost:8080/admin/gebruikers
before:
after:

fix(avo-2359): make border for first column specific to translations

---

src/assignment/views/AssignmentResponseEdit/tabs/AssignmentResponseSearchTab.tsx

https://meemoo.atlassian.net/browse/AVO-2398
page: http://localhost:8080/opdrachten/7bb060ea-b70e-4200-9fdb-efd9e7eac5e0?tab=SEARCH
before:
after:

fix(avo-2398): reset cuepoints for cutting videos when modal closes

---

src/search/components/MediaGridWrapper/MediaGridWrapper.tsx

https://meemoo.atlassian.net/browse/AVO-2391
page: http://localhost:8080/admin/content/maak
before:
after:

fix(avo-2391): show default audio still in the media tiles block

---

package-lock.json
package.json

https://meemoo.atlassian.net/browse/AVO-2433
bumps version of the avo2-components to include pagination icons fix:
https://github.com/viaacode/avo2-components/commit/a16f32b1fd2250a19c3074dcd47f9f21c9ef0d7e
before:
after:

fix(avo-2433): bump avo2-components to include fix for pagination icons

---

package-lock.json
package.json

https://meemoo.atlassian.net/browse/AVO-2396
bumps avo2-components to fix the perfect-scrollbar library styles:
https://github.com/viaacode/avo2-components/commit/e264a072f758bda3331ed9cc953c3f9501c8992d
before:
after:

fix(avo-2396): bump avo2-component version to fix modal scrollbars

---

src/App.tsx
src/admin/Admin.tsx

https://meemoo.atlassian.net/browse/AVO-2450
pupil should not see the widget:
other users should see the widget:
except on the admin dashboard screens:

fix(avo-2450): show hide zendesk widget using css only

---

src/bundle/views/BundleDetail.tsx
src/collection/collection.service.ts
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleOverview.tsx
src/collection/queries/delete-collection-or-bundle-by-uuid.graphql
src/collection/queries/soft-delete-collection-by-id.graphql
src/collection/views/CollectionDetail.tsx
src/shared/generated/graphql-db-types.ts
src/shared/services/bookmarks-views-plays-service/queries/delete-collection-bookmarks.graphql

https://meemoo.atlassian.net/browse/AVO-2441
requires proxy PR: https://github.com/viaacode/avo2-proxy/pull/597
When you add a collection to a bundle:
and then you delete the collection.
before: the collection is not correctly removed from the bundle:
after: the collection is correctly removed from the bundle:

fix(avo-2441): delete collection also from bundles

---

src/collection/components/CollectionOrBundleOverview.tsx

AVO-[2620](https://meemoo.atlassian.net/browse/AVO-2620)
Before: 
After:

fix(avo-2620): Move render header function in orde to display filter in every situation

---

src/assignment/components/AssignmentAdminFormEditable.tsx

[AVO-2672](https://meemoo.atlassian.net/browse/AVO-2672)
Added missing permission in Hasura
Before: 
After:
[AVO-2672]: https://meemoo.atlassian.net/browse/AVO-2672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2672): remove briefings form group and add permission to edit assignment quality labels

---

src/shared/components/HeaderOwnerAndContributors/HeaderOwnerAndContributors.tsx

[AVO-2608](https://meemoo.atlassian.net/browse/AVO-2608)
Before:
After:
[AVO-2608]: https://meemoo.atlassian.net/browse/AVO-2608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2608): Add spacing between contributors and previous word

---

src/assignment/views/AssignmentEdit.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/shared/constants/index.ts

https://meemoo.atlassian.net/browse/AVO-2776
before:
after:

fix(avo-2776): hide toast message if statuscode indicates no access

---

src/assignment/components/AssignmentHeading.scss
src/styles/components/_index.scss
src/styles/components/tabs.scss

https://meemoo.atlassian.net/browse/AVO-2771
before:
after:

fix(avo-2771): ensure tabs and scrollbar don't go through options menu

---

src/assignment/components/AssignmentHeading.scss

[AVO-2787](https://meemoo.atlassian.net/browse/AVO-2787)
Before:
After:
[AVO-2787]: https://meemoo.atlassian.net/browse/AVO-2787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2787): up the z-index of assignment edit action bars

---

src/collection/views/CollectionDetail.tsx
src/item/views/ItemDetail.tsx

https://meemoo.atlassian.net/browse/AVO-2807
proxy PR: https://github.com/viaacode/avo2-proxy/pull/678
after:
collection link:
quick link:
public assignment:
private assignment:

fix(avo-2807): only load collection for pupil if quick link exists

---

src/assignment/hooks/assignment-teacher-tabs.tsx
src/assignment/views/AssignmentCreate.tsx
src/assignment/views/AssignmentEdit.tsx

[AVO-2804](https://meemoo.atlassian.net/browse/AVO-2804)
[AVO-2809](https://meemoo.atlassian.net/browse/AVO-2809)
[Avo2-client PR](https://github.com/viaacode/avo2-client/pull/1861)
[Avo2-proxy PR](https://github.com/viaacode/avo2-proxy/pull/680)
[Avo2-typings PR](https://github.com/viaacode/avo2-typings/pull/131)
Before:
After:
[AVO-2804]: https://meemoo.atlassian.net/browse/AVO-2804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AVO-2809]: https://meemoo.atlassian.net/browse/AVO-2809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2796): add publish and admin tab to assignment create page, adjust permissions for showing admin tab

---

src/assignment/modals/DeleteAssignmentModal.tsx

[AVO-2824](https://meemoo.atlassian.net/browse/AVO-2824)
Before:
After:
[AVO-2824]: https://meemoo.atlassian.net/browse/AVO-2824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2824): move warning messages inside is shared with others check

---

src/shared/components/HeaderOwnerAndContributors/HeaderOwnerAndContributors.tsx

[AVO-2847](https://meemoo.atlassian.net/browse/AVO-2847)
Before:
After:
[AVO-2847]: https://meemoo.atlassian.net/browse/AVO-2847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2847): fix header owners and contributors containing viewers

---

src/search/components/SearchResultItem.tsx

[AVO-2858](https://meemoo.atlassian.net/browse/AVO-2858)
Before:
After:
[AVO-2858]: https://meemoo.atlassian.net/browse/AVO-2858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2858): fix profile picture on searchresult

---

src/assignment/views/AssignmentResponseEdit/AssignmentResponseEdit.tsx

[AVO-2855](https://meemoo.atlassian.net/browse/AVO-2855)
Before:
After:
[AVO-2855]: https://meemoo.atlassian.net/browse/AVO-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif

fix(avo-2855): fix pupil assignment title alignment

---

src/assignment/views/AssignmentDetail.tsx

[AVO-2851](https://meemoo.atlassian.net/browse/AVO-2851)
Before:
After:
[AVO-2851]: https://meemoo.atlassian.net/browse/AVO-2851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2851): fix assignment detail video fragments title not clickable

---

src/constants.ts

In useGetInteractiveTourForPage.ts the route pairs list is reversed, so ASSIGNMENT_CREATE was seen as ASSIGNMENT_DETAIL. Fix: by switching the order ASSIGNMENT_CREATE is found first and a tour is available.
Ticket: https://meemoo.atlassian.net/browse/AVO-2923

fix(avo-2923): switch url order for InteractiveTour

---

src/shared/components/TimeCropControls/TimeCropControls.tsx
src/shared/services/video-stills-service.ts

First:
Then:
Also had issue:
Ticket: https://meemoo.atlassian.net/browse/AVO-2971

fix(avo-2971): fix timecrop bug + previewImagePath bug

---

src/assignment/views/AssignmentOverview.tsx

Before:
After:
Ticket: https://meemoo.atlassian.net/browse/AVO-3044

fix(avo-3044): use tHtml so p-tags are not shown

---

src/admin/shared/components/ContentPicker/ContentPicker.tsx
src/admin/shared/components/ContentPicker/item-providers/profile.ts

https://meemoo.atlassian.net/browse/AVO-3010
requires proxy pr: https://github.com/viaacode/avo2-proxy/pull/697
* use custom queries that only fetch the name, email and id of the user and don't use the heave users_summary_view
* switch to backend routes for these queries

feat(AVO-3010): improve performance of the content picker for profiles

---

src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.scss

Before:
After:
Ticket: https://meemoo.atlassian.net/browse/AVO-2724

fix(avo-2724): show bijschrift under videoplayer

---

src/assignment/assignment.types.ts
src/assignment/components/AssignmentDetailsFormEditable.tsx
src/assignment/components/AssignmentMetaDataFormEditable.tsx
src/assignment/components/AssignmentTitle.tsx
src/assignment/components/blocks/AssignmentBlockEditText.tsx
src/assignment/hooks/use-edit-blocks.tsx
src/assignment/views/AssignmentEdit.tsx
src/collection/components/CollectionOrBundleEdit.tsx
src/collection/components/CollectionOrBundleEditActualisation.tsx
src/collection/components/CollectionOrBundleEditAdmin.tsx
src/collection/components/CollectionOrBundleEditContent.tsx
src/collection/components/CollectionOrBundleEditMarcom.tsx
src/collection/components/CollectionOrBundleEditMetaData.tsx
src/collection/components/CollectionOrBundleEditQualityCheck.tsx
src/collection/components/CollectionOrBundleTitle.tsx
src/collection/components/fragment/FragmentEdit.tsx
src/shared/components/ShortDescriptionField/ShortDescriptionField.tsx
src/shared/components/TitleDescriptionForm/TitleDescriptionForm.tsx

Ticket: https://meemoo.atlassian.net/browse/AVO-2721
**Check avo2-components commit**: https://github.com/viaacode/avo2-components/commit/6f906d522d069d64834fd2ef5fc82f61b1f9c5a6

feature/AVO-2721: add onFocus on Edit assignment page and edit collection page

---

src/styles/components/_content-page.scss

https://meemoo.atlassian.net/browse/AVO-3002
this bug seems to be caused by the fix of https://meemoo.atlassian.net/browse/AVO-2926
so this pr tries to tweak the solution for AVO-2926 to solve both AVO-2926 and AVO-3002
replaced this PR:  https://github.com/viaacode/react-admin-core-module/pull/218

fix(avo-3002): fix padding in paragraphs in c-content divs

---

src/shared/components/LomFieldsInput/LomFieldsInput.tsx

https://meemoo.atlassian.net/browse/AVO-2881
before:
after:

fix(AVO-2881): only childless edu levels/degrees in complete profile

---

src/admin/content-page/components/blocks/MediaGridWrapper/MediaGridWrapper.tsx
src/admin/shared/hoc/with-admin-core-config.const.tsx

https://meemoo.atlassian.net/browse/AVO-3015
requires proxy and admin-core PRs:
* https://github.com/viaacode/avo2-proxy/pull/713
* https://github.com/viaacode/react-admin-core-module/pull/222
before:
after:

fix(AVO-3015): show audio still for audio items, show copyright in admin

---

src/admin/shared/components/ContentPicker/helpers/parse-picker.ts

https://meemoo.atlassian.net/browse/AVO-3113
Mirror of https://github.com/viaacode/react-admin-core-module/pull/226

fix(AVO-3113): return empty instead of untranslated string

---

.eslintrc.js
package-lock.json
package.json
src/shared/components/FlowPlayerWrapper/FlowPlayerWrapper.tsx
src/workspace/workspace.routes.tsx

on windows this package gives an error:
```
"C:\Program Files\nodejs\npm.cmd" install
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @esbuild/darwin-arm64@0.20.1: wanted {"os":"darwin","cpu":"arm64"} (current: {"os":"win32","cpu":"x64"})
npm ERR! notsup Valid os:   darwin
npm ERR! notsup Actual os:  win32
npm ERR! notsup Valid cpu:  arm64
npm ERR! notsup Actual cpu: x64
npm ERR! A complete log of this run can be found in: C:\Users\bert\AppData\Local\npm-cache\_logs\2024-02-28T08_37_50_539Z-debug-0.log
Process finished with exit code 1
```
Maybe this PR can be a solution for all devices/OS's
More info:
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies

fix(package.json): move apple m1 package to optional dependencies

---

src/admin/assignments/views/AssignmentsOverviewAdmin.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleActualisationOverview.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleMarcomOverview.tsx
src/admin/collectionsOrBundles/views/CollectionOrBundleQualityCheckOverview.tsx
src/admin/collectionsOrBundles/views/CollectionsOrBundlesOverview.tsx
src/shared/components/CollectionOrBundleOrAssignmentTitleAndCopyTag/CollectionOrBundleOrAssignmentTitleAndCopyTag.tsx
src/shared/helpers/render-collection-or-bundle-or-assignment-title-and-copy-tag.tsx

https://meemoo.atlassian.net/browse/AVO-3132
* make one render function for rendering titles and kopie label
* unnest the link for the title from the link of the copy label
* use function on pages
* assignment overview
* collection/bundle overview
* collection/bundle actualisation overview
* collection/bundle quality overview
* collection/bundle communication overview
* replace usage of lodash get function with elvis operator ?.
* replace ReactText with ReactNode
* fix error in author user group filter property: tableState.author.user_groups => tableState.author_user_group

fix(AVO-3132): split copy link from title link for coll, bun. & assign.

---

src/settings/components/CompleteProfileStep.tsx
src/settings/components/Email/Email.tsx
src/shared/services/campaign-monitor-service.ts
src/shared/services/event-logging-service.ts

https://meemoo.atlassian.net/browse/AVO-3309
keeps track of subscribe and unsubscribe actions during the registration fase and in the accounts menu
registration process
account email preferences:

feat(AVO-3309): add logging events for un-,subscribe to newsletters

---

vite.config.js

https://meemoo.atlassian.net/browse/AVO-3336
requires hasura PR: https://github.com/viaacode/hasura-graphql/pull/130
before:
after:

fix(AVO-3336): remove the hash from the audio still asset url

---

src/shared/components/QuickLaneModal/QuickLaneModal.helpers.tsx
src/shared/components/QuickLaneModal/QuickLaneModalSharingTab.tsx

One more known issue occurs when dragging the end handle over the start handle; also occurs on assignments so out of scope for this ticket considering the issue is likely inside of TimeCropControls.

feat(AVO-3380): avoid most cases of zero-ended crops

---

src/embed/hooks/useGetLoginStateForEmbed.ts

Every time the user was focussing the iframe, the app was checking the login state, triggering a re-render because the loginstate changed although nothing changed.

AVO-3725: avoid rerendering the embed app when the user is already logged in
